### ISSUE TITLE
是否可以支持图片接收？

### ISSUE THREAD

**Issue by 1715819** [dreamhunter2333/cloudflare_temp_email#1]

**Comment by dreamhunter2333** [comment]
可以支持附件，目前没有保存和展示附件

**Comment by dreamhunter2333** [comment]
已支持
<img width="1152" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/a7811e2c-12f7-4e17-ad11-9f644ae284e2">
