### ISSUE TITLE
Couldn't find a D1 DB with the name or binding 'dev' in wrangler.toml

### ISSUE THREAD

**Issue by 1715819** [dreamhunter2333/cloudflare_temp_email#100]
这个问题怎么解决呢

**Comment by 1715819** [comment]
ok，解决了

**Comment by purepoorx** [comment]
> ok，解决了

刚想部署就遇到这个问题，请问如何解决的

**Comment by Zding89** [comment]
请问怎么解决？

**Comment by dreamhunter2333** [comment]
> 请问怎么解决？

参考 D1 的配置和绑定到 worker 
https://temp-mail-docs.awsl.uk/zh/guide/cli/d1.html

**Comment by EaxMov** [comment]
不知道是不是文档不全还是什么问题，要手动创建一个wrangler.toml文件
然后写入以下内容
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "dev"
database_id = "e1f2e29c-c976-4066-959e-d53c1b627f51"

**Comment by 1715819** [comment]
> 请问怎么解决？

wrangler d1 execute dev --remote --file=db/schema.sql
试一下这个

**Comment by dreamhunter2333** [comment]
> 不知道是不是文档不全还是什么问题，要手动创建一个wrangler.toml文件
> 
> 然后写入以下内容
> 
> [[d1_databases]]
> 
> binding = "DB" # i.e. available in your Worker on env.DB
> 
> database_name = "dev"
> 
> database_id = "e1f2e29c-c976-4066-959e-d53c1b627f51"

了解了，应该是文档的顺序问题，创建文件在 worker 部署那一步
