### ISSUE TITLE
可以添加自定义邮箱地址的功能吗？

### ISSUE THREAD

**Issue by 1715819** [dreamhunter2333/cloudflare_temp_email#11]
类似于forsaken mail 那样可以自定义邮箱地址。

**Comment by dreamhunter2333** [comment]
可以增加自定义地址，我稍后增加一下

**Comment by dreamhunter2333** [comment]
<img width="1188" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/b27c05a5-cb8b-4b26-8d25-9a0e73fecfbb">

**Comment by 1715819** [comment]
666
