### ISSUE TITLE
可以考虑生成现成的js，通过环境变量来修改参数吗？

### ISSUE THREAD

**Issue by Zding89** [dreamhunter2333/cloudflare_temp_email#115]
wrangler安装比较费劲~换台设备又得从来，希望作者考虑下生成现成的js文件去部署，感谢

**Comment by dreamhunter2333** [comment]
好的，我研究一下怎么搞

**Comment by dreamhunter2333** [comment]
已添加通过用户界面部署的文档
https://temp-mail-docs.awsl.uk/zh/guide/quick-start.html

**Comment by Zding89** [comment]
效率
