### ISSUE TITLE
功能很实用。

### ISSUE THREAD

**Issue by fxecc** [dreamhunter2333/cloudflare_temp_email#12]
确实很方便，还添加了登录。
前端有点丑，最好最加个中文能自动识别浏览器语言。

**Comment by dreamhunter2333** [comment]
是的，我前端水平有限，多语言也在考虑中，哈哈

**Comment by dreamhunter2333** [comment]
已支持多语言
<img width="1167" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/4d749b58-cf2c-4948-b87f-b10aeca6cb8f">
