### ISSUE TITLE
发送邮件时为邮件添加DKIM签名

### ISSUE THREAD

**Issue by sunnywangzi** [dreamhunter2333/cloudflare_temp_email#121]
参考
https://support.mailchannels.com/hc/en-us/articles/7122849237389-Adding-a-DKIM-Signature

**Comment by dreamhunter2333** [comment]
感谢，我看一下集成到当前系统

**Comment by dreamhunter2333** [comment]
main 分支已支持，之后我会打一个新版 tag

**Comment by dreamhunter2333** [comment]
https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.7
