### ISSUE TITLE
在管理后台添加查询已发送的邮件

### ISSUE THREAD

**Issue by sunnywangzi** [dreamhunter2333/cloudflare_temp_email#124]
管理员可以在后台查询已经发送出去的邮件

**Comment by dreamhunter2333** [comment]
OK 可以在管理员面板加下和收件箱一样，按邮箱查询发件箱

**Comment by dreamhunter2333** [comment]
最新版已增加 https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.6
<img width="1229" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/c9a6b734-58e0-4af2-aec4-9ce1420a03a1">
