### ISSUE TITLE
 一键删除数据库中所有已接收邮件

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#125]
希望可以在管理员面板，一键删除数据库中所有已接收邮件（避免超过D1免费版容量限制），但是已建立的邮箱要继续保存。

**Comment by xiewei3536** [comment]
或者有没有可能让每封邮件只会保存24小时，到期自动删除？
感谢大佬

**Comment by dreamhunter2333** [comment]
OK 可以加个定时清除和管理员清理邮件

**Comment by dreamhunter2333** [comment]
最新版已添加 https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.6
<img width="1211" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/4a266217-a2e2-4440-99e4-4dbe834ff688">

**Comment by xiewei3536** [comment]
> 最新版已添加 https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.6 <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/32295532/322280977-4a266217-a2e2-4440-99e4-4dbe834ff688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDU1ODMsIm5iZiI6MTcxMzE0NTI4MywicGF0aCI6Ii8zMjI5NTUzMi8zMjIyODA5NzctNGEyNjYyMTctYTJlMi00NDQwLTk5ZTQtNGRiZTgzNGZmNjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAxNDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwN2NmYzUxNzU2MWMwMmNjNTI4YzZiY2Q0OTMzODI3ODQxNzlhMWFjMWQ1YjRhZmQzNzE1MzI2YTljMDczMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7k7lmzSJf0Ys_0tSPJjbGWFmWO5wU9PFMz-5mWGPHNc">

 大佬，我按了清理30天前无收件人的邮件，但还是可以查询的到，请问是哪里有问题呢？感谢！

**Comment by xiewei3536** [comment]
清理发件箱也不行
其他清理功能还没有测试

**Comment by dreamhunter2333** [comment]
> > 最新版已添加 https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.6 <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/32295532/322280977-4a266217-a2e2-4440-99e4-4dbe834ff688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDU1ODMsIm5iZiI6MTcxMzE0NTI4MywicGF0aCI6Ii8zMjI5NTUzMi8zMjIyODA5NzctNGEyNjYyMTctYTJlMi00NDQwLTk5ZTQtNGRiZTgzNGZmNjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAxNDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwN2NmYzUxNzU2MWMwMmNjNTI4YzZiY2Q0OTMzODI3ODQxNzlhMWFjMWQ1YjRhZmQzNzE1MzI2YTljMDczMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7k7lmzSJf0Ys_0tSPJjbGWFmWO5wU9PFMz-5mWGPHNc">
> 
>  大佬，我按了清理30天前无收件人的邮件，但还是可以查询的到，请问是哪里有问题呢？感谢！

我测试一下

**Comment by dreamhunter2333** [comment]
> 清理发件箱也不行 其他清理功能还没有测试

测试了下，都成功了，清理天数在 0 - 30 天之间
<img width="756" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/7889c2e1-8a79-4f87-b628-198abccbbfc2">
