### ISSUE TITLE
发送邮件显示500 Error

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#145]
大佬，我更新到最新版本，也配置完DKIM。但是发送邮件一直跳出500 error，请问要如何解决，感谢！

 "logs": [
    {
      "message": [
        "TypeError: Cannot destructure property 'address' of 'c.get(...)' as it is undefined."
      ],
      "level": "error",
      "timestamp": 1713659721033
    }
  ],

**Comment by xiewei3536** [comment]
<img width="587" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/831b7aff-dded-4ec5-a95c-04ccb0052371">

大佬，我测试你搭建的，同样也是500 error

**Comment by dreamhunter2333** [comment]
我检查下，可能是最新代码有些问题

**Comment by dreamhunter2333** [comment]
已修复，main 分支的逻辑有些问题

**Comment by xiewei3536** [comment]
谢谢大佬！已更新也正常运行了

> 已修复，main 分支的逻辑有些问题
