### ISSUE TITLE
zip无法下载问题

### ISSUE THREAD

**Issue by gushan123** [dreamhunter2333/cloudflare_temp_email#147]
调试工具说访问https://temp-mail-docs.awsl.uk/ui_install/frontend.zip返回状态码404

**Comment by gushan123** [comment]
解决了，是我愚蠢了，我跑去问了一下chatgpt才知道是要输入文件里的内容

**Comment by gushan123** [comment]
我在github上下载了frontend文件夹上传之后搭建了https://mail-6bp.pages.dev/
访问是空白页面

**Comment by dreamhunter2333** [comment]
我测试下，可能最新版有点问题， github直接下载是不能使用的，需要更改下后端的 url

**Comment by dreamhunter2333** [comment]
暂时通过命令行部署吧，文档打包少了文件，我晚上重新部署下文档

**Comment by gushan123** [comment]
> 暂时通过命令行部署吧，文档打包少了文件，我晚上重新部署下文档

不会用命令行，哈哈哈

**Comment by dreamhunter2333** [comment]
> > 暂时通过命令行部署吧，文档打包少了文件，我晚上重新部署下文档
> 
> 
> 
> 不会用命令行，哈哈哈

那我晚上更新一下

**Comment by gushan123** [comment]
> > > 暂时通过命令行部署吧，文档打包少了文件，我晚上重新部署下文档
> > 
> > 
> > 不会用命令行，哈哈哈
> 
> 那我晚上更新一下

好的，感谢！我去下载之前的版本的frontend文件有没有用？

**Comment by dreamhunter2333** [comment]
一个临时的解决方案，从这里下载 zip, https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.7

修改里面的 index-xxx.js 文件 ，xx 是随机的字符串，搜索

https://temp-email-api.xxx.xxx ，替换成你worker 的域名

**Comment by gushan123** [comment]
> 一个临时的解决方案，从这里下载 zip, https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.7
> 
> 修改里面的 index-xxx.js 文件 ，xx 是随机的字符串，搜索
> 
> https://temp-email-api.xxx.xxx ，替换成你worker 的域名，然后部署新的zip文件
> 
> (其实文档里的按钮就是在做这件事

创建Cloudflare workers 后端打开域名应该要显示Hello world还是Not Found

**Comment by gushan123** [comment]
> 一个临时的解决方案，从这里下载 zip, https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.7
> 
> 修改里面的 index-xxx.js 文件 ，xx 是随机的字符串，搜索
> 
> https://temp-email-api.xxx.xxx ，替换成你worker 的域名，然后部署新的zip文件
> 
> (其实文档里的按钮就是在做这件事

大佬，我搭建出页端了，但是生成邮箱时提示Code 500: Failed to create address

**Comment by gushan123** [comment]
> 一个临时的解决方案，从这里下载 zip, https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.7
> 
> 修改里面的 index-xxx.js 文件 ，xx 是随机的字符串，搜索
> 
> https://temp-email-api.xxx.xxx ，替换成你worker 的域名，然后部署新的zip文件
> 
> (其实文档里的按钮就是在做这件事

我看到其他人也遇到了，你说解决了，但是我下载了新版好像还是会这样

**Comment by dreamhunter2333** [comment]
最新文档已修复
