### ISSUE TITLE
无法创建邮箱

### ISSUE THREAD

**Issue by gushan123** [dreamhunter2333/cloudflare_temp_email#148]
提示Code 500: Failed to create address

**Comment by dreamhunter2333** [comment]
检查下d1数据库表是否创建好了，可以打开cf 控制台的 worker 后端查看一下日志

**Comment by gushan123** [comment]
> 检查下d1数据库表是否创建好了，worker是否绑定了d1数据库，可以打开cf 控制台的 worker 后端查看一下日志

打扰了哈，我数据库绑错了
