### ISSUE TITLE
启用Worker后无法收信

### ISSUE THREAD

**Issue by gushan123** [dreamhunter2333/cloudflare_temp_email#149]
![80Z0$WZ80~$WFE61VC76DTV](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/101441800/5b4b83f3-cb23-4e9a-8bdf-391ff93250bf)
![K2AINRIPEE WQEZKAJHG( K](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/101441800/de2e185c-08cf-44c5-8e91-69b12554bc81)
![%1UY9T2 {9T 72SFYVITKH0](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/101441800/55736726-79ce-4938-afcf-e59148049572)
![8@@QZ(@925 X O19YXYBAKS](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/101441800/8e93b5fd-a07a-4b9c-9ce4-5f3a8cddc794)
如果设置转发到其他邮箱时就不会被退信，设置了转发到Worker就会被退信

**Comment by gushan123** [comment]
自定义地址是2，目标地址是2

**Comment by gushan123** [comment]
是不是因为我没有配置DKIM？

**Comment by gushan123** [comment]
乱搞乱，又可以接了

**Comment by dreamhunter2333** [comment]
环境变量的 tmp 是否设置了
