### ISSUE TITLE
bug: Admin删除账号后，发件权限控制中仍存留被删除的账号

### ISSUE THREAD

**Issue by lwd-temp** [dreamhunter2333/cloudflare_temp_email#151]
## 复现步骤
登录Admin，删除一个申请过发信权限的账号，在发件权限控制中仍可见被删除的账号。

## 预期行为
登录Admin，删除一个申请过发信权限的账号，也删除它在发件权限控制中的记录。

## 构建配置
构建命令：pnpm build --emptyOutDir
构建输出目录：/dist
根目录：/frontend
源码版本：https://github.com/dreamhunter2333/cloudflare_temp_email/commit/e524f8267490e79cb5905ab2b4bf5f0ef55fdba3

## 浏览器
Microsoft Edge 124

**Comment by lwd-temp** [comment]
附带的另一个bug：删除邮箱Dialog在点击按钮后仍不消失。

**Comment by dreamhunter2333** [comment]
1. 应该也删除它在发件权限控制中的记录，我加一下
2. 按钮后仍不消失看起来是 UI 问题，我修复下
3. 删除账号没有删除发件箱，应该显示，我查一下

**Comment by dreamhunter2333** [comment]
> 1. 应该也删除它在发件权限控制中的记录，我加一下
> 2. 按钮后仍不消失看起来是 UI 问题，我修复下
> 3. 删除账号没有删除发件箱，应该显示，我查一下

main 分支已修复
1. 已增加
2. 已修改 UI
3. 测试如果发送成功可以查询到，检查下查询的地址是否正确
