### ISSUE TITLE
翻译+文档优化

### ISSUE THREAD

**Issue by pdhapy** [dreamhunter2333/cloudflare_temp_email#156]
试了一下没部署成功，手动上传了一下，居然要授权？
不知道除了校验域名信息，会不会回传数据的？虽然只是用CF免费羊毛玩玩，但不是Pro版也被监控着使用还是有点怪怪的。

![Screenshot 2024-04-22 224943](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/94694475/97818fd5-1260-4966-8b16-31aefbfedeab)

**Comment by dreamhunter2333** [comment]
> 试了一下没部署成功，手动上传了一下，居然要授权？ 不知道除了校验域名信息，会不会回传数据的？虽然只是用CF免费羊毛玩玩，但不是Pro版也被监控着使用还是有点怪怪的。
> 
> ![Screenshot 2024-04-22 224943](https://private-user-images.githubusercontent.com/94694475/324523985-97818fd5-1260-4966-8b16-31aefbfedeab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDMxMzksIm5iZiI6MTcxMzgwMjgzOSwicGF0aCI6Ii85NDY5NDQ3NS8zMjQ1MjM5ODUtOTc4MThmZDUtMTI2MC00OTY2LThiMTYtMzFhZWZiZmVkZWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2MjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYWJkMDg3YjBkMmZhMTljOWE0MzA0NWY5NTIxOWU3NDM0ODZkZTNhMTA0NmRjNzIxZGJkNzcyZDc4MTEwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Jrn57o9CadscEtMg1noHnS92XrCSIKWTielF7FyEx4)

授权是给私人站点用的，在 worker 的后台配置密码即可

# 如果你想要你的网站私有，取消下面的注释，并修改密码
# PASSWORDS = ["123", "456"]
# admin 控制台密码, 不配置则不允许访问控制台
# ADMIN_PASSWORDS = ["123", "456"]

**Comment by pdhapy** [comment]
那是我理解错了，抱歉。

这个【授权】建议换成： 网站访问密码，或者是：访问密码
提示语：请输入站点访问密码，以浏览网站

可能会更合适一点。

另：昨晚新版本用命令行部署成功，收信正常，之前手动部署看着说明文档还是有点晦涩的（如果不是开发的同学的话）。

再就是：如果是基于安全考虑，workers部署成功后直接输出【Not Found】其实挺让人困惑的，如果不是找了代码看了下的话，建议是 直接404，然后支持特定的URI关键词来访问并输出提示部署成功，或者在部署文档中提及，输出 Not Found 后为部署成功。

**Comment by dreamhunter2333** [comment]
> 那是我理解错了，抱歉。
> 
> 这个【授权】建议换成： 网站访问密码，或者是：访问密码 提示语：请输入站点访问密码，以浏览网站
> 
> 可能会更合适一点。
> 
> 另：昨晚新版本用命令行部署成功，收信正常，之前手动部署看着说明文档还是有点晦涩的（如果不是开发的同学的话）。
> 
> 再就是：如果是基于安全考虑，workers部署成功后直接输出【Not Found】其实挺让人困惑的，如果不是找了代码看了下的话，建议是 直接404，然后支持特定的URI关键词来访问并输出提示部署成功，或者在部署文档中提及，输出 Not Found 后为部署成功。

1. 我修改下文本描述，确实有歧义，
2. 手动部署的文档我看看能不能优化
3. workers 成功的验证我加一下

**Comment by dreamhunter2333** [comment]
main 分支已更改 文本描述 和 workers 成功的验证

<img width="534" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/6a01d8d9-e411-47fe-8b98-8ba29b032ee7">

<img width="790" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/34f50cfb-cdc0-4371-94fb-9655882c66e5">

**Comment by pdhapy** [comment]
厉害！赞一个。

如果有严格的安全考虑，还是建议，直接用访问URL访问 workers 时（如：xxx.xxx.workers.dev/)直接浏览器的404，，当使用指定的URL访问时，如：xxx.xxxx.workers.dev/aaaaaaaa（aaaaaaaa为可配置的变量信息），来输出正确的部署状态，甚至于后端的一些不敏感的配置自检信息。

当然，项目如果对安全要求不是很严格或者很敏感，当前这样完全可以了。

**Comment by dreamhunter2333** [comment]
> 厉害！赞一个。
> 
> 如果有严格的安全考虑，还是建议，直接用访问URL访问 workers 时（如：xxx.xxx.workers.dev/)直接浏览器的404，，当使用指定的URL访问时，如：xxx.xxxx.workers.dev/aaaaaaaa（aaaaaaaa为可配置的变量信息），来输出正确的部署状态，甚至于后端的一些不敏感的配置自检信息。
> 
> 当然，项目如果对安全要求不是很严格或者很敏感，当前这样完全可以了。

目前 `/` 和 `/health_check` 会返回 OK

`/api/*` 会校验用户的 jwt
`/admin/*` 会校验 admin 的 密码

**Comment by Raejesh** [comment]
大哥，我按部署文档操作，部署后端之后，卡在"打开 worker 的 url，如果显示 OK 说明部署成功"这一步了，我打开url之后显示的是not found, 重试了好几次都是这样，可能是哪里操作错了呢？

**Comment by dreamhunter2333** [comment]
> 大哥，我按部署文档操作，部署后端之后，卡在"打开 worker 的 url，如果显示 OK 说明部署成功"这一步了，我打开url之后显示的是not found, 重试了好几次都是这样，可能是哪里操作错了呢？

main 分支么, 其实只要返回了就是成功了

```js
app.get('/', async c => c.text("OK"))
app.get('/health_check', async c => c.text("OK"))
app.all('/*', async c => c.text("Not Found", 404))
```

**Comment by Raejesh** [comment]
> > 大哥，我按部署文档操作，部署后端之后，卡在"打开 worker 的 url，如果显示 OK 说明部署成功"这一步了，我打开url之后显示的是not found, 重试了好几次都是这样，可能是哪里操作错了呢？
> 
> main 分支么, 其实只要返回了就是成功了
> 
> ```js
> app.get('/', async c => c.text("OK"))
> app.get('/health_check', async c => c.text("OK"))
> app.all('/*', async c => c.text("Not Found", 404))
> ```

我是直接下载的release里的`worker.js`, 我看现在新建的worker里的js文件就是叫`worker.js`, `worker.js`和`index.js`两个名字都尝试过， 上传之后直接访问域名和访问`域名/health_check`都试过了，都是直接返回404提示Not Found。
![IMG_0923](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/167405725/fdfb0a49-3f86-48b6-b55d-0ef0e5a4d14b)

**Comment by dreamhunter2333** [comment]
> 
> 
> 
> 
> > > 大哥，我按部署文档操作，部署后端之后，卡在"打开 worker 的 url，如果显示 OK 说明部署成功"这一步了，我打开url之后显示的是not found, 重试了好几次都是这样，可能是哪里操作错了呢？
> 
> > 
> 
> > main 分支么, 其实只要返回了就是成功了
> 
> > 
> 
> > ```js
> 
> > app.get('/', async c => c.text("OK"))
> 
> > app.get('/health_check', async c => c.text("OK"))
> 
> > app.all('/*', async c => c.text("Not Found", 404))
> 
> > ```
> 
> 
> 
> 我是直接下载的release里的`worker.js`, 我看现在新建的worker里的js文件就是叫`worker.js`, `worker.js`和`index.js`两个名字都尝试过， 上传之后直接访问域名和访问`域名/health_check`都试过了，都是直接返回404提示Not Found。
> 
> ![IMG_0923](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/167405725/fdfb0a49-3f86-48b6-b55d-0ef0e5a4d14b)
> 
> 

这两个名字都可以的，下载个最新的 release 尝试下

**Comment by pdhapy** [comment]
> 
> 我是直接下载的release里的`worker.js`, 我看现在新建的worker里的js文件就是叫`worker.js`, `worker.js`和`index.js`两个名字都尝试过， 上传之后直接访问域名和访问`域名/health_check`都试过了，都是直接返回404提示Not Found。

当时我手动部署时，也是卡在这里，而且又因为部署后默认输出了 `Not Found` 我一度以为是哪里出了问题，排查了很久，一度要去搜索代码查看。但其实应该是部署成功了的。但是当时也不确定，因为文档里也没提及有 `/health_check` 来检查部署状态。 所以部署后，默认输出 `Not Found` 其实没啥问题，甚至于 `/` 访问直接 HTTP 404 也挺好的，这里真正的坑在于当时部署文档里完全没提及部署成功后的结果确认方式，只是说打开URL就算成功了。 所以文档提供说明由 `/health_check`  确认部署结果就相当关键了（原先我也一直不知道有这个）。作者大佬@dreamhunter2333更新一下就好。

另外：手动部署文档里这段说明是有谬误的，不知道是因为CF版本更新的问题，正准备提个Bug的，放在这里一起说了。

按当前的CF 版本，手动在CF操作 部署后，默认的就是 `Workers.js`了，这里其实应该是：

1、没有修改 `index.js` 这个操作，因为CF新建Workers后默认部署成功后的示例就不是 `index.js` ，文档里说了这个让新手很困惑；
 
2、常规操作这里应该是：直接把下载的 `Workers.js`  里面的内容复制粘贴进来，保存部署就可以了；

3、但因为下载的代码是压缩过的，直接粘贴**也可能**会有问题，**只是可能**，因为代码编辑带有简单的格式优化，粘贴进去的代码是会显示格式错误的，并且语法高亮也显示不正常，因为有几处SQL查询语句的语法空格可能被编辑器压缩删除了，可能显示不正常，**但实际上应该也是能部署成功的。**  这是CF编辑器的坑。

4、至于文档里提及的上传，其实也可以，但是CF的这个代码编辑器对 `上传` 藏得比较深，需要先点击左侧菜单的 `Explorer` ，在文件列表的窗口里`点击鼠标右键`，在右键菜单里仔细些才能看到 ` Upload`, 新手可能没办法一下子找到在哪里，如下图：。

![Screenshot 2024-04-26 213912-2](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/94694475/0be1e9b2-a95b-4f91-a401-10fe296399f5)

因为是如果是要直接上传的话，可以先删除CF默认创建的workers.js后，再直接上传下载好的就可以了。

**Comment by dreamhunter2333** [comment]
> 4、至于文档里提及的上传，其实也可以，但是CF的这个代码编辑器对 `上传` 藏得比较深，需要先点击左侧菜单的 `Explorer` ，在文件列表的窗口里`点击鼠标右键`，在右键菜单里仔细些才能看到 ` Upload`, 新手可能没办法一下子找到在哪里，如下图：。

赞，非常详细，我后续优化下文档

**Comment by Raejesh** [comment]
可能是ipad上传`worker.js`出了啥问题，回家用电脑重新下载上传部署一次就成功了，感谢大佬们耐心解答！

**Comment by Raejesh** [comment]
接受邮件测试没问题了，但是发送报500，看提示和 #145 很像， [这是](https://mail-infinite.pages.dev)我部署的地址， 大哥能帮忙看下吗

**Comment by Raejesh** [comment]
> 接受邮件测试没问题了，但是发送报500，看提示和 #145 很像， [这是](https://mail-infinite.pages.dev)我部署的地址， 大哥能帮忙看下吗

🤔应该不是发送邮件配置的问题， 我两个域名测试用其他发送邮件的cf项目是可以正常发送的

**Comment by dreamhunter2333** [comment]
> > 接受邮件测试没问题了，但是发送报500，看提示和 #145 很像， [这是](https://mail-infinite.pages.dev)我部署的地址， 大哥能帮忙看下吗
> 
> 🤔应该不是发送邮件配置的问题， 我两个域名测试用其他发送邮件的cf项目是可以正常发送的

可以查看下控制台日志么，我试了下你部署的地址，发送报错 `Failed to send mail`
<img width="1111" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/01998e95-35fd-47c5-9f53-591ed1d54035">


<img width="878" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/c0c62fa3-aaa5-4a87-83cb-e30fa11e1590">

**Comment by Raejesh** [comment]
> > > 接受邮件测试没问题了，但是发送报500，看提示和 #145 很像， [这是](https://mail-infinite.pages.dev)我部署的地址， 大哥能帮忙看下吗
> > 
> > 
> > 🤔应该不是发送邮件配置的问题， 我两个域名测试用其他发送邮件的cf项目是可以正常发送的
> 
> 可以查看下控制台日志么，我试了下你部署的地址，发送报错 `Failed to send mail` <img alt="image" width="1111" src="https://private-user-images.githubusercontent.com/32295532/326148519-01998e95-35fd-47c5-9f53-591ed1d54035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTE1MjQsIm5iZiI6MTcxNDIxMTIyNCwicGF0aCI6Ii8zMjI5NTUzMi8zMjYxNDg1MTktMDE5OThlOTUtMzVmZC00N2M1LTlmNTMtNTkxZWQxZDU0MDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA5NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNmRlZGFmODBhNDA2YmM3NTNmNDUwMmMzY2MwNjg3MzQwZWEzMzFmODU1ODkwMTZlMzVmYzQyNDcwMzM5YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oruxwK91QVg6yAH9cv_GilNJ0_ryjZs-Txh7avGMwJA">
> 
> <img alt="image" width="878" src="https://private-user-images.githubusercontent.com/32295532/326148374-c0c62fa3-aaa5-4a87-83cb-e30fa11e1590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTE1MjQsIm5iZiI6MTcxNDIxMTIyNCwicGF0aCI6Ii8zMjI5NTUzMi8zMjYxNDgzNzQtYzBjNjJmYTMtYWFhNS00YTg3LTgzY2ItZTMwZmExMWUxNTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA5NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNTE1ZDMyMzY4ZGFmYjE3MDVhYTAxY2M3ZWEyZWJmYzg0MmEyOTNiZTExZDk1Zjg4ZjIyZTI0NDQxZmNkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WfRYxiFjuw3_ScF_4rhZdhyQEjZEGPA8Xi2G07sNTUY">

感谢大哥的提醒！
打开cf日志瞅了眼，发现确实有个POST报了个`"400 Bad Request: {\"errors\":[\"bad request - DKIM public key and private key mismatch: fail to get public key from DNS record\"]}\n"`
我寻思着另外一个worker可以发，那说明DNS解析配置没问题，就去对了下workers的变量，发现是`DKIM_SELECTOR`的值多了双引号🤣, 我是昨天用ipad通过用户界面部署的，参考`wrangler.toml`添加变量时没注意。
感谢大哥耐心协助排查问题！给大哥点赞🫡
