### ISSUE TITLE
这个项目有可能支持多域名吗？

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#16]
如题，谢谢大佬

**Comment by dreamhunter2333** [comment]
多域名指同时服务多个域名邮箱吗，理论上可以的，需要修改下逻辑

**Comment by xiewei3536** [comment]
> 多域名指同时服务多个域名邮箱吗，理论上可以的，需要修改下逻辑

是的，希望可以实现
1.指定域名
2.未指定就随机调用域名

辛苦你了🙏🏻

**Comment by dreamhunter2333** [comment]
已支持

**Comment by xiewei3536** [comment]
> 已支持

大佬太牛逼！！
已经顺利部署完成！！

**Comment by dreamhunter2333** [comment]
> > 已支持
> 
> 
> 
> 大佬太牛逼！！
> 
> 已经顺利部署完成！！

记得两个域名都要设置电子邮件 catch all

**Comment by xiewei3536** [comment]
> > > 已支持
> > 
> > 
> > 大佬太牛逼！！
> > 已经顺利部署完成！！
> 
> 记得两个域名都要设置电子邮件 catch all

有的有的！非常感谢❤️

**Comment by kurapika7733** [comment]
# 补充：支持多域名cloudflare配置

##  1. 在cf中切换到新域名，例如`xxx.ggff.net`, 进入到电子邮件 -> 电子邮件路由，开始使用

<img width="2880" height="1398" alt="Image" src="https://github.com/user-attachments/assets/b8ec6c93-789c-42e0-9afb-8507a03d34a0" />

## 2. 创建邮件路由（后面会指到worker）

<img width="2874" height="1312" alt="Image" src="https://github.com/user-attachments/assets/befbef1c-5109-49dc-9d88-a3dbb4fe85ed" />

### 2.1 验证路由
<img width="2870" height="912" alt="Image" src="https://github.com/user-attachments/assets/28553c63-76ab-4e1d-9358-6630c3be6e4c" />

### 2.2创建记录
<img width="2840" height="1076" alt="Image" src="https://github.com/user-attachments/assets/664e95d8-e576-4476-97d9-ea802a9f48c2" />

### 2.3 开启并且进行编辑
<img width="2862" height="1052" alt="Image" src="https://github.com/user-attachments/assets/45ec18be-83b2-41af-9c71-244de44714f7" />

### 2.4 编辑邮件路由
<img width="2854" height="1004" alt="Image" src="https://github.com/user-attachments/assets/438cdc77-5d64-42a1-abbc-e6d134472c6f" />

### 2.5 编辑成功的结果
<img width="2776" height="970" alt="Image" src="https://github.com/user-attachments/assets/b9fec3cf-8c22-4edb-8611-912be5e5e7e9" />

## 3. 进入`worker`修改环境变量DOMAINS, 把域添加到该环境变量中，然后重新部署
<img width="2850" height="1512" alt="Image" src="https://github.com/user-attachments/assets/4f2b864f-72a0-4afa-8098-1a22252d038f" />

## 4. 进入web页面，刷新就可以配置新的路由名称邮件地址了，该域名邮件可以正常接收邮件
<img width="2866" height="690" alt="Image" src="https://github.com/user-attachments/assets/1372a620-5cad-422c-a97a-273f0e513763" />

## 其他
因为我使用的是免费的Resend服务，只有1个免费域名配置的名额，还没测试多域名发邮件功能（应该和单个配置相同）
