### ISSUE TITLE
希望细化配置的使用和说明

### ISSUE THREAD

**Issue by Zding89** [dreamhunter2333/cloudflare_temp_email#160]
已经部署成功，目前踩的坑有：
1.用命令行部署前端，生成pages后无法使用，后面改为手动上传文件成功（不知道是不是我个例）
2.jwt是什么作用？
3.这个一开始以为是对应不同的域名产生不同的的密码
# 如果你想要你的网站私有，取消下面的注释，并修改密码
# PASSWORDS = ["123", "456"]
于是我用PASSWORDS = ["", "456"，""]这样使用，但发现会导致所有域名都无法使用，提示需要输入密码，但也没授权验证框。
4.默认1次发信怎么改为默认0次。建议改为弄个申请按钮，按钮可让输入邮件和申请内容，发送则通过tg或者别的push提醒到拥有者，用拥有者生成指定授权次数的key，发送的时候根据Key来判断有没发送次数。（又或者弄成注册用户有发送权和申请，不知道哪个容易实现）

ps:作者的热心程度是真高，点赞

**Comment by dreamhunter2333** [comment]
1. PASSWORDS 这个看起来是个 bug 我修复下
2. 默认1次发信这个可以添加个配置项
3. 怎么给用户增加发信权限/额度 - 这个我还在看怎么处理比较合适

**Comment by Zding89** [comment]
命令行部署那个已经解决了，我估计是当初部署的时候没输入production

**Comment by dreamhunter2333** [comment]
> 1. 命令行部署是提示输入分支，输入 production 了么
> 2. jwt 用于给用户登录以及鉴权
> 3. PASSWORDS 这个看起来是个 bug 我修复下
> 4. 默认1次发信这个可以添加个配置项
> 5. 怎么给用户增加发信权限/额度 - 这个我还在看怎么处理比较合适

https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html#%E4%BF%AE%E6%94%B9-wrangler-toml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

2. 已更新文档
3. main 分支已修复
4. 已增加配置项 `DEFAULT_SEND_BALANCE`
5. 暂时先加了提示 `ADMIN_CONTACT`
