### ISSUE TITLE
[Feature] 自己设置密码，支持邮箱 + 密码登录

### ISSUE THREAD

**Issue by mantoufan** [dreamhunter2333/cloudflare_temp_email#166]
## 登录功能

1. 用户可以自己设置密码
2. 登录界面，支持 账号 + 密码 登录

一长串的密码，虽然可以免除记忆邮箱账号，但必须保存到某个地方，才能使用，非常感谢！

**Comment by dreamhunter2333** [comment]
OK 后续可以增加下用户名密码登录，感谢反馈

**Comment by dreamhunter2333** [comment]
main 分支已增加用户功能，测试完成会会发布新的 tag, 可以先在 `https://mail.awsl.uk/user` 试用下
<img width="1261" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/b664f92c-fdba-423c-83a8-1612944ad023">

**Comment by dreamhunter2333** [comment]
v0.4.0 已增加用户功能
