### ISSUE TITLE
另外想再请问有没有可能实现一键删除临时信箱

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#17]
如题能否一键删除临时信箱，使这个邮箱地址不存在？

**Comment by dreamhunter2333** [comment]
是指禁止接收这个地址的邮件吗，是可以的

**Comment by xiewei3536** [comment]
> 是指禁止接收这个地址的邮件吗，是可以的

对的，直接在前端一键删除当前建立的临时邮箱

**Comment by dreamhunter2333** [comment]
=

> > 是指禁止接收这个地址的邮件吗，是可以的
> 
> 对的，直接在前端一键删除当前建立的临时邮箱

唯一缺点就是得维护一个 存在的地址列表/删除的地址列表。

**Comment by xiewei3536** [comment]
> =
> 
> > > 是指禁止接收这个地址的邮件吗，是可以的
> > 
> > 
> > 对的，直接在前端一键删除当前建立的临时邮箱
> 
> 唯一缺点就是得维护一个 存在的地址列表/删除的地址列表。难度不大，我有空搞一下

谢谢大佬！
这是我之前常常用的临时邮箱，希望可以实现跟他一样的功能
<img width="406" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/d41bb44a-2451-4348-abce-d29c05761555">

**Comment by dreamhunter2333** [comment]
> > =
> > > > 是指禁止接收这个地址的邮件吗，是可以的
> > > 
> > > 
> > > 对的，直接在前端一键删除当前建立的临时邮箱
> > 
> > 
> > 唯一缺点就是得维护一个 存在的地址列表/删除的地址列表。难度不大，我有空搞一下
> 
> 谢谢大佬！ 这是我之前常常用的临时邮箱，希望可以实现跟他一样的功能 <img alt="image" width="406" src="https://user-images.githubusercontent.com/29998329/266256238-d41bb44a-2451-4348-abce-d29c05761555.png">

这个我可以加一下，账户可以被别人重新使用，这个地址还会继续接收邮件

**Comment by 1715819** [comment]
这个功能很实用。有时候密码忘了，对应的邮箱也就没法用了，有些浪费。

**Comment by dreamhunter2333** [comment]
> 这个功能很实用。有时候密码忘了，对应的邮箱也就没法用了，有些浪费。

增加了 admin 页面，需在配置文件增加密码，访问 `/admin` 地址，可查看密码和删除地址

**Comment by xiewei3536** [comment]
> > 这个功能很实用。有时候密码忘了，对应的邮箱也就没法用了，有些浪费。
> 
> 增加了 admin 页面，需在配置文件增加密码，访问 `/admin` 地址，可查看密码和删除地址

完美部署！！真的太感谢大佬了，辛苦你了！！

**Comment by dreamhunter2333** [comment]
> @dreamhunter2333 不好意思，但好像有一点问题，我删除掉了邮箱，但地址好像还是存在，我透过密码依旧可以登入😨

是的，删除目前只是释放了地址，可以被其他人获取到，之前的密码依然可用

**Comment by xiewei3536** [comment]
> > @dreamhunter2333 不好意思，但好像有一点问题，我删除掉了邮箱，但地址好像还是存在，我透过密码依旧可以登入😨
> 
> 是的，删除目前只是释放了地址，可以被其他人获取到，之前的密码依然可用，目前密码的是纯客户端的 JWT，无法通过服务端使其失效

大佬，那有可能实现真正删除邮箱地址吗？

**Comment by dreamhunter2333** [comment]
> > > @dreamhunter2333 不好意思，但好像有一点问题，我删除掉了邮箱，但地址好像还是存在，我透过密码依旧可以登入😨
> > 
> > 
> > 是的，删除目前只是释放了地址，可以被其他人获取到，之前的密码依然可用，目前密码的是纯客户端的 JWT，无法通过服务端使其失效
> 
> 大佬，那有可能实现真正删除邮箱地址吗？

目前没办法，我看看后续有什么其他方式，删除账号+邮件是可以的，让原密码失效需要重新设计下

**Comment by rendercs** [comment]
<img width="934" alt="屏幕截图 2023-11-30 134640" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/115221968/428bc41f-6975-4259-bc80-aa684da8c10f">
可以在这删除地址，之后这个地址又可以重新使用了，但是收件内容还在，自用的话可以这样做

**Comment by dreamhunter2333** [comment]
已添加删除功能

**Comment by xiewei3536** [comment]
> 已添加删除功能

大佬，我刚刚有测试一下，发现我删除后，再用同样的密码一样可以再登录

**Comment by dreamhunter2333** [comment]
> > 已添加删除功能
> 
> 大佬，我刚刚有测试一下，发现我删除后，再用同样的密码一样可以再登录

更改了下校验逻辑，对于之前注册的账号会检查账号是否存在，不存在则返回错误，
目前的问题是旧的密码还是能登录到新注册的同名账号
对于新用户来说没有问题

**Comment by xiewei3536** [comment]
> > > 已添加删除功能
> > 
> > 
> > 大佬，我刚刚有测试一下，发现我删除后，再用同样的密码一样可以再登录
> 
> 更改了下校验逻辑，对于之前注册的账号会检查账号是否存在，不存在则返回错误， 目前的问题是旧的密码还是能登录到新注册的同名账号 对于新用户来说没有问题

大佬，操作完后变成所有旧邮箱都没办法登入了！
