### ISSUE TITLE
[Feature] 规避敏感词作为邮箱

### ISSUE THREAD

**Issue by oneisall8955** [dreamhunter2333/cloudflare_temp_email#170]
> 这是个不紧急的 feature

## 请描述您的 Feature
十分感谢这个优秀的项目，虽然项目的理念是临时邮箱，但别人使用的时候的是我的域名。我希望别人注册邮箱，避免使用特殊的词语，如：official，admin，me，support，root等词语作为邮箱前缀。通过敏感词管理实现简单的风控。

## 描述您想要的解决方案
- 提供敏感词表，通过 sql 初始化默认敏感词词库
- admin 后台添加增删改查，及批量导入敏感词（以换行为分割）
- admin 后台添加创建创建账号功能（也就是可以创建包括敏感词的邮箱，无限制）
- 获取新邮箱的接口，添加上敏感词过滤限制，登录还是可以使用密码登录（后台可以管理这种敏感邮箱）。

## 描述您考虑过的替代方案
加前缀例如 tmpemail 虽然可以避免敏感词，但是有个前缀有所限制，大部分非敏感词也会加上前缀，导致整个邮箱过长

**Comment by dreamhunter2333** [comment]
感谢反馈，这个解决方案比较好，之前添加前缀也是为了防止滥用邮箱名字

**Comment by Raejesh** [comment]
大哥，我看到README里功能写有`admin 后台创建无前缀邮箱`了， 请问菜单入口在哪里呢

**Comment by dreamhunter2333** [comment]
> 大哥，我看到README里功能写有`admin 后台创建无前缀邮箱`了， 请问菜单入口在哪里呢

目前还在 main 分支，没有打 tag release，之后做完这个敏感词一起打一个 tag

**Comment by dreamhunter2333** [comment]
最新版已增加
https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.3.1

**Comment by Raejesh** [comment]
> 最新版已增加 https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.3.1

0.3.1版本部署后没有获取新邮箱的按钮了，不管是下载最新release的frontend.zip或者从部署文档下载的都是下图效果
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/167405725/06c4e794-3ad8-4ced-af39-0f4e2eeefe90)
尝试清除缓存也没有效果，求助.

**Comment by dreamhunter2333** [comment]
> > 最新版已增加 https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.3.1
> 
> 
> 
> 0.3.1版本部署后没有获取新邮箱的按钮了，不管是下载最新release的frontend.zip或者从部署文档下载的都是下图效果
> 
> ![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/167405725/06c4e794-3ad8-4ced-af39-0f4e2eeefe90)
> 
> 尝试清除缓存也没有效果，求助.

worker 新增了允许用户创建邮箱配置，默认不允许
