### ISSUE TITLE
V0.3.0 前缀疑问

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#174]
请问如果原先就没有使用前缀的话，升级v0.3.0需要执行这步骤吗？

![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/defdfeac-2401-4cee-bdff-0aa85489cba7)

**Comment by dreamhunter2333** [comment]
> 请问如果原先就没有使用前缀的话，升级v0.3.0需要执行这步骤吗？
> 
> ![image](https://private-user-images.githubusercontent.com/29998329/326241292-defdfeac-2401-4cee-bdff-0aa85489cba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTMzMjcsIm5iZiI6MTcxNDI5MzAyNywicGF0aCI6Ii8yOTk5ODMyOS8zMjYyNDEyOTItZGVmZGZlYWMtMjQwMS00Y2VlLWJkZmYtMGFhODU0ODljYmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA4MzAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTE1N2RkYzM1Y2EwZThjMTJkY2Y4NzIxNjIxYTVjYTQ5MzI1YjZlN2U2MjJlNThlNTFkOTNmZTMwNGU5NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jxsd-a9qAbkuda-u53XFSZ-8rEQyYK3ms9MMRES1AVA)

原来没使用前缀就无须处理，我加一下备注，这次修改主要是为了 admin 可以手动创建指定名称的邮箱
