### ISSUE TITLE
[BUG] ENABLE_USER_DELETE_EMAIL 似乎不工作

### ISSUE THREAD

**Issue by lwd-temp** [dreamhunter2333/cloudflare_temp_email#176]
## 复现步骤

ENABLE_USER_DELETE_EMAIL 设为 false 时，重新部署，用户仍可删除邮件。

## 预期行为

ENABLE_USER_DELETE_EMAIL 设为 false 时，用户不可删除邮件。

## 部署方式

- [ ] cli 部署
- [x] 用户界面部署

## 浏览器环境

Edg/124.0.0.0

## 可能的问题位置

https://github.com/dreamhunter2333/cloudflare_temp_email/blob/23d1709ca1aa36e946d69394996b3e89aa959565/worker/src/router.js#L175C16-L175C40

```javascript
// 一个猜测，不一定正确
// 当：
c.env.ENABLE_USER_DELETE_EMAIL = "false"

(!c.env.ENABLE_USER_DELETE_EMAIL)
// 即为
(!"false") = false

// TODO: 如果这个猜测成立，需要修改不止一处这样的问题。另外，需要注意，前端的行为不一定一致。
```

**Comment by dreamhunter2333** [comment]
看起来应该是用户界面输入的所有变量都变成字符串了，我修改下这些bool变量的判断逻辑

**Comment by dreamhunter2333** [comment]
临时的解决方案是不配置这个参数，未配置会认为是 false

**Comment by dreamhunter2333** [comment]
已修复
