### ISSUE TITLE
[Feature] 一个账户可以添加多个邮箱，以及邮箱push功能

### ISSUE THREAD

**Issue by verlands** [dreamhunter2333/cloudflare_temp_email#181]
## 功能

1. 一个账户可以添加多个邮箱，不可能只使用同一个临时邮箱  
2. 添加push邮箱功能，能够将自己的一个邮箱push给另一个账户

这样使用范围就更广了，非常感谢

**Comment by pdhapy** [comment]
这是别名功能了，正好也需要，感觉这几个大需求做完，这项目的后端 Worker 已经是个小的 Hotmail Server 了，就差支持IMAP了。 

:smiley:

**Comment by verlands** [comment]
> 2. 类似直接迁移数据那种么，历史邮件全部指向另一个账户，当前账户迁移完成后可以删除 / 还是指转发到其他地址的邮箱

不是迁移数据，是把某个邮箱转移给另一个账户，比如A账户有很多邮箱，其中一个是abc@awsl.uk，现在我想把这个abc@awsl.uk转移给B账户，这个邮箱的所有权就是B的了，A就收不到这个邮箱的邮件了。

不过说到迁移数据，倒是可以出一个迁移/导出邮件的功能。

**Comment by dreamhunter2333** [comment]
> 为了转移方便，可以用转移码的方式，想转移的邮箱就生成一个唯一的转移码，任何有这个转移码的人就可以输入转移码拿到这个邮箱。

OK 了解了，算是用户体系下的转移账户所有权功能
- 邮件的话现在有单个邮件的下载功能

**Comment by dreamhunter2333** [comment]
main 分支已增加用户功能，测试完成会会发布新的 tag, 可以先在 `https://mail.awsl.uk/user` 试用下
<img width="1261" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/b664f92c-fdba-423c-83a8-1612944ad023">

**Comment by dreamhunter2333** [comment]
v0.4.0 已增加
