### ISSUE TITLE
[Feature] 添加快捷回复邮件的功能

### ISSUE THREAD

**Issue by sunnywangzi** [dreamhunter2333/cloudflare_temp_email#186]
Rt
在收到邮件后可以快速回复

**Comment by dreamhunter2333** [comment]
OK 可以在邮件上加个回复按钮

**Comment by dreamhunter2333** [comment]
已增加

**Comment by sunnywangzi** [comment]
可以把正文也自动填充一下，参考各大邮箱的回复
因为有些软件通过邮件自动回复的功能需要上下文

**Comment by dreamhunter2333** [comment]
> 可以把正文也自动填充一下，参考各大邮箱的回复 因为有些软件通过邮件回复的功能需要上下文

OK 我看下怎么做一下引用原文

**Comment by dreamhunter2333** [comment]
已更新，只能做到引用，做不到 outlook 那种邮件 thread

<img width="783" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/e87a976f-f60e-4d80-a1ee-49ecc06ba735">
