### ISSUE TITLE
[Feature] api发件可以直接在body传入jwt

### ISSUE THREAD

**Issue by sunnywangzi** [dreamhunter2333/cloudflare_temp_email#194]
rt
有些项目不支持配置header
还有使用api发件就不用验证网站使用密码了吧

再提个bug 删除邮箱会报500错误，但实际能删除成功

**Comment by dreamhunter2333** [comment]
好的我看下删

**Comment by dreamhunter2333** [comment]
> rt 有些项目不支持配置header 还有使用api发件就不用验证网站使用密码了吧
> 
> 再提个bug 删除邮箱会报500错误，但实际能删除成功

测试删除邮箱账户没有 500 错误，能看下你的错误日志么

**Comment by sunnywangzi** [comment]
```

"logs": [
    {
      "message": [
        "Error: D1_ERROR: no such column: address_id at offset 33"
      ],
      "level": "error",
      "timestamp": 1714804439738
    }
  ],

```

**Comment by dreamhunter2333** [comment]
> ```
> 
> 
> 
> "logs": [
> 
>     {
> 
>       "message": [
> 
>         "Error: D1_ERROR: no such column: address_id at offset 33"
> 
>       ],
> 
>       "level": "error",
> 
>       "timestamp": 1714804439738
> 
>     }
> 
>   ],
> 
> 
> 
> ```

是用户删除么，还是通过 admin 删除的

**Comment by dreamhunter2333** [comment]
已增加 `/external/api/send_mail`，通过 body 验证

https://temp-mail-docs.awsl.uk/zh/guide/feature/send-mail-api.html

**Comment by sunnywangzi** [comment]
好的，感谢

ps：文档的token后面没加逗号

**Comment by dreamhunter2333** [comment]
> 好的，感谢
> 
> 
> 
> _文档的token后面没加逗号_

感谢提醒
