### ISSUE TITLE
api部署完打开网站是hello world

### ISSUE THREAD

**Issue by LONELYLI666** [dreamhunter2333/cloudflare_temp_email#2]
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/78999498/f46d6eaf-5d36-4a1e-bb1a-0f5ea444b659)

**Comment by dreamhunter2333** [comment]
`VITE_API_BASE=https://temp-email-api.dreamhunter2333.xyz`
 检查这个配置是否正确，末尾不要用 /

**Comment by LONELYLI666** [comment]
> `VITE_API_BASE=https://temp-email-api.dreamhunter2333.xyz` 检查这个配置是否正确，末尾不要用 /

![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/78999498/9a66d0d0-3b00-4dbf-9981-67333d867c30)
又有了新的问题

**Comment by dreamhunter2333** [comment]
> > `VITE_API_BASE=https://temp-email-api.dreamhunter2333.xyz` 检查这个配置是否正确，末尾不要用 /
> 
> ![image](https://user-images.githubusercontent.com/78999498/263213457-9a66d0d0-3b00-4dbf-9981-67333d867c30.png) 又有了新的问题

可以 f12 看看具体错误吗，数据库初始化了吗

**Comment by LONELYLI666** [comment]
> > > `VITE_API_BASE=https://temp-email-api.dreamhunter2333.xyz` 检查这个配置是否正确，末尾不要用 /
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/78999498/263213457-9a66d0d0-3b00-4dbf-9981-67333d867c30.png) 又有了新的问题
> 
> 可以 f12 看看具体错误吗，数据库初始化了吗

一针见血了确实是数据库没有初始化
我当时初始化时忘记先git clone了

**Comment by dreamhunter2333** [comment]
> > > > `VITE_API_BASE=https://temp-email-api.dreamhunter2333.xyz` 检查这个配置是否正确，末尾不要用 /
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/78999498/263213457-9a66d0d0-3b00-4dbf-9981-67333d867c30.png) 又有了新的问题
> > 
> > 
> > 可以 f12 看看具体错误吗，数据库初始化了吗
> 
> 一针见血了确实是数据库没有初始化 我当时初始化时忘记先git clone了

初始化之后成功了吗

**Comment by LONELYLI666** [comment]
> > > > > `VITE_API_BASE=https://temp-email-api.dreamhunter2333.xyz` 检查这个配置是否正确，末尾不要用 /
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/78999498/263213457-9a66d0d0-3b00-4dbf-9981-67333d867c30.png) 又有了新的问题
> > > 
> > > 
> > > 可以 f12 看看具体错误吗，数据库初始化了吗
> > 
> > 
> > 一针见血了确实是数据库没有初始化 我当时初始化时忘记先git clone了
> 
> 初始化之后成功了吗

成功了感谢🙏
