### ISSUE TITLE
可否实现新增加密访问

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#20]
大佬你好
想请问可否新增加密访问网站
希望可以实现，可加密成为私人站点，未加密成为公开站点。
谢谢！

**Comment by dreamhunter2333** [comment]
我也正在考虑这个功能，等我增加下

**Comment by dreamhunter2333** [comment]
<img width="1246" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/e9e5a711-a2fa-4884-8d6f-61519bf8209b">

**Comment by xiewei3536** [comment]
> <img alt="image" width="1246" src="https://user-images.githubusercontent.com/32295532/266768065-e9e5a711-a2fa-4884-8d6f-61519bf8209b.png">

大佬太强啦～
期待！！

**Comment by dreamhunter2333** [comment]
已合并，有空可以测试下

**Comment by dreamhunter2333** [comment]
<img width="916" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/3c71e768-6322-4e1d-8e34-517b63960792">

**Comment by xiewei3536** [comment]
> 已合并，有空可以测试下

已经完美部署成功！
再次感谢大佬！太棒了

**Comment by xiewei3536** [comment]
我发现一个问题😭


> <img alt="image" width="916" src="https://user-images.githubusercontent.com/32295532/266768483-3c71e768-6322-4e1d-8e34-517b63960792.png">

我输入错误的密码，一样也可以访问
是哪里有问题吗？

**Comment by xiewei3536** [comment]
@dreamhunter2333 
一开始访问网站，跳出第一个授权框，无论输入密码正确与否，都会直接通过。（这边有问题）
但在创建邮件时，还是会被挡下来，要求输入正却授权码。

**Comment by dreamhunter2333** [comment]
> 

好的我加一下密码检查

**Comment by dreamhunter2333** [comment]
> @dreamhunter2333 一开始访问网站，跳出第一个授权框，无论输入密码正确与否，都会直接通过。（这边有问题） 但在创建邮件时，还是会被挡下来，要求输入正却授权码。

已更新，麻烦测试下

**Comment by xiewei3536** [comment]
> > @dreamhunter2333 一开始访问网站，跳出第一个授权框，无论输入密码正确与否，都会直接通过。（这边有问题） 但在创建邮件时，还是会被挡下来，要求输入正却授权码。
> 
> 已更新，麻烦测试下

谢谢大佬修正
刚才测试了一下，发现确实会判断密码了，但似乎可以透过「关闭弹窗」绕过访问网站检查，想请问可不可以把关闭取消，变成强制需要密码。
<img width="1084" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/fe3e253d-40fe-43fa-b587-ff33443049fa">

**Comment by dreamhunter2333** [comment]
> > > @dreamhunter2333 一开始访问网站，跳出第一个授权框，无论输入密码正确与否，都会直接通过。（这边有问题） 但在创建邮件时，还是会被挡下来，要求输入正却授权码。
> 
> > 
> 
> > 已更新，麻烦测试下
> 
> 
> 
> 谢谢大佬修正
> 
> 刚才测试了一下，发现确实会判断密码了，但似乎可以透过「关闭弹窗」绕过访问网站的第一层授权检查，想请问可不可以把关闭取消，变成强制需要密码。
> 
> <img width="1084" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/fe3e253d-40fe-43fa-b587-ff33443049fa">
> 
> 

我看下这个组件能不能取消关闭，关闭了其实也无法使用，就是不易用

**Comment by dreamhunter2333** [comment]
> > > @dreamhunter2333 一开始访问网站，跳出第一个授权框，无论输入密码正确与否，都会直接通过。（这边有问题） 但在创建邮件时，还是会被挡下来，要求输入正却授权码。
> > 
> > 
> > 已更新，麻烦测试下
> 
> 谢谢大佬修正 刚才测试了一下，发现确实会判断密码了，但似乎可以透过「关闭弹窗」绕过访问网站的第一层授权检查，想请问可不可以把关闭取消，变成强制需要密码。 <img alt="image" width="1084" src="https://user-images.githubusercontent.com/29998329/266780547-fe3e253d-40fe-43fa-b587-ff33443049fa.png">

已更新

**Comment by xiewei3536** [comment]
> > > > @dreamhunter2333 一开始访问网站，跳出第一个授权框，无论输入密码正确与否，都会直接通过。（这边有问题） 但在创建邮件时，还是会被挡下来，要求输入正却授权码。
> > > 
> > > 
> > > 已更新，麻烦测试下
> > 
> > 
> > 谢谢大佬修正 刚才测试了一下，发现确实会判断密码了，但似乎可以透过「关闭弹窗」绕过访问网站的第一层授权检查，想请问可不可以把关闭取消，变成强制需要密码。 <img alt="image" width="1084" src="https://user-images.githubusercontent.com/29998329/266780547-fe3e253d-40fe-43fa-b587-ff33443049fa.png">
> 
> 已更新

非常感谢大佬！
部署完成！辛苦你了💯
