### ISSUE TITLE
可以实现api或者imap提取邮件吗？

### ISSUE THREAD

**Issue by 666-eth** [dreamhunter2333/cloudflare_temp_email#203]
## 请描述您的 Feature
可以实现api或者imap提取邮件吗？
## 描述您想要的解决方案
有些时候批量收取邮件的时候有办法api提取验证码或者是imap提取吗？能实现吗老哥

**Comment by dreamhunter2333** [comment]
api 提取是可以的，ui 界面就是通过api 查询的(我之后加一下文档)，imap 我看看如何实现

**Comment by dreamhunter2333** [comment]
api 查询邮件的文档

https://temp-mail-docs.awsl.uk/zh/guide/feature/mail-api.html

**Comment by xiewei3536** [comment]
> api 查询邮件的文档
> 
> https://temp-mail-docs.awsl.uk/zh/guide/feature/mail-api.html

大佬，有可能弄出telegram bot吗？

**Comment by pdhapy** [comment]
哈，正好两天刚看到个项目：mail2telegram    https://github.com/TBXark/mail2telegram

**Comment by dreamhunter2333** [comment]
> > api 查询邮件的文档
> > https://temp-mail-docs.awsl.uk/zh/guide/feature/mail-api.html
> 
> 大佬，有可能弄出telegram bot吗？

是说邮件推送到 telegram bot 么

**Comment by xiewei3536** [comment]
> > > api 查询邮件的文档
> > > https://temp-mail-docs.awsl.uk/zh/guide/feature/mail-api.html
> > 
> > 
> > 大佬，有可能弄出telegram bot吗？
> 
> 是说邮件推送到 telegram bot 么，集成应该不复杂

对的，希望可以在bot中建立邮件、收到邮件

**Comment by 666-eth** [comment]
老大你也太棒了把！！！

**Comment by 666-eth** [comment]
老哥 8787端口怎么启动啊 api 的

**Comment by dreamhunter2333** [comment]
> 老哥 8787端口怎么启动啊 api 的

配置成后端代理地址即可，环境变量配置

**Comment by wsgehaishan520** [comment]
> > 老哥 8787端口怎么启动啊 api 的
> 
> https://temp-mail-docs.awsl.uk/zh/guide/feature/config-smtp-proxy.html `proxy_url=https://temp-email-api.xxx.xxx` 配置成后端worker地址即可，环境变量配置

原来是这样，我还以为在docker里启动8787呢，摸排好久哈

**Comment by wsgehaishan520** [comment]
> > 老哥 8787端口怎么启动啊 api 的
> 
> https://temp-mail-docs.awsl.uk/zh/guide/feature/config-smtp-proxy.html `proxy_url=https://temp-email-api.xxx.xxx` 配置成后端worker地址即可，环境变量配置

还有一个api收信里面的send_body怎么写呀，我看没有这个参数的模版，有的是发信里面的模板

**Comment by dreamhunter2333** [comment]
> > > 老哥 8787端口怎么启动啊 api 的
> 
> > 
> 
> > https://temp-mail-docs.awsl.uk/zh/guide/feature/config-smtp-proxy.html `proxy_url=https://temp-email-api.xxx.xxx` 配置成后端worker地址即可，环境变量配置
> 
> 
> 
> 还有一个api收信里面的send_body怎么写呀，我看没有这个参数的模版，有的是发信里面的模板 

文档有点错误，使用get 请求即可，无需 body

**Comment by wsgehaishan520** [comment]
> > > > 老哥 8787端口怎么启动啊 api 的
> > 
> > 
> > > 
> > 
> > 
> > > https://temp-mail-docs.awsl.uk/zh/guide/feature/config-smtp-proxy.html `proxy_url=https://temp-email-api.xxx.xxx` 配置成后端worker地址即可，环境变量配置
> > 
> > 
> > 还有一个api收信里面的send_body怎么写呀，我看没有这个参数的模版，有的是发信里面的模板
> 
> 文档有点错误，使用get 请求即可，无需 body

文档里确实 好多都没有更新了，建议更新一下哈，我们新手只能看文档搭建。走了挺多弯路的

**Comment by dreamhunter2333** [comment]
> > > > > 老哥 8787端口怎么启动啊 api 的
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > https://temp-mail-docs.awsl.uk/zh/guide/feature/config-smtp-proxy.html `proxy_url=https://temp-email-api.xxx.xxx` 配置成后端worker地址即可，环境变量配置
> 
> > > 
> 
> > > 
> 
> > > 还有一个api收信里面的send_body怎么写呀，我看没有这个参数的模版，有的是发信里面的模板
> 
> > 
> 
> > 文档有点错误，使用get 请求即可，无需 body
> 
> 
> 
> 文档里确实 好多都没有更新了，建议更新一下哈，我们新手只能看文档搭建。走了挺多弯路的
> 
> 

好的，之后更新下文档

**Comment by dreamhunter2333** [comment]
> > > > api 查询邮件的文档
> > > > https://temp-mail-docs.awsl.uk/zh/guide/feature/mail-api.html
> > > 
> > > 
> > > 大佬，有可能弄出telegram bot吗？
> > 
> > 
> > 是说邮件推送到 telegram bot 么，集成应该不复杂
> 
> 对的，希望可以在bot中建立邮件、收到邮件

已支持推送邮件和查看邮件，不过受限于 tg 和 后台的限制，很多邮件解析不了
