### ISSUE TITLE
[BUG]DKIM验证一直失败

### ISSUE THREAD

**Issue by CoolkHz** [dreamhunter2333/cloudflare_temp_email#207]
`"logs": [
    {
      "message": [
        "400 Bad Request: {\"errors\":[\"bad request - DKIM public key and private key mismatch: fail to get public key from DNS record\"]}\n"
      ],
      "level": "log",
      "timestamp": 1714982310775
    }
  ],`

![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/34871925/c1de2f9f-f6c9-4d2b-b3c8-7ae9a7760b7d)
txt 记录已经解析了公钥

配置文件也配置了私钥 但是一发邮件就显示错误
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/34871925/ee60086a-51e9-485d-ac9b-7a1abfed0b8e)

**Comment by dreamhunter2333** [comment]
已经移除 mail channels 相关部分，resend 无需手动配置
