### ISSUE TITLE
获取新邮箱没显示

### ISSUE THREAD

**Issue by Zding89** [dreamhunter2333/cloudflare_temp_email#208]
【获取新邮箱】按钮没显示，但后端连入显示OK，前段能通过登录密码登录，且admin后台也能正常登录。
怎么调试原因错在哪里？

**Comment by dreamhunter2333** [comment]
默认不允许创建，需要配置文件中允许
```toml
# 是否允许用户创建邮件, 不配置则不允许
ENABLE_USER_CREATE_EMAIL = true
```

https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html

**Comment by Zding89** [comment]
> 默认不允许创建，需要配置文件中允许
> 
> ```toml
> # 是否允许用户创建邮件, 不配置则不允许
> ENABLE_USER_CREATE_EMAIL = true
> ```
> 
> https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html

应该找到原因了，因为我是直接在网站上覆盖JS，然后添加变量更新，
`ENABLE_AUTO_REPLY = "true"
ENABLE_USER_CREATE_EMAIL  = "true"
ENABLE_USER_DELETE_EMAIL  = "true"`
网站把true变文本了，保存也一直闪10013错误
