### ISSUE TITLE
[BUG]会被标记为垃圾邮件

### ISSUE THREAD

**Issue by 1715819** [dreamhunter2333/cloudflare_temp_email#212]
有什么办法可以防止吗

**Comment by dreamhunter2333** [comment]
https://www.mail-tester.com/

可以用这个网站测试下邮件质量，开启 dkim 的话应该会有 8 分
<img width="860" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/2cb74493-1004-4cf4-9ed0-076a691635db">

**Comment by 1715819** [comment]
好的谢谢。
