### ISSUE TITLE
[BUG]删除账号功能不太完善

### ISSUE THREAD

**Issue by acocchat** [dreamhunter2333/cloudflare_temp_email#213]
删除账号后，账号那一栏正常。发件箱，收件箱还有发送权限控制仍然还有被删账号的一些信息。我在数据库看了一下表，确实没有删干净。

**Comment by acocchat** [comment]
另外，如果账号太多的话，可以加一个一键删除所有的账号的按钮。即连同发件箱，收件箱还有发送权限控制一起删。避免一个一个删的繁琐。
也可以每个栏目都设置一个一键删除功能。您看哪种比较友好且妥当。

**Comment by dreamhunter2333** [comment]
发件箱默认不会删除，收件箱没删除有问题，我修复一下，admin 控制台有一键清理
https://github.com/dreamhunter2333/cloudflare_temp_email/blob/main/worker/src/router.js#L152-L179

<img width="1243" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/3ed146b3-8ed1-4944-b0f4-519dca15d825">

**Comment by acocchat** [comment]
谢谢

**Comment by acocchat** [comment]
无收件人邮件清理，还有收件箱清理似乎不起作用。点击立即清理后，邮件和无收件人邮件一栏还有邮件。

收件箱清理天数有两个按钮？

另外能否加一个显示版本号的功能，更加清晰。

**Comment by dreamhunter2333** [comment]
> 无收件人邮件清理，还有收件箱清理似乎不起作用。点击立即清理后，邮件和无收件人邮件一栏还有邮件。而用户主动删除账号会清理得很干净。
> 
> 
> 
> 收件箱清理天数有两个按钮？
> 
> 
> 
> 另外能否加一个显示版本号的功能，更加清晰。

我修复下，感谢反馈

**Comment by dreamhunter2333** [comment]
> > 无收件人邮件清理，还有收件箱清理似乎不起作用。点击立即清理后，邮件和无收件人邮件一栏还有邮件。而用户主动删除账号会清理得很干净。
> > 收件箱清理天数有两个按钮？
> > 另外能否加一个显示版本号的功能，更加清晰。
> 
> 我修复下，感谢反馈

已增加版本号显示，cli 部署需自行增加，ui 压缩包部署可自动显示
<img width="1275" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/a8fd23d2-747f-404b-85dc-b6ef3575553f">
https://temp-mail-docs.awsl.uk/zh/guide/cli/pages.html#:~:text=%23%20export%20VITE_VERSION%3D0.0.0

**Comment by acocchat** [comment]
raw_mails ，sendbox表还是删不干净

**Comment by dreamhunter2333** [comment]
> raw_mails ，sendbox表还是删不干净

我测试下，最新版应该没问题
