### ISSUE TITLE
[Feature]能否添加支持，收到的邮件转发到webhook

### ISSUE THREAD

**Issue by C-Plusone** [dreamhunter2333/cloudflare_temp_email#224]
## 功能
将收到的邮件内容转发到webhook
这样可以将这个作为转发接收邮箱，然后转发到webhook，感谢大佬

**Comment by dreamhunter2333** [comment]
OK，我可以加一下

**Comment by dreamhunter2333** [comment]
想确认下，webhook 是全局配置还是针对每个邮箱地址

**Comment by C-Plusone** [comment]
> 想确认下，webhook 是全局配置还是针对每个邮箱地址

在管理界面授权，账户界面配置webhook可选邮箱地址转发这样子

**Comment by dreamhunter2333** [comment]
> > 想确认下，webhook 是全局配置还是针对每个邮箱地址
> 
> 在管理界面授权，账户界面配置webhook可选邮箱地址转发这样子

了解了，管理员授权某些邮箱地址，这些邮箱可以配置自己的 webhook

**Comment by dreamhunter2333** [comment]
v0.4.3已支持

**Comment by C-Plusone** [comment]
> v0.4.3已支持
配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到

**Comment by C-Plusone** [comment]
> 配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到

管理界面配置了邮箱白名单，用户配置了webhook测试成功并保存，还需要配置哪里吗

**Comment by dreamhunter2333** [comment]
> > 配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到
> 
> 管理界面配置了邮箱白名单，用户配置了webhook测试成功并保存，还需要配置哪里吗

不需要了，可以发邮件测试下

**Comment by C-Plusone** [comment]
> > > 配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到
> > 
> > 
> > 管理界面配置了邮箱白名单，用户配置了webhook测试成功并保存，还需要配置哪里吗
> 
> 不需要了，可以发邮件测试下

webhook测试页的可以收到，收件箱有接收到邮件，但是没有收到webhook推送

**Comment by dreamhunter2333** [comment]
> > > > 配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到
> > > 
> > > 
> > > 管理界面配置了邮箱白名单，用户配置了webhook测试成功并保存，还需要配置哪里吗
> > 
> > 
> > 不需要了，可以发邮件测试下
> 
> webhook测试页的可以收到，收件箱有接收到邮件，但是没有收到webhook推送

可以看下后台日志么

**Comment by dreamhunter2333** [comment]
> > > > > > 配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到
> > > > > 
> > > > > 
> > > > > 管理界面配置了邮箱白名单，用户配置了webhook测试成功并保存，还需要配置哪里吗
> > > > 
> > > > 
> > > > 不需要了，可以发邮件测试下
> > > 
> > > 
> > > webhook测试页的可以收到，收件箱有接收到邮件，但是没有收到webhook推送
> > 
> > 
> > 可以看下后台日志么
> 
> ![image](https://private-user-images.githubusercontent.com/97445906/332124738-9b93a89f-3ff8-4aed-af77-04d383c0f9dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg0OTYsIm5iZiI6MTcxNjIyODE5NiwicGF0aCI6Ii85NzQ0NTkwNi8zMzIxMjQ3MzgtOWI5M2E4OWYtM2ZmOC00YWVkLWFmNzctMDRkMzgzYzBmOWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTc1MWJkNDU0ZWVhNWI4YTJkMGMwOWRkZDBjMTcyZDAyMWQzZmNiZjdkMGQ4MDdmOWZmZGJkNGQwYTU2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XIKwpcZwX0TeKPwb4kf2DZhmEoeSxnjpPCOo5COaMxg) ![image](https://private-user-images.githubusercontent.com/97445906/332131129-64c5d98f-5eff-4a83-be37-dec875f41da8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg0OTYsIm5iZiI6MTcxNjIyODE5NiwicGF0aCI6Ii85NzQ0NTkwNi8zMzIxMzExMjktNjRjNWQ5OGYtNWVmZi00YTgzLWJlMzctZGVjODc1ZjQxZGE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNzdkMjFjODk4MWY1Yjc0ZjU2NTE1Y2E2Mzg5MWJhYTA1NTg2NWE3ZGQyMmQwZmY0ZjA4Yjc3MWY1MjAxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_R1CptvGCu7s7zWaxjDUCI5rAl4nDk_7E9Oxwuw3gU)
> 
> 格式错误吗，但是测试可以收到

看起来是格式问题，我把字段都 JSON.stringify 了，可以再试试

**Comment by C-Plusone** [comment]
> > > > > > > 配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到
> > > > > > 
> > > > > > 
> > > > > > 管理界面配置了邮箱白名单，用户配置了webhook测试成功并保存，还需要配置哪里吗
> > > > > 
> > > > > 
> > > > > 不需要了，可以发邮件测试下
> > > > 
> > > > 
> > > > webhook测试页的可以收到，收件箱有接收到邮件，但是没有收到webhook推送
> > > 
> > > 
> > > 可以看下后台日志么
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/97445906/332124738-9b93a89f-3ff8-4aed-af77-04d383c0f9dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg0OTYsIm5iZiI6MTcxNjIyODE5NiwicGF0aCI6Ii85NzQ0NTkwNi8zMzIxMjQ3MzgtOWI5M2E4OWYtM2ZmOC00YWVkLWFmNzctMDRkMzgzYzBmOWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTc1MWJkNDU0ZWVhNWI4YTJkMGMwOWRkZDBjMTcyZDAyMWQzZmNiZjdkMGQ4MDdmOWZmZGJkNGQwYTU2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XIKwpcZwX0TeKPwb4kf2DZhmEoeSxnjpPCOo5COaMxg) ![image](https://private-user-images.githubusercontent.com/97445906/332131129-64c5d98f-5eff-4a83-be37-dec875f41da8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg0OTYsIm5iZiI6MTcxNjIyODE5NiwicGF0aCI6Ii85NzQ0NTkwNi8zMzIxMzExMjktNjRjNWQ5OGYtNWVmZi00YTgzLWJlMzctZGVjODc1ZjQxZGE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNzdkMjFjODk4MWY1Yjc0ZjU2NTE1Y2E2Mzg5MWJhYTA1NTg2NWE3ZGQyMmQwZmY0ZjA4Yjc3MWY1MjAxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_R1CptvGCu7s7zWaxjDUCI5rAl4nDk_7E9Oxwuw3gU)
> > 格式错误吗，但是测试可以收到
> 
> 看起来是格式问题，我把main分支字段都 JSON.stringify 了，可以再试试

![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/97445906/3a66e64e-97a4-45c0-be55-495b1b67a0f3)
重新部署后端后，还是报这个

**Comment by dreamhunter2333** [comment]
> > > > > > > > 配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到
> 
> > > > > > > 
> 
> > > > > > > 
> 
> > > > > > > 管理界面配置了邮箱白名单，用户配置了webhook测试成功并保存，还需要配置哪里吗
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 不需要了，可以发邮件测试下
> 
> > > > > 
> 
> > > > > 
> 
> > > > > webhook测试页的可以收到，收件箱有接收到邮件，但是没有收到webhook推送
> 
> > > > 
> 
> > > > 
> 
> > > > 可以看下后台日志么
> 
> > > 
> 
> > > 
> 
> > > ![image](https://private-user-images.githubusercontent.com/97445906/332124738-9b93a89f-3ff8-4aed-af77-04d383c0f9dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg0OTYsIm5iZiI6MTcxNjIyODE5NiwicGF0aCI6Ii85NzQ0NTkwNi8zMzIxMjQ3MzgtOWI5M2E4OWYtM2ZmOC00YWVkLWFmNzctMDRkMzgzYzBmOWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTc1MWJkNDU0ZWVhNWI4YTJkMGMwOWRkZDBjMTcyZDAyMWQzZmNiZjdkMGQ4MDdmOWZmZGJkNGQwYTU2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XIKwpcZwX0TeKPwb4kf2DZhmEoeSxnjpPCOo5COaMxg) ![image](https://private-user-images.githubusercontent.com/97445906/332131129-64c5d98f-5eff-4a83-be37-dec875f41da8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg0OTYsIm5iZiI6MTcxNjIyODE5NiwicGF0aCI6Ii85NzQ0NTkwNi8zMzIxMzExMjktNjRjNWQ5OGYtNWVmZi00YTgzLWJlMzctZGVjODc1ZjQxZGE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNzdkMjFjODk4MWY1Yjc0ZjU2NTE1Y2E2Mzg5MWJhYTA1NTg2NWE3ZGQyMmQwZmY0ZjA4Yjc3MWY1MjAxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_R1CptvGCu7s7zWaxjDUCI5rAl4nDk_7E9Oxwuw3gU)
> 
> > > 格式错误吗，但是测试可以收到
> 
> > 
> 
> > 看起来是格式问题，我把main分支字段都 JSON.stringify 了，可以再试试
> 
> 
> 
> ![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/97445906/3a66e64e-97a4-45c0-be55-495b1b67a0f3)
> 
> 重新部署后端后，还是报这个

部署的 main分支呢，我有空测试下特殊邮件

**Comment by C-Plusone** [comment]
> > > > > > > > > 配置了webhook 测试也成功收到，但是发送邮件到邮箱收件箱收到，但webhook没收到
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 管理界面配置了邮箱白名单，用户配置了webhook测试成功并保存，还需要配置哪里吗
> > > > > > > 
> > > > > > > 
> > > > > > > 不需要了，可以发邮件测试下
> > > > > > 
> > > > > > 
> > > > > > webhook测试页的可以收到，收件箱有接收到邮件，但是没有收到webhook推送
> > > > > 
> > > > > 
> > > > > 可以看下后台日志么
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/97445906/332124738-9b93a89f-3ff8-4aed-af77-04d383c0f9dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg0OTYsIm5iZiI6MTcxNjIyODE5NiwicGF0aCI6Ii85NzQ0NTkwNi8zMzIxMjQ3MzgtOWI5M2E4OWYtM2ZmOC00YWVkLWFmNzctMDRkMzgzYzBmOWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTc1MWJkNDU0ZWVhNWI4YTJkMGMwOWRkZDBjMTcyZDAyMWQzZmNiZjdkMGQ4MDdmOWZmZGJkNGQwYTU2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XIKwpcZwX0TeKPwb4kf2DZhmEoeSxnjpPCOo5COaMxg) ![image](https://private-user-images.githubusercontent.com/97445906/332131129-64c5d98f-5eff-4a83-be37-dec875f41da8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjg0OTYsIm5iZiI6MTcxNjIyODE5NiwicGF0aCI6Ii85NzQ0NTkwNi8zMzIxMzExMjktNjRjNWQ5OGYtNWVmZi00YTgzLWJlMzctZGVjODc1ZjQxZGE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE4MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNzdkMjFjODk4MWY1Yjc0ZjU2NTE1Y2E2Mzg5MWJhYTA1NTg2NWE3ZGQyMmQwZmY0ZjA4Yjc3MWY1MjAxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_R1CptvGCu7s7zWaxjDUCI5rAl4nDk_7E9Oxwuw3gU)
> > > > 格式错误吗，但是测试可以收到
> > > 
> > > 
> > > 看起来是格式问题，我把main分支字段都 JSON.stringify 了，可以再试试
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/97445906/332657914-3a66e64e-97a4-45c0-be55-495b1b67a0f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODIzOTQsIm5iZiI6MTcxNjM4MjA5NCwicGF0aCI6Ii85NzQ0NTkwNi8zMzI2NTc5MTQtM2E2NmU2NGUtOTdhNC00NWMwLWJlNTUtNDk1YjFiNjdhMGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEyNDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NzNjMDRhZTExZDBmMjgwMTU0Y2Q4NWJiZTBlN2JlYTE3NGIwZjgzNjAzZWY1N2U2NmU2NjllYjdkZGI2MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ajHOI0Q5ng7WEskCSqwSIJSNLD_2HAg5UcZJVW3rANo) 重新部署后端后，还是报这个
> 
> main 分支我测试多行邮件也没问题了，麻烦有空试试

可以了大佬，接了几个验证码测试，没问题

**Comment by dreamhunter2333** [comment]
模板中使用的 parsedtxt 么

**Comment by dreamhunter2333** [comment]
> > 模板中使用的 parsedtxt 么，应该是 email 解析失败了，我看看怎么用其他库解析
> 
> 哇😯这么晚还在啊，是的使用的parsedText

有空可以试试这个
https://temp-mail-docs.awsl.uk/zh/guide/feature/mail_parser_wasm_worker.html

**Comment by dreamhunter2333** [comment]
> > > > 模板中使用的 parsedtxt 么，应该是 email 解析失败了，我看看怎么用其他库解析
> > > 
> > > 
> > > 哇😯这么晚还在啊，是的使用的parsedText
> > 
> > 
> > 有空可以试试这个 https://temp-mail-docs.awsl.uk/zh/guide/feature/mail_parser_wasm_worker.html
> 
> 这个Github Actions取消注释，然后Deploy Backend Production部署可以吗，应该还是${parsedText}吧

可以的，由于加了这个打包大很多，而且没法软开关，就没有默认开启了
