### ISSUE TITLE
发邮件[BUG]

### ISSUE THREAD

**Issue by wsgehaishan520** [dreamhunter2333/cloudflare_temp_email#232]
## 预期行为
不知道为什么不能发信，配置好像也没错

## 部署方式

- [x] cli 部署
- [1 ]  用户界面部署

**Comment by dreamhunter2333** [comment]
看起来了像  _mailchannels 记录未配置，或者还没有生效

**Comment by wsgehaishan520** [comment]
能帮我删帖子么，好像有我的敏感信息
