### ISSUE TITLE
通过GitHub action部署出现Cannot read properties of undefined

### ISSUE THREAD

**Issue by pawofpuzzle** [dreamhunter2333/cloudflare_temp_email#233]
感谢大佬的项目，小弟有个问题，通过GitHub action部署出现Cannot read properties of undefined该如何解决，麻烦大佬了

**Comment by dreamhunter2333** [comment]
可以发一下错误日志么

**Comment by pawofpuzzle** [comment]
大佬你好，所有workflow都能运行，不知道哪里看错误日志呀qwq，麻烦你了

**Comment by pawofpuzzle** [comment]
大佬，action所有的workflow正常运行，不知道在哪里看错误日志呀qwq，麻烦啦

**Comment by pawofpuzzle** [comment]
> 可以发一下错误日志么

谢谢大佬，已解决，是我的配置问题
