### ISSUE TITLE
[BUG] 多个域名时回复邮件报错

### ISSUE THREAD

**Issue by pwddd** [dreamhunter2333/cloudflare_temp_email#239]
## 复现步骤
后端使用的temp-email-api.aaaa.com，当使用aaaa.com接收和回复邮件时，正常。使用bbbb.com回复邮件报错。
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/138374591/075368e2-a9e7-4891-b32a-cb355b2bf538)

测试后端使用temp-email-api.bbbb.com时，bbbb.com可以正常回复邮件。

## 预期行为

使用aaaa.com和bbbb.com都可以正常回复邮件。

## 部署方式

- [ ] cli 部署
- [ ]  用户界面部署

## 浏览器环境
Chrome

**Comment by dreamhunter2333** [comment]
bbbb.com 是否配置了相同 dns 呢，多个域名都要配置同样的 _mailchannels 记录

<img width="730" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/26241e91-d48c-4426-8a79-90c150095a57">

**Comment by pwddd** [comment]
我按照教程重新配置了一下，问题解决了，感谢。
