### ISSUE TITLE
Outlook寄来的邮件无法显示内容

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#25]
你好，
最近使用一段时间后，发现一个小问题，就是若是由outlook寄来的邮件，只会显示标题，内容无法显示。
目前似乎只有outlook会有这个问题。

**Comment by dreamhunter2333** [comment]
我测试正常，不过字体颜色会有点问题， 黑色在暗色下看不出文字，

<img width="1108" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/dca78422-986e-406c-8ff6-b985ed8352b6">

**Comment by xiewei3536** [comment]
> 我测试正常，不过字体颜色会有点问题， 黑色在暗色下看不出文字，
> 
> <img alt="image" width="1108" src="https://user-images.githubusercontent.com/32295532/273092217-dca78422-986e-406c-8ff6-b985ed8352b6.png">

<img width="1089" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/9ed44e0d-79a5-4a28-be94-33332f54a49a">
大佬，我自己测试都是只有显示标题而已。其他域名的邮件就都正常。主题也是用的白色

**Comment by xiewei3536** [comment]
> 我测试正常，不过字体颜色会有点问题， 黑色在暗色下看不出文字，
> 
> <img alt="image" width="1108" src="https://user-images.githubusercontent.com/32295532/273092217-dca78422-986e-406c-8ff6-b985ed8352b6.png">

你能试试看只打一句话的情况下，是否也能显示出来呢？
我内容只有打这么一句 hello！How are you？

**Comment by dreamhunter2333** [comment]
> > 我测试正常，不过字体颜色会有点问题， 黑色在暗色下看不出文字，
> > <img alt="image" width="1108" src="https://user-images.githubusercontent.com/32295532/273092217-dca78422-986e-406c-8ff6-b985ed8352b6.png">
> 
> 你能试试看只打一句话的情况下，是否也能显示出来呢？ 我内容只有打这么一句 hello！How are you？

确实是空的了，我找下原因

**Comment by dreamhunter2333** [comment]
mailparser 有时候解析不了 Outlook 一行的邮件，加了个兜底策略，失败了再尝试 `postal-mime`

**Comment by xiewei3536** [comment]
> mailparser 有时候解析不了 Outlook 一行的邮件，加了个兜底策略，失败了再尝试 `postal-mime`

非常感谢！已经解决，有正常显示了！
