### ISSUE TITLE
[BUG] smtp配置问题

### ISSUE THREAD

**Issue by jakernel** [dreamhunter2333/cloudflare_temp_email#268]
使用 docker 部署了 smtp 服务。然后 thunderbird 添加账号后，收发邮件会报错，不知道哪里配置错了
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/1704664/06342d72-2b4c-4db2-b757-376ed3581fe2)

查看 docker 的日志显示如下：
```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 803, in __cbDispatch
    self.__doCommand(tag, fn, args, parseargs, rest, uid)
  File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 796, in __doCommand
    handler(uid=uid, *args)
  File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 2059, in do_FETCH
    maybeDeferred(self.mbox.fetch, messages, uid=uid).addCallback(
---  ---
  File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 212, in maybeDeferred
    result = f(*args, **kwargs)
  File "/app/imap_server.py", line 109, in fetch
    return self.fetchINBOX(messages)
  File "/app/imap_server.py", line 120, in fetchINBOX
    res = httpx.get(
  File "/usr/local/lib/python3.12/site-packages/httpx/_api.py", line 198, in get
    return request(
  File "/usr/local/lib/python3.12/site-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'xxx.xxx.workers.dev'. (_ssl.c:1000)
```

**Comment by dreamhunter2333** [comment]
> 使用 docker 部署了 smtp 服务。然后 thunderbird 添加账号后，收发邮件会报错，不知道哪里配置错了
> 
> ![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/1704664/06342d72-2b4c-4db2-b757-376ed3581fe2)
> 
> 
> 
> 查看 docker 的日志显示如下：
> 
> ```
> 
> Unhandled Error
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
> 
>     current.result = callback(  # type: ignore[misc]
> 
>   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 803, in __cbDispatch
> 
>     self.__doCommand(tag, fn, args, parseargs, rest, uid)
> 
>   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 796, in __doCommand
> 
>     handler(uid=uid, *args)
> 
>   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 2059, in do_FETCH
> 
>     maybeDeferred(self.mbox.fetch, messages, uid=uid).addCallback(
> 
> ---  ---
> 
>   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 212, in maybeDeferred
> 
>     result = f(*args, **kwargs)
> 
>   File "/app/imap_server.py", line 109, in fetch
> 
>     return self.fetchINBOX(messages)
> 
>   File "/app/imap_server.py", line 120, in fetchINBOX
> 
>     res = httpx.get(
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_api.py", line 198, in get
> 
>     return request(
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_api.py", line 106, in request
> 
>     return client.request(
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 827, in request
> 
>     return self.send(request, auth=auth, follow_redirects=follow_redirects)
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 914, in send
> 
>     response = self._send_handling_auth(
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 942, in _send_handling_auth
> 
>     response = self._send_handling_redirects(
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
> 
>     response = self._send_single_request(request)
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1015, in _send_single_request
> 
>     response = transport.handle_request(request)
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 232, in handle_request
> 
>     with map_httpcore_exceptions():
> 
>   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
> 
>     self.gen.throw(value)
> 
>   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
> 
>     raise mapped_exc(message) from exc
> 
> httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'xxx.xxx.workers.dev'. (_ssl.c:1000)
> 
> ```

目前还不支持ssl ，需要勾选非 ssl链接

**Comment by dreamhunter2333** [comment]
你能使用 api 访问后台服务么

**Comment by jakernel** [comment]
> 你能使用 api 访问后台服务么，看起来像无法访问 worker api

可以的，api可以正常访问 `https://xxx.xxx.workers.dev` 收取邮件，但是smtp下调用到 fetchINBOX 这个接口时，
却会抛出 ssl 证书异常

**Comment by dreamhunter2333** [comment]
> > 你能使用 api 访问后台服务么，看起来像无法访问 worker api
> 
> 
> 
> 可以的，api可以正常访问 `https://xxx.xxx.workers.dev` 收取邮件，但是smtp下调用到 fetchINBOX 这个接口时，
> 
> 却会抛出 ssl 证书异常

很奇怪，尝试过自定义域名么，我有空更新下代码，禁用ssl检查

**Comment by jakernel** [comment]
> > > 你能使用 api 访问后台服务么，看起来像无法访问 worker api
> > 
> > 
> > 可以的，api可以正常访问 `https://xxx.xxx.workers.dev` 收取邮件，但是smtp下调用到 fetchINBOX 这个接口时，
> > 却会抛出 ssl 证书异常
> 
> 很奇怪，尝试过自定义域名么，我有空更新下代码，禁用ssl检查

测试了自定义域名可以正常收发
