### ISSUE TITLE
能否添加对象存储支持邮件附件的持久化存储？

### ISSUE THREAD

**Issue by xshenhan** [dreamhunter2333/cloudflare_temp_email#277]
## 请描述您的 Feature
能否添加对象存储支持邮件附件的持久化存储，s3格式之类的？有些邮箱数据还是希望能够长期存储的。

## 描述您考虑过的替代方案
cloudflare R2储存之类的。但是还是希望能接入通用的s3格式。

**Comment by dreamhunter2333** [comment]
是指提单独存储附件么，目前是存储在d1数据库的

**Comment by xshenhan** [comment]
比如说可以支持接入对象储存，把附件储存在对象储存中，d1数据库中只存链接之类的。主要是d1数据库存储空间太有限了。

**Comment by dreamhunter2333** [comment]
> 比如说可以支持接入对象储存，把附件储存在对象储存中，d1数据库中只存链接之类的。主要是d1数据库存储空间太有限了。

目前由于免费worker 的cpu限制以及nodejs 的邮件解析限制，后端是无法解析出大附件邮件的，现在全部才用了浏览器来解析，目前有个下载附件按钮，可以在UI上做个转存附件到R2

**Comment by xshenhan** [comment]
> > 比如说可以支持接入对象储存，把附件储存在对象储存中，d1数据库中只存链接之类的。主要是d1数据库存储空间太有限了。
> 
> 目前由于免费worker 的cpu限制以及nodejs 的邮件解析限制，后端是无法解析出大附件邮件的，现在全部才用了浏览器来解析，目前有个下载附件按钮，可以在UI上做个转存附件到R2

我觉得可以，希望不只可以接入r2，希望兼容所有的s3格式的对象储存。这个实现上难度应该是类似的吧。另外转存以后，d1中的空间会被释放替换成链接吗？

**Comment by dreamhunter2333** [comment]
> > > 比如说可以支持接入对象储存，把附件储存在对象储存中，d1数据库中只存链接之类的。主要是d1数据库存储空间太有限了。
> > 
> > 目前由于免费worker 的cpu限制以及nodejs 的邮件解析限制，后端是无法解析出大附件邮件的，现在全部才用了浏览器来解析，目前有个下载附件按钮，可以在UI上做个转存附件到R2
> 
> 我觉得可以，希望不只可以接入r2，希望兼容所有的s3格式的对象储存。这个实现上难度应该是类似的吧。另外转存以后，d1中的空间会被释放替换成链接吗？

可以的 d1 的内容可以进行修改，不过通过ui就不能批量了，只能单独操作一封邮件

**Comment by xshenhan** [comment]
> > > > 比如说可以支持接入对象储存，把附件储存在对象储存中，d1数据库中只存链接之类的。主要是d1数据库存储空间太有限了。
> > > 
> > > 目前由于免费worker 的cpu限制以及nodejs 的邮件解析限制，后端是无法解析出大附件邮件的，现在全部才用了浏览器来解析，目前有个下载附件按钮，可以在UI上做个转存附件到R2
> > 
> > 我觉得可以，希望不只可以接入r2，希望兼容所有的s3格式的对象储存。这个实现上难度应该是类似的吧。另外转存以后，d1中的空间会被释放替换成链接吗？
> 
> 可以的 d1 的内容可以进行修改，不过通过ui就不能批量了，只能单独操作一封邮件

可以的，谢谢回复！

**Comment by dreamhunter2333** [comment]
https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.5.0 已增加

- 添加保存附件到 S3 的功能 [文档地址](https://temp-mail-docs.awsl.uk/zh/guide/feature/s3-attachment.html)
