### ISSUE TITLE
[BUG] 按部署文档中在图形界面初始化数据库报错 ？

### ISSUE THREAD

**Issue by 80imike** [dreamhunter2333/cloudflare_temp_email#278]
按部署文档中在图形界面初始化数据库报错 ？

![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/1665201/26e5bf6a-27ce-4dec-ade6-908b0b3cd62d)

文档是不是有一部分没有写， 直接执行好像找不到这个 sql

**Comment by oneisall8955** [comment]
姿势不正确，把sql整个内容贴进去执行就行了

**Comment by 80imike** [comment]
> 姿势不正确，把sql整个内容贴进去执行就行了
 
感谢，这里可以了
