### ISSUE TITLE
管理员有办法查询密码么？

### ISSUE THREAD

**Issue by goxofy** [dreamhunter2333/cloudflare_temp_email#28]

**Comment by dreamhunter2333** [comment]
正在计划加一个 admin 控制台，可以查看密码

**Comment by dreamhunter2333** [comment]
增加了 admin 页面，需在配置文件增加密码，访问 `/admin` 地址

**Comment by goxofy** [comment]
> 增加了 admin 页面，需在配置文件增加密码，访问 `/admin` 地址

如果升级的话，pull 最新的代码然后重新部署 workers 和 frontend 就行了吗，数据库需要重新导入吗

**Comment by dreamhunter2333** [comment]
> > 增加了 admin 页面，需在配置文件增加密码，访问 `/admin` 地址
> 
> 如果升级的话，pull 最新的代码然后重新部署 workers 和 frontend 就行了吗，数据库需要重新导入吗

重新部署即可，数据库无需更新（没有数据库表结构的变更）

**Comment by goxofy** [comment]
请问下更新的话，JWT_SECRET这个参数必须和之前一样吗？
