### ISSUE TITLE
[BUG] 发邮件给监时邮箱报 550 5.1.1 Address does not exist. IoNoxggOpIHN

### ISSUE THREAD

**Issue by 80imike** [dreamhunter2333/cloudflare_temp_email#280]
发邮件给监时邮箱报

以下为远程服务器的响应：
550 5.1.1 Address does not exist. IoNoxggOpIHN

这是什么原因呢？

**Comment by oneisall8955** [comment]
https://github.com/dreamhunter2333/cloudflare_temp_email/issues/52

盲猜没有配置好cloudflare

**Comment by 80imike** [comment]
> #52
> 
> 盲猜没有配置好cloudflare

cloudflare 具体哪里的问题呢？

**Comment by 80imike** [comment]
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/1665201/e068d3d9-9198-477a-82a7-a95ac8a363ff)

直接发给这里的自定义邮件地址 是可以收到邮件的

**Comment by 80imike** [comment]
cloudflare-tempe-mail-backend 后端服务也是可以正常访问有

**Comment by dreamhunter2333** [comment]
是指接收不到 catch all 的邮件么，需要在 cf 增加一个认证邮箱才能收到邮件

**Comment by 80imike** [comment]
> 是指接收不到 catch all 的邮件么，需要在 cf 增加一个认证邮箱才能收到邮件

是的收不到   catch all 的邮件  cf 增加一个认证邮箱具体要怎么做？ @dreamhunter2333

**Comment by oneisall8955** [comment]
@80imike 麻烦追加处理过程，为后续遇到相同问题的提供思路😁

**Comment by 80imike** [comment]
> @80imike 麻烦追加处理过程，为后续遇到相同问题的提供思路😁

就是 需要在 cf 增加一个认证邮箱才能收到邮件

**Comment by dreamhunter2333** [comment]
文档第二步有提到这个，是 cloudflare 的限制
https://temp-mail-docs.awsl.uk/zh/guide/email-routing.html
