### ISSUE TITLE
使用界面部署 都显示成功 但访问不了

### ISSUE THREAD

**Issue by rational-stars** [dreamhunter2333/cloudflare_temp_email#286]
<img width="505" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/bd9f13bb-b0e6-4f68-b09a-e56d2c16077e">

这是 wordks 地址 https://mymail.960303390.workers.dev/  访问结果显示 ok
前端地址  
<img width="1194" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/1001bdb5-d298-4dfb-89cd-104ec6b32b4b">
前端按照文档修改了 index.js
<img width="687" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/f6b583ff-787a-4081-b51d-77e7ad66f777">
<img width="692" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/a9f3da24-be36-41bb-856a-dc96046f37ee">
大佬帮我看下问题吧 谢谢

**Comment by dreamhunter2333** [comment]
看起来像 dns 还没生效，我这边访问你的worker地址显示ok了

**Comment by dreamhunter2333** [comment]
检查下压缩包是否压缩了多层，前端 pages 没部署成功

**Comment by rational-stars** [comment]
> 检查下压缩包是否压缩了多层，前端 pages 没部署成功

哈哈 感谢我太傻了 我以为他会自己解压 我上传的是压缩包
