### ISSUE TITLE
admin 管理页面一直提示 401 

### ISSUE THREAD

**Issue by rational-stars** [dreamhunter2333/cloudflare_temp_email#287]
<img width="278" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/55a7c169-6821-413b-8ac9-faf16c132c4f">
先说一下 这两个画框的我是没配置的  原谅我这么多问题 包容一下哈 感谢

<img width="663" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/3a6fd8ae-4ebc-4501-a38c-b38cda90e3f6">
这是我的配置截图  
https://mail-air.pages.dev/admin
上面是我的前端 web 地址
<img width="555" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/4f3ed061-e25c-452f-9ad8-109848ff8736">
<img width="1200" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/2bdd7ba9-7813-4fc4-a07e-a0eeb65d4ba2">

<img width="889" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/29780168-7e33-42ad-b61d-6eaf1ae21dd0">
还有我不是开启了 KV 嘛 ，在页面上找不到注册按钮

邮箱地址凭据 没搞懂是啥
<img width="1119" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/7d037f2f-43f7-4b3f-857e-3dcf27d6df10">

**Comment by dreamhunter2333** [comment]
admin passwords 是个字符串列表，可以参考文档的例子

**Comment by dreamhunter2333** [comment]
配置文件中允许用户创建邮箱即可允许创建，用户登录可以在 admin 用户页面配置
https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html#%E4%BF%AE%E6%94%B9-wrangler-toml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by rational-stars** [comment]
<img width="673" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/086a012e-a28c-48d8-9224-1b0dd99540a6">
这样的我之前也试了 我复制文档里面的也不行  我手打英文也不行 我有点难受

**Comment by rational-stars** [comment]
> 配置文件中很荣幸能够创建邮箱即可允许创建，用户登录可以在管理员用户页面配置 https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html#%E4%BF%AE%E6%94%B9-wrangler-toml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
好难啊 手打的数组加双引号字符串也用了 单引号字符串也用了 文档里的也复制了 不用数组的也试了  各种组合我都试完了 要么是 401 要是 500  我该怎么办 是因为我没有配置 DKIM 还是什么
<img width="548" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/aa7869f8-e32b-4948-9102-a0c94fa98759">

**Comment by rational-stars** [comment]
六一快乐 抽时间回就行

**Comment by dreamhunter2333** [comment]
> rational-stars.top

密码看其已经认证成功了，是不是没绑定 D1 数据库

**Comment by rational-stars** [comment]
> > rational-stars.top
> 
> 密码看起来已经认证成功了，是不是没绑定 D1 数据库，或者名字不是 `DB`

<img width="594" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/0512494d-5782-4a57-a597-b18b75092231">
<img width="613" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/dae1e07d-ec66-44b7-a30f-62b6639166a3">
绑了呀

**Comment by dreamhunter2333** [comment]
> > > rational-stars.top
> 
> > 
> 
> > 密码看起来已经认证成功了，是不是没绑定 D1 数据库，或者名字不是 `DB`
> 
>  是数据库和 KV 名字的问题   不好意思 麻烦了  非常感谢 六一快乐
> 
> 
> 
> <img width="613" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/65513250/dae1e07d-ec66-44b7-a30f-62b6639166a3">
> 
> 
> 
> 

变量名称可以参考 cli 部署 worker 的部分
