### ISSUE TITLE
想请问一下大佬为什么出现这样的问题和解决方法

### ISSUE THREAD

**Issue by DR-lin-eng** [dreamhunter2333/cloudflare_temp_email#300]
注册邮箱时出现Code 400: Failed create address: Failed to create address
管理员界面出现：Code 500: Internal Server Error
附上报错的控制台
400的： POST https://emailcuncu.linzefeng.top/api/new_address 400 (Bad Request)
500：Failed to load resource: the server responded with a status of 500 ()
Admin-9OyjNtz4.js:35 Error: Code 500: Internal Server Error
    at Object.Li [as fetch] (index-BepwDP49.js:4037:5518)
    at async k (Admin-9OyjNtz4.js:35:11682)
    at async Admin-9OyjNtz4.js:35:13149

**Comment by dreamhunter2333** [comment]
> 注册邮箱时出现Code 400: Failed create address: Failed to create address
> 
> 管理员界面出现：Code 500: Internal Server Error
> 
> 附上报错的控制台
> 
> 400的： POST https://emailcuncu.linzefeng.top/api/new_address 400 (Bad Request)
> 
> 500：Failed to load resource: the server responded with a status of 500 ()
> 
> Admin-9OyjNtz4.js:35 Error: Code 500: Internal Server Error
> 
>     at Object.Li [as fetch] (index-BepwDP49.js:4037:5518)
> 
>     at async k (Admin-9OyjNtz4.js:35:11682)
> 
>     at async Admin-9OyjNtz4.js:35:13149

可以看下worker后台的报错么，是不是 d1 数据库没绑定，或者 名字不是 DB

**Comment by DR-lin-eng** [comment]
> > 注册邮箱时出现Code 400: Failed create address: Failed to create address
> > 管理员界面出现：Code 500: Internal Server Error
> > 附上报错的控制台
> > 400的： POST https://emailcuncu.linzefeng.top/api/new_address 400 (Bad Request)
> > 500：Failed to load resource: the server responded with a status of 500 ()
> > Admin-9OyjNtz4.js:35 Error: Code 500: Internal Server Error
> > ```
> > at Object.Li [as fetch] (index-BepwDP49.js:4037:5518)
> > 
> > at async k (Admin-9OyjNtz4.js:35:11682)
> > 
> > at async Admin-9OyjNtz4.js:35:13149
> > ```
> 
> 可以看下worker后台的报错么，是不是 d1 数据库没绑定，或者 名字不是 DB

Error: D1_ERROR: no such table: settings
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/52230594/2d7960ec-8fa2-43e1-a7aa-05d8d387af05)
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/52230594/a9b826ea-6324-4963-8cce-7ab6c12047ea)

**Comment by dreamhunter2333** [comment]
需要初始化数据库，参考文档的 D1 部分

**Comment by DR-lin-eng** [comment]
> 需要初始化数据库，参考文档的 D1 部分

> db/schema.sql
near "db": syntax error at offset 0

**Comment by dreamhunter2333** [comment]
> db/schema.sql

执行仓库中这个文件的所有内容

**Comment by DR-lin-eng** [comment]
> > db/schema.sql
> 
> 执行仓库中这个文件的所有内容 <img alt="image" width="732" src="https://private-user-images.githubusercontent.com/32295532/335816979-70c73a22-2117-4e19-81be-e15b3b0c7f2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTc0OTksIm5iZiI6MTcxNzI5NzE5OSwicGF0aCI6Ii8zMjI5NTUzMi8zMzU4MTY5NzktNzBjNzNhMjItMjExNy00ZTE5LTgxYmUtZTE1YjNiMGM3ZjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAyNTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNDUxYWQ0N2M3MGE1ZmJjOTY1MDdiMGYzZDZhMTFmMDI2N2M4NmY5OTY0ZmQyM2MxOWJiMzU1NTE3MDgwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GPcLUD8mWCQEq3--nNQ_2u5iP9fLdlXuZaxzR1cNfR8">

感谢指导是我理解错误了，辛苦大佬了

**Comment by VectorZhao** [comment]
> > db/schema.sql
> 
> 执行仓库中这个文件的所有内容 <img alt="image" width="732" src="https://private-user-images.githubusercontent.com/32295532/335816979-70c73a22-2117-4e19-81be-e15b3b0c7f2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzYwOTAsIm5iZiI6MTcxNzU3NTc5MCwicGF0aCI6Ii8zMjI5NTUzMi8zMzU4MTY5NzktNzBjNzNhMjItMjExNy00ZTE5LTgxYmUtZTE1YjNiMGM3ZjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA4MjMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjY2NzkwOWUxYjNjM2E0MmJjMjM4MTEzNWFjNjFiY2I3NjZmOTA2MGYzYzdiYjRmMWUzNWRiZWFjYmViNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x0rn2EGkJSpi_bF4v-AHW3oOXW2f9gvyC9MbtIkssLs">

这是啥意思啊？这个文件的所有内容？
我按照部署文档的D1部分代码依次执行了一遍
然后创建邮箱时worker日志如下

"scriptName": "cloudflare_temp_email",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Error: D1_ERROR: no such table: address"
      ],
      "level": "error",
      "timestamp": 1717575670696
    }
  ],

**Comment by VectorZhao** [comment]
哦，是打开这个文件，把内容复制粘贴进去然后运行。搞定了

**Comment by DR-lin-eng** [comment]
> 哦，是打开这个文件，把内容复制粘贴进去然后运行。搞定了

抓到一个同病相怜的，一样理解不透策的
