### ISSUE TITLE
[Feature] 用户端限制输入长度为固定位数

### ISSUE THREAD

**Issue by aliuq** [dreamhunter2333/cloudflare_temp_email#303]
## 请描述您的 Feature

这个项目非常棒，希望用户端限制输入长度为固定位数，管理端则不做限制

**Comment by dreamhunter2333** [comment]
请问是指哪个地方的输入长度

**Comment by aliuq** [comment]
> 请问是指哪个地方的输入长度

感谢回复。我去掉了前缀，希望开放使用时，固定长度为固定长度，仅管理员可手动输入任意长度

![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/11707934/1218e52d-1ed8-42d1-bd8c-124bc10b5601)

**Comment by dreamhunter2333** [comment]
> > 请问是指哪个地方的输入长度
> 
> 
> 
> 感谢回复。我去掉了前缀，希望开放使用时，固定长度为固定长度，仅管理员可手动输入任意长度
> 
> 
> 
> ![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/11707934/a729fa41-4c76-4c90-bfc6-9ba90d0b9003)
> 
> 
> 
> 
> 
> 
> 
> 

了解了，相当于后台配置一个普通用户能注册的长度范围，我有空加一下

**Comment by dreamhunter2333** [comment]
main 分支已增加，我有空发个新的版本
