### ISSUE TITLE
[Feature] 关于服务间内部调用问题

### ISSUE THREAD

**Issue by xlh001** [dreamhunter2333/cloudflare_temp_email#307]
## 请描述您的 Feature
能否采用服务绑定模式进行前后端调用,避免出现网络超时问题
https://developers.cloudflare.com/pages/functions/bindings/#service-bindings
## 描述您想要的解决方案
采用服务绑定模式进行调用
https://developers.cloudflare.com/pages/functions/bindings/#service-bindings

**Comment by dreamhunter2333** [comment]
可以参考文档中部署前端的第二种方式部署

https://temp-mail-docs.awsl.uk/zh/guide/cli/pages.html#%E9%80%9A%E8%BF%87-page-functions-%E8%BD%AC%E5%8F%91%E5%90%8E%E7%AB%AF%E8%AF%B7%E6%B1%82
