### ISSUE TITLE
[Feature]请问可不可以添加一个新建邮箱的API呢

### ISSUE THREAD

**Issue by Nekohy** [dreamhunter2333/cloudflare_temp_email#308]
## 描述您想要的解决方案
GET 新建邮箱接口返回邮箱地址和JWT

**Comment by dreamhunter2333** [comment]
> ## 描述您想要的解决方案
> 
> GET 新建邮箱接口返回邮箱地址和JWT
> 
> 
> 
> 

api 是有的，我加一下文档

**Comment by dreamhunter2333** [comment]
已增加文档
https://temp-mail-docs.awsl.uk/zh/guide/feature/new-address-api.html
