### ISSUE TITLE
创建邮箱报错，查看邮箱凭证报错

### ISSUE THREAD

**Issue by foxdodo** [dreamhunter2333/cloudflare_temp_email#315]
按教程安装部署成功，但是创建邮箱时报错
![1333](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/3275698/233794a2-d635-4e52-bc11-f2b53ef68668)
但是切换到账号标签页可以看到新建的邮箱，而且邮箱可以正常收邮件。

接着是无法查看邮箱凭证，点击查看则前端弹窗报错
`Code 500: Internal Server Error`
后台日志报错
```
  "logs": [
    {
      "message": [
        "TypeError: Cannot read properties of undefined (reading 'includes')"
```
因为无法查看凭证所以无法给自己建的新用户绑定邮箱

**Comment by dreamhunter2333** [comment]
worker 的 JWT_SECRET 是否配置了呢

**Comment by dreamhunter2333** [comment]
> > worker 的 JWT_SECRET 是否配置了呢
> 
> 
> 
> ![23](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/3275698/31a79f63-61b5-4f42-9655-1a2ecdb74aca)
> 
> 这样配置可以吗？也尝试过`JWT_SECRET`=`["faplord"]`  一样的报错，这个值是我乱写的，有影响吗？

图片上的 JWT_SECRE 少了一个 T
