### ISSUE TITLE
[BUG]大大，我部署了但是新建邮箱是选择后缀显示无数据怎么办

### ISSUE THREAD

**Issue by tujiangh** [dreamhunter2333/cloudflare_temp_email#316]
求解谢谢

**Comment by dreamhunter2333** [comment]
worker 部署好了么，打开 worker 的域名会显示 OK

pages 前端部署的时候需要输入 worker 的域名

**Comment by dreamhunter2333** [comment]
> 求解谢谢

可以 f12看看请求的后台 url

**Comment by tujiangh** [comment]
谢谢，Workers部署应该没毛病部署Pages的时候也输了Workers的链接，会不会是Workers变量设置的有毛病？

**Comment by tujiangh** [comment]
https://ehd.ikunweb.eu.org，这是后端地址

在 2024年6月18日星期二，Dream Hunter ***@***.***> 写道：

**Comment by dreamhunter2333** [comment]
> 谢谢，Workers部署应该没毛病部署Pages的时候也输了Workers的链接，会不会是Workers变量设置的有毛病？

有可能

**Comment by dreamhunter2333** [comment]
> 谢谢，Workers部署应该没毛病部署Pages的时候也输了Workers的链接，会不会是Workers变量设置的有毛病？

https://ehd.ikunweb.eu.org/open_api/settings
没有返回域名，看起来是worker 没配置 domains

**Comment by dreamhunter2333** [comment]
参考这个配置

https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html#%E4%BF%AE%E6%94%B9-wrangler-toml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by tujiangh** [comment]
谢谢😊
