### ISSUE TITLE
大佬求救，部署没报错，但是收不到邮件

### ISSUE THREAD

**Issue by kledgold** [dreamhunter2333/cloudflare_temp_email#317]
https://tmp-email-page-v1.pages.dev

我部署后是这样的，不知道应该是哪出了问题

**Comment by kledgold** [comment]
补充一下，查了一下mail那张表是空，邮件似乎发不到这个项目

**Comment by kledgold** [comment]
是不是因为这个
<img width="1375" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/111190538/c4ad5b1e-d8c2-4536-ba6c-d6cbe06b3218">

**Comment by kledgold** [comment]
还有就是这个

<img width="1008" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/111190538/da23e630-d1e8-4e48-a4db-7cb7ba897532">

**Comment by snakejohn** [comment]
大佬，请问你是怎么解决的？
