### ISSUE TITLE
[BUG] 可以接收邮件但无法发送，额度是有的

### ISSUE THREAD

**Issue by 2545504198** [dreamhunter2333/cloudflare_temp_email#320]
## 复现步骤
邮箱后缀是 xxx.xxx
接口是自带的域名，创建邮箱也成功了，但是发送邮件失败
```
Failed to send email: 550 5.7.1 This sender is not authorized to send from xxx.xxx. See https://bit.ly/domain-lockdown. cfid=xxx.workers.dev
```

## 预期行为
正常发送

## 部署方式

- [x]  用户界面部署

## 浏览器环境
Edge

**Comment by dreamhunter2333** [comment]
请问是使用 resend 方式发送邮件的么


https://temp-mail-docs.awsl.uk/zh/guide/config-send-mail.html

**Comment by 2545504198** [comment]
之前配置的自带的一直发不出去，用resend可以了，请关闭
