### ISSUE TITLE
添加一个用户删除邮件的功能

### ISSUE THREAD

**Issue by ghwnode02** [dreamhunter2333/cloudflare_temp_email#327]
## 预期行为
普通用户或管理员可以删除邮箱发出的邮件。

## 部署方式

- [ ] cli 部署
- [ √]  用户界面部署

## 浏览器环境
edge和chroom

**Comment by dreamhunter2333** [comment]
OK，我有空添加一下

**Comment by dreamhunter2333** [comment]
https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.5.3

v0.5.3 已增加

**Comment by ghwnode02** [comment]
好的，感谢
