### ISSUE TITLE
创建 D1 数据库,生成的认证链接，需要手动复制打开，并且认证后无法自动跳转，导致创建数据库失败

### ISSUE THREAD

**Issue by wilsonloss** [dreamhunter2333/cloudflare_temp_email#33]
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/139339542/f9fff53b-df66-4761-9a24-339f3512b2fc)

**Comment by wilsonloss** [comment]
换了不同的ssh软件都是这样，系统是debian11，之前的操作执行都没有报错
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/139339542/9cc15d9d-c74c-4e17-b14e-d0076e26eb6b)

**Comment by dreamhunter2333** [comment]
解决了吗，可以在网页上新建数据库

**Comment by wilsonloss** [comment]
如果手动创建的话
`wrangler d1 execute dev --file=db/schema.sql`
这一步该怎么操作了，还希望大佬解释一下，我自己先去bing等ai问了一下，并没有找到结果

**Comment by wilsonloss** [comment]
谢谢大佬，成功解决，手动在d1的控制台，[db](https://github.com/dreamhunter2333/cloudflare_temp_email/tree/main/db)
/schema.sql手动执行了这些命令，不知道对不对

**Comment by dreamhunter2333** [comment]
只要能运行成功就可以
