### ISSUE TITLE
无限刷新

### ISSUE THREAD

**Issue by superen7527** [dreamhunter2333/cloudflare_temp_email#34]
手机访问了示例站点，点了自动刷新，手动refresh，就全屏灰遮罩了，想取消只能刷新。不知道电脑有没有这种问题，希望可以优化一下，如果想取消换邮件等等，或者区域外部点击取消等等，可以优化一下。

感谢，很喜欢这个项目，一直很喜欢之前一个临时邮箱界面，花了很多时间没有找到源码，这是我能找得到唯一一个中文还在更新作者友好刚好我还在用cf的相关项目了。加油。

**Comment by dreamhunter2333** [comment]
好的，我看一下怎么取消刷新遮罩

**Comment by dreamhunter2333** [comment]
换成了  axios 并加了 10s 超时的限制，可以再尝试下
