### ISSUE TITLE
[BUG]部署D1数据库时出现问题

### ISSUE THREAD

**Issue by WilliamQAQ0v0** [dreamhunter2333/cloudflare_temp_email#341]
## 复现步骤
按照开发文档部署D1时出现异常 提示no such table: main.mails

## 部署方式
- []  用户界面部署

## 浏览器环境
chrome
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/130297310/7171dde9-28ed-4df8-b0ee-fe2787914f2b)

**Comment by oneisall8955** [comment]
用现在最新的sql 执行即可，https://github.com/dreamhunter2333/cloudflare_temp_email/pull/342 在此次提交修复了

**Comment by WilliamQAQ0v0** [comment]
> 用现在最新的sql 执行即可，#342 在此次提交修复了

okk 感谢

**Comment by WilliamQAQ0v0** [comment]
> 用现在最新的sql 执行即可，#342 在此次提交修复了

但是现在部署会显示DB is not available（？ 已经使用了新的sql

**Comment by dreamhunter2333** [comment]
> > 用现在最新的sql 执行即可，#342 在此次提交修复了
> 
> 但是现在部署会显示DB is not available（？ 已经使用了新的sql

数据库 id 正确么，再尝试下

**Comment by WilliamQAQ0v0** [comment]
> > > 用现在最新的sql 执行即可，#342 在此次提交修复了
> > 
> > 
> > 但是现在部署会显示DB is not available（？ 已经使用了新的sql
> 
> 数据库 id 正确么，再尝试下

我勒个豆 忘了这回事啊啊啊QAQ 谢谢大大
