### ISSUE TITLE
[Feature]一点小想法，希望采纳，不采纳也没关系已经很棒了

### ISSUE THREAD

**Issue by ippinger** [dreamhunter2333/cloudflare_temp_email#343]
首先感谢作者的辛勤付出和无私分享，以及互联网大善人cf的鼎力支持

以下是我的一些想法

1. 是否可以增加一个变量，允许**已注册的用户**获得**没有前缀**的邮箱地址，而**未注册用户**则只能获得**带有前缀**（即变量PREFIX的值）的地址
2. 在有**多个域名**的情况下，只允许**已注册用户**获得特定域名后缀的地址

为啥有这些想法呢，因为在我看来，目前的策略应该是以临时邮箱为主，但另一方面又可以允许注册，那么注册用户应该是想获得一个长久使用的邮箱（起码不像临时邮箱那样用了就扔），所以我想是不是应该把注册用户与未注册用户做一下区分

**Comment by dreamhunter2333** [comment]
1. 这个简单，我加一下
2. 这个我想一下，可以加一下权限

**Comment by ippinger** [comment]
哇大佬真的太好了！我泪目😭
刚才在玩这个webhook功能，因为是菜鸟弄了好久才学会用webhook搭配zapier实现邮件转发

我问ai能不能使用webhook直接将邮件转发到一个指定地址（比如test@gmail.com），ai告诉我这无法实现，因为gmail没有接收webhook的服务器😅

对于用户来说要是可以直接填一个目标收件地址，就可以设置转发这样就方便多了，但是我不懂，感觉就算能实现，应该也会消耗发件额度吧...

**Comment by dreamhunter2333** [comment]
> 哇大佬真的太好了！我泪目😭 刚才在玩这个webhook功能，因为是菜鸟弄了好久才学会用webhook搭配zapier实现邮件转发
> 
> 我问ai能不能使用webhook直接将邮件转发到一个指定地址（比如[test@gmail.com](mailto:test@gmail.com)），ai告诉我这无法实现，因为gmail没有接收webhook的服务器😅
> 
> 对于用户来说要是可以直接填一个目标收件地址，就可以设置转发这样就方便多了，但是我不懂，感觉就算能实现，应该也会消耗发件额度吧...

只能转发到已认证的地址，可以直接使用 cf 的邮件转发或者配置本项目的全局转发 `FORWARD_ADDRESS_LIST`

**Comment by ippinger** [comment]
大佬，`cf 的邮件转发` 这个我理解，

对于`转发到已认证的地址`，如果我没理解错的话，用户只要在CF有一个已经认证的地址，就可以设置转发吗？比如我在CF有一个已认证的地址`verified@gmail.com`，我是否可以设置`tmp123@awsl.uk`转发到`verified@gmail.com`（不通过zapier），如果可以的话，webhook的URL那里填什么呢？

对于`本项目的全局转发`，如果开启，则所有邮件都转发到`FORWARD_ADDRESS_LIST`中的邮箱地址，这样的话相当于把这个站点私有了，其他用户的信件也会转发到List中的地址，对吗？

哈哈，不好意思啊有这么多问题，实在是小白，而且真的很喜欢这个项目

**Comment by dreamhunter2333** [comment]
> FORWARD_ADDRESS_LIST

因为 FORWARD_ADDRESS_LIST 是全局的，所以没有开放给用户，因为此功能对除了 admin 之外的人几乎没有作用

**Comment by ippinger** [comment]
确实，对于临时邮箱来说，目前的功能已经很完善了，再次感谢，大佬早点休息，晚安

**Comment by ippinger** [comment]
omg，真的采纳了，而且这么快就更新了，大佬受我一拜

可是我更新后遇到一个问题，在注册的时候，输入验证码点击注册弹出`400 Invalid role_text`

是我的`USER_ROLES`变量有语法错误吗？还是说应该直接在D1数据库的`user_roles`表添加规则？

以下是我的相关变量，烦请大佬过目：
PREFIX `tmp`
DOMAINS                                 `["default.com" , "vip.com" , "admin.com"]`
DEFAULT_DOMAINS                 `["default.com"]`
USER_DEFAULT_ROLE               `vip`
USER_ROLES `[ 
{ domains = ["default.com" , "vip.com"], role = "vip", prefix = "vip" }, 
{ domains = ["default.com" , "vip.com" , "admin.com], role = "admin", prefix = "" } 
]`

**Comment by dreamhunter2333** [comment]
> omg，真的采纳了，而且这么快就更新了，大佬受我一拜
> 
> 可是我更新后遇到一个问题，在注册的时候，输入验证码点击注册弹出`400 Invalid role_text`
> 
> 是我的`USER_ROLES`变量有语法错误吗？还是说应该直接在D1数据库的`user_roles`表添加规则？
> 
> 以下是我的相关变量，烦请大佬过目： PREFIX `tmp` DOMAINS `["default.com" , "vip.com" , "admin.com"]` DEFAULT_DOMAINS `["default.com"]` USER_DEFAULT_ROLE `vip` USER_ROLES `[ { domains = ["default.com" , "vip.com"], role = "vip", prefix = "vip" }, { domains = ["default.com" , "vip.com" , "admin.com], role = "admin", prefix = "" } ]`

看起来没问题，能看下 admin 后台给用户分配角色是否正常么

**Comment by ippinger** [comment]
有角色这一列，但所有用户的角色的值都为空
并且更改角色下拉框显示：无数据

**Comment by dreamhunter2333** [comment]
> USER_ROLES

看起来是 USER_ROLES 没配置成功，可以查看下后台日志和 worker 的配置

**Comment by ippinger** [comment]
找到问题了，是变量格式错误，我JSON 格式不熟...
尝试将变量值的 `domains` `role` `prefix` 用双引号 " 包围，问题解决

**Comment by dishao123** [comment]
@ippinger 你好，我也遇到了一样的问题，能看一下正确的写法吗？

**Comment by ippinger** [comment]
> @ippinger 你好，我也遇到了一样的问题，能看一下正确的写法吗？

朋友，上边写的很清楚了
