### ISSUE TITLE
用户名邮件没有匹配大小写导致小号邮箱没有正常接收[BUG]

### ISSUE THREAD

**Issue by 666-eth** [dreamhunter2333/cloudflare_temp_email#345]
## 复现步骤
![image](https://github.com/user-attachments/assets/2fb619c6-3e52-4b52-97ee-48e0d3b7d118)

![image](https://github.com/user-attachments/assets/4f72e44e-b10c-49e2-9f05-1c9023ec016a)
![image](https://github.com/user-attachments/assets/5d7aa683-710d-4552-8bb7-059509b5f318)
## 部署方式

- [ ] cli 部署
- [ ]  用户界面部署

**Comment by dreamhunter2333** [comment]
感谢反馈，我想一下怎么修复，邮箱大小写目前是区分的，我考虑下是否全部转为小写来匹配

**Comment by dreamhunter2333** [comment]
## v0.6.0

### Breaking Changes

DB changes: 增加用户角色表, 需要执行 `db/2024-07-14-patch.sql` 更新 `D1` 数据库

### Changes

worker 配置文件新增 `DEFAULT_DOMAINS`, `USER_ROLES`, `USER_DEFAULT_ROLE`, 具体查看文档 [worker配置](https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html#%E4%BF%AE%E6%94%B9-wrangler-toml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

- 移除 `apiV1` 相关代码和相关的数据库表
- 更新 `admin/statistics` api, 添加用户统计信息
- 更新地址的规则，只允许小写+数字，对于历史的地址在查询邮件时会进行 `lowercase` 处理
- 增加用户角色功能，`admin` 可以设置用户角色(目前可配置每个角色域名和前缀)
- admin 页面搜索优化, 回车自动搜索, 输入内容自动 trim

**Comment by 666-eth** [comment]
你太棒了，加油
