### ISSUE TITLE
请问如何配置未登陆用户的可用域名?

### ISSUE THREAD

**Issue by dishao123** [dreamhunter2333/cloudflare_temp_email#354]
我已配置 DEFAULT_DOMAINS 环境变量
DEFAULT_DOMAINS = ["mail.com" , "email.com"]

前台还是显示无数据，是否需要配置 USER_DEFAULT_ROLE 和 USER_ROLES 环境变量。应该怎么做？

**Comment by dreamhunter2333** [comment]
可以f12 看下后台是否返回了 DEFAULT_DOMAINS

**Comment by dishao123** [comment]
> 可以f12 看下后台是否返回了 DEFAULT_DOMAINS

已解决
