### ISSUE TITLE
老哥imap和stmp错误[BUG]

### ISSUE THREAD

**Issue by 666-eth** [dreamhunter2333/cloudflare_temp_email#359]
## 复现步骤

老哥imap和stmp错误
用不了

## 预期行为
![image](https://github.com/user-attachments/assets/7f2cceab-16a6-45f5-98c7-36c733fc3ba8)

**Comment by dreamhunter2333** [comment]
url 配置是否正确，可以先用上个版本的 tag

**Comment by 666-eth** [comment]
docker-compose up -d

docker-compose.yaml 

services:
  smtp_proxy_server:
    image: ghcr.io/dreamhunter2333/cloudflare_temp_email/smtp_proxy_server:latest
    # build:
    #   context: .
    #   dockerfile: dockerfile
    container_name: "smtp_proxy_server"
    ports:
      - "8025:8025"
      - "11143:11143"
    environment:
      - proxy_url=https://worker.aabbcc.com
      - port=8025
      - imap_port=11143

**Comment by 666-eth** [comment]
正确的 哥

**Comment by dreamhunter2333** [comment]
> 正确的 哥

我这测试没啥问题
