### ISSUE TITLE
为啥一直都是405！！！重新部署了还是一样

### ISSUE THREAD

**Issue by Aaron112233499** [dreamhunter2333/cloudflare_temp_email#365]
## 部署方式

- [ ] cli 部署
- [ ]  用户界面部署

**Comment by Aaron112233499** [comment]
https://email1.pages.dev/

**Comment by dreamhunter2333** [comment]
感谢反馈，我看了下
https://mail.quchuguo.net
域名指向的不是 worker

**Comment by Aaron112233499** [comment]
我重新在windows 上搞了一遍好了，对了问问咱那个用户注册是哪个字段啊

**Comment by Aaron112233499** [comment]
好像貌似大概没有收到邮件哎

**Comment by dreamhunter2333** [comment]
> 我重新在windows 上搞了一遍好了，对了问问咱那个用户注册是哪个字段啊

可以查看下worker配置中的变量，有对应说明

**Comment by dreamhunter2333** [comment]
> 好像貌似大概没有收到邮件哎

需要邮件路由中配置 catchall

**Comment by dreamhunter2333** [comment]
如果有任何问题，可重新 open issue
