### ISSUE TITLE
[Feature] 极简最好

### ISSUE THREAD

**Issue by ywgx** [dreamhunter2333/cloudflare_temp_email#368]
比如这样 https://mail.xabc.io

建议哥们, 极简, 去掉 github 链接和版本, 让每个人自己感觉都是自己的

**Comment by dreamhunter2333** [comment]
ok 我加个配置项，默认不显示

**Comment by dreamhunter2333** [comment]
https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.0

v0.7.0: worker 增加 DISABLE_SHOW_GITHUB 配置, 用于配置是否显示 github 链接
