### ISSUE TITLE
请问变量设置

### ISSUE THREAD

**Issue by 404gods** [dreamhunter2333/cloudflare_temp_email#369]
请教大佬，按照文档通过用户界面部署好了，可是访问/admin，密码始终报错，到底要添加哪些变量啊？我已经加了ADMIN_PASSWORDS和PASSWORDS都不行，部署后端的时候没有启用注册用户功能
![image](https://github.com/user-attachments/assets/320bcfab-9ac9-4bd3-bf66-9b70dcd38b36)
还问下，后端触发器里路由一直显示初始化是怎么回事啊？谢谢
![image](https://github.com/user-attachments/assets/baf4dc1b-9e8a-49ae-bfc3-f56733523376)

**Comment by 6aink** [comment]
大佬，请问如何解决的？数组格式怎么设置

**Comment by 6aink** [comment]
看了配置文件懂了 打扰了！

**Comment by dreamhunter2333** [comment]
> 变量已经搞定了，原来是要用数组格式。
> 另外想提个建议
> 我是完全想自用，所以希望能建立一个管理员账号，没有发信等限制，比如我登陆后就是自己的N个子邮箱，可以方便的各自收信回信。

管理员账号这个正在做，main 分支增加了管理员用户直接访问管理员后台的功能， 发信限制这个我也可以加一下

**Comment by dreamhunter2333** [comment]
> > > 变量已经搞定了，原来是要用数组格式。
> 
> > > 另外想提个建议
> 
> > > 我是完全想自用，所以希望能建立一个管理员账号，没有发信等限制，比如我登陆后就是自己的N个子邮箱，可以方便的各自收信回信。
> 
> > 
> 
> > 管理员账号这个正在做，main 分支增加了管理员用户直接访问管理员后台的功能， 发信限制这个我也可以加一下
> 
> 
> 
> 谢谢作者大佬，期待新版本合并。
> 
> 还想问下通过界面部署，每次更新的时候patch.sql、后端worker.js、前端frontend.zip都要更新吗？

前后端每次都要部署，如果需要 patch 会在更新中说明
