### ISSUE TITLE
[Feature]希望Admin路由增加一个无需验证选项

### ISSUE THREAD

**Issue by WowYiJiu** [dreamhunter2333/cloudflare_temp_email#374]
我一般部署的私人网站喜欢接入Cloudflare Access或者Authentik一类的登陆验证，这样就只需要记住一个密码就可以了

**Comment by dreamhunter2333** [comment]
main 分支增加了 admin 角色， 分配到这个角色的用户可以直接访问admin

**Comment by dreamhunter2333** [comment]
v0.7.0: worker 增加 DISABLE_ADMIN_PASSWORD_CHECK 配置, 用于配置是否禁用 admin 控制台密码检查, 若你的网站只可私人访问，可通过此禁用检查

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.0
