### ISSUE TITLE
没有任何报错，但是收不到邮件

### ISSUE THREAD

**Issue by yoghurtlee-thu** [dreamhunter2333/cloudflare_temp_email#376]
如题。部署后使用邮箱进行收件测试，临时邮箱内无法看到任何邮件。CloudFlare Workers 的日志流显示为：

<img width="817" alt="image" src="https://github.com/user-attachments/assets/0a146df2-a432-4b62-8fe4-09f64517d54a">

求大佬解惑。

**Comment by dreamhunter2333** [comment]
感谢反馈，请检查，对应的 cf 页面有邮件的日志

worker 是否配置了 [邮件转发](https://temp-mail-docs.awsl.uk/zh/guide/email-routing.html)

**Comment by yoghurtlee-thu** [comment]
已经解决，感谢大佬。
