### ISSUE TITLE
[BUG]Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by akiker233** [dreamhunter2333/cloudflare_temp_email#377]
### 访问自定义域名
进入/admin，点任意选项卡都显示Cannot read properties of undefined (reading 'map')，创建账户时，后缀显示无数据，控制台无报错

![image](https://github.com/user-attachments/assets/7c1c5839-1c93-4b2d-83e4-283408559a7c)

![image](https://github.com/user-attachments/assets/afff65df-21a7-44e3-a9db-7ac434cc8e14)

### 访问pages自带的域名
进入/admin，提示 t.domains.map is not a function
![image](https://github.com/user-attachments/assets/ca360090-1a07-49f5-aad8-778e00aeb36d)
登录的时候提示Unauthorized, your admin password is wrong，但是密码与后端设置的密码一致

## 预期行为

成功进入后台，创建账户

## 部署方式

- [x]  用户界面部署

## 浏览器环境
Chrome 129

**Comment by dreamhunter2333** [comment]
感谢反馈 可以检查下 https://<worker域名>/open_api/settings 是否返回了 domains 字段

worker 是否配置了
DOMAINS = ["xxx.xxx1" , "xxx.xxx2"] # 你的域名, 支持多个域名

**Comment by akiker233** [comment]
> 感谢反馈 可以检查下 https://<worker域名>/open_api/settings 是否返回了 domains 字段

![image](https://github.com/user-attachments/assets/29ed451a-4cae-4b0c-9d3b-4cb404d558bf)
这样可以吧，我只想搞一个域名，所以就
![image](https://github.com/user-attachments/assets/7b996e02-8fd8-44cd-81f4-9bbcade125c2)

**Comment by dreamhunter2333** [comment]
> > 感谢反馈 可以检查下 https://<worker域名>/open_api/settings 是否返回了 domains 字段
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/29ed451a-4cae-4b0c-9d3b-4cb404d558bf)
> 
> 这样可以吧，我只想搞一个域名，所以就
> 
> ![image](https://github.com/user-attachments/assets/7b996e02-8fd8-44cd-81f4-9bbcade125c2)
> 
> 
> 
> 

需要为一个字符串的数组，需要括号

**Comment by akiker233** [comment]
> > > 感谢反馈 可以检查下 https://<worker域名>/open_api/settings 是否返回了 domains 字段
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/94284604/356073339-29ed451a-4cae-4b0c-9d3b-4cb404d558bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTQyODMsIm5iZiI6MTcyMzA5Mzk4MywicGF0aCI6Ii85NDI4NDYwNC8zNTYwNzMzMzktMjllZDQ1MWEtNGNhZS00YjBjLTlkM2ItNGNiNDA0ZDU1OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA1MTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNzYyY2NhMTM2NTMyMWRlYjg4ZmNkYzEyYjQzMzFiNGY0ZTJmYzYwYmY0ZGMyYzkwNmE2NGUwMjZhMjZlMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X8HjZfVTUYaVmsBGNAhHTE_YV2N9y6bqnK4DfEWJG6k)
> > 这样可以吧，我只想搞一个域名，所以就
> > ![image](https://private-user-images.githubusercontent.com/94284604/356073505-7b996e02-8fd8-44cd-81f4-9bbcade125c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTQyODMsIm5iZiI6MTcyMzA5Mzk4MywicGF0aCI6Ii85NDI4NDYwNC8zNTYwNzM1MDUtN2I5OTZlMDItOGZkOC00NGNkLTgxZjQtOWJiY2FkZTEyNWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA1MTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNmI5ODU5NDgxMjg1NTRjNzcwZmZlZmU0MGMwN2U4OTEzNDcxZmY3YWQyNDA2NjMyNzU0MWEzM2ZkYTM4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.45Pr_3Rpoh0uOyl1vEbf980qh3aeRj20oMAKb5hJSgY)
> 
> 需要为一个字符串的数组，需要括号

好了，但是自定义域名访问还是弹出  Cannot read properties of undefined (reading 'map')
![image](https://github.com/user-attachments/assets/113c6cd5-972d-41b7-9d09-e984a625aadb)

**Comment by dreamhunter2333** [comment]
> > > > 感谢反馈 可以检查下 https://<worker域名>/open_api/settings 是否返回了 domains 字段
> 
> > > 
> 
> > > 
> 
> > > ![image](https://private-user-images.githubusercontent.com/94284604/356073339-29ed451a-4cae-4b0c-9d3b-4cb404d558bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTQyODMsIm5iZiI6MTcyMzA5Mzk4MywicGF0aCI6Ii85NDI4NDYwNC8zNTYwNzMzMzktMjllZDQ1MWEtNGNhZS00YjBjLTlkM2ItNGNiNDA0ZDU1OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA1MTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNzYyY2NhMTM2NTMyMWRlYjg4ZmNkYzEyYjQzMzFiNGY0ZTJmYzYwYmY0ZGMyYzkwNmE2NGUwMjZhMjZlMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X8HjZfVTUYaVmsBGNAhHTE_YV2N9y6bqnK4DfEWJG6k)
> 
> > > 这样可以吧，我只想搞一个域名，所以就
> 
> > > ![image](https://private-user-images.githubusercontent.com/94284604/356073505-7b996e02-8fd8-44cd-81f4-9bbcade125c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTQyODMsIm5iZiI6MTcyMzA5Mzk4MywicGF0aCI6Ii85NDI4NDYwNC8zNTYwNzM1MDUtN2I5OTZlMDItOGZkOC00NGNkLTgxZjQtOWJiY2FkZTEyNWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA1MTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNmI5ODU5NDgxMjg1NTRjNzcwZmZlZmU0MGMwN2U4OTEzNDcxZmY3YWQyNDA2NjMyNzU0MWEzM2ZkYTM4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.45Pr_3Rpoh0uOyl1vEbf980qh3aeRj20oMAKb5hJSgY)
> 
> > 
> 
> > 需要为一个字符串的数组，需要括号
> 
> 
> 
> 好了，但是自定义域名访问还是弹出  Cannot read properties of undefined (reading 'map')
> 
> ![image](https://github.com/user-attachments/assets/113c6cd5-972d-41b7-9d09-e984a625aadb)
> 
> 

改了domains 应该不会出现这种情况了

**Comment by akiker233** [comment]
> 改了domains 应该不会出现这种情况了

清除缓存刷新下可以了，感谢
