### ISSUE TITLE
总开关和黑名单[Feature]

### ISSUE THREAD

**Issue by 666-eth** [dreamhunter2333/cloudflare_temp_email#379]
## 请描述您的 Feature
总开关和黑名单
## 描述您想要的解决方案
后台增加总开关 ， 可以拒绝收取所有信件这样就不浪费worker流量。或者是添加拒绝某个发信人拒收，一天可是收取10w+的垃圾推广邮件。

**Comment by dreamhunter2333** [comment]
感谢反馈，我想下怎么实现

**Comment by 666-eth** [comment]
在数据插入一条 发件人的邮箱， 入站检查一下这个表？

**Comment by dreamhunter2333** [comment]
目前支持关键词屏蔽
可配置 worker 的 BLACK_LIST 变量

**Comment by dreamhunter2333** [comment]
总开关这个我没想明白，用来临时使用么，用的时候再打开收件

**Comment by 666-eth** [comment]
> 总开关这个我没想明白，用来临时使用么，用的时候再打开收件

对的 要用时在打开

**Comment by dreamhunter2333** [comment]
> > 总开关这个我没想明白，用来临时使用么，用的时候再打开收件
> 
> 对的 要用时在打开

OK 我有空加一下，admin 页面可配置开关 + 屏蔽来源地址的关键词列表

**Comment by dreamhunter2333** [comment]
main 分支已增加黑名单
<img width="652" alt="image" src="https://github.com/user-attachments/assets/f9e88d7c-0236-4714-8624-15762632e1c0">

**Comment by 666-eth** [comment]
你是最棒的！！！

**Comment by 666-eth** [comment]
你是最棒的！！！
