### ISSUE TITLE
对中文邮件的支持问题

### ISSUE THREAD

**Issue by sunnywangzi** [dreamhunter2333/cloudflare_temp_email#38]
有些中文邮件会乱码
![Screenshot_20231210_010429](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/88769439/6e916f60-90fb-4397-af50-2222a161cd81)

**Comment by dreamhunter2333** [comment]
已更新新版，我测试没问题，请尝试下中文邮件

**Comment by sunnywangzi** [comment]
感谢，已经可以了
