### ISSUE TITLE
[BUG]求助，自定义域名无法访问

### ISSUE THREAD

**Issue by mmm1h** [dreamhunter2333/cloudflare_temp_email#382]
## 复现步骤
自定义域名无法访问前后端，worker.dev可以访问

## 预期行为
自定义域名可以访问

## 部署方式

- [ ] cli 部署
- [ ✅]  用户界面部署

## 浏览器环境
chrome

**Comment by dreamhunter2333** [comment]
感谢反馈，是否科学上网了呢

**Comment by mmm1h** [comment]
已经科学上网了，在控制台中显示如下
[ warn ][TCP] dial 🎯 全球直连 (match RuleSet/ChinaDomain) 192.168.9.51:4826 --> mail.hmhi.ac.cn:443 error: dns resolve failed: couldn't find ip
