### ISSUE TITLE
[Feature] 启用全局邮件推送WEBHOOK

### ISSUE THREAD

**Issue by wqwwffsytxwp** [dreamhunter2333/cloudflare_temp_email#383]
支持启用全局邮件推送 推送到TG TG在国内通知不是那么及时
系统可以加一个启用全局邮件推送到WEBHOOK 自己配置到飞书机器人
现在只支持一个邮箱一个邮箱配置有点费人

 感谢大佬

**Comment by dreamhunter2333** [comment]
感谢反馈，我有空看下怎么实现
