### ISSUE TITLE
管理员还是不懂

### ISSUE THREAD

**Issue by 404gods** [dreamhunter2333/cloudflare_temp_email#390]
谢谢作者
部署了8月10日的最新版，还是没搞懂怎么设置单独管理员，用户里更改角色内容是空，请问一下：
一、“增加 ADMIN_USER_ROLE 配置, 用于配置管理员用户角色，此角色的用户可访问 admin 管理页面”这一步是变量设置吗？变量值是什么呢？
二、“worker 增加 DISABLE_ADMIN_PASSWORD_CHECK 配置, 用于配置是否禁用 admin 控制台密码检查, 若你的网站只可私人访问，可通过此禁用检查”，这一步也是变量吗？我设置了true没感到变化，还是要点5次输密码进后台。

给个建议，功能逻辑还是太绕了，为什么不像其他的程序一样，变量里（或首次随机）设置个管理员账户密码，管理员账户登陆就是管理员，可以管理其他角色的权限，简单明了。

**Comment by dreamhunter2333** [comment]
DISABLE_ADMIN_PASSWORD_CHECK = TRUE 就没有密码检查了

**Comment by dreamhunter2333** [comment]
目前角色没有在数据库配置，都保存在 worker 的变量中

```
# 用户角色配置, 如果 domains 为空将使用 default_domains
# 如果 prefix 为 null 将使用默认前缀, 如果 prefix 为空字符串将不使用前缀
# USER_ROLES = [
#    { domains = ["xxx.xxx1" , "xxx.xxx2"], role = "vip", prefix = "vip" },
#    { domains = ["xxx.xxx1" , "xxx.xxx2"], role = "admin", prefix = "" },
# ]
```

**Comment by WowYiJiu** [comment]
> 2. DISABLE_ADMIN_PASSWORD_CHECK = TRUE 就没有密码检查了

我重新升级了一下，发现还是需要输入密码

**Comment by dreamhunter2333** [comment]
> 2\. DISABLE_ADMIN_PASSWORD_CHECK = TRUE

配置了这个么

**Comment by dreamhunter2333** [comment]
其实最开始设计的是只需要管理员密码就可以进 admin 页面

**Comment by WowYiJiu** [comment]
> > 2. DISABLE_ADMIN_PASSWORD_CHECK = TRUE
> 
> 配置了这个么

配置了，还是要密码

**Comment by dreamhunter2333** [comment]
> > > 2. DISABLE_ADMIN_PASSWORD_CHECK = TRUE
> 
> > 
> 
> > 配置了这个么
> 
> 
> 
> 配置了，还是要密码

请尝试小写 true

**Comment by WowYiJiu** [comment]
> > > > 2. DISABLE_ADMIN_PASSWORD_CHECK = TRUE
> > 
> > 
> > > 
> > 
> > 
> > > 配置了这个么
> > 
> > 
> > 配置了，还是要密码
> 
> 请尝试小写 true

可以了，就是还会弹出密码框，需要随便输入内容才能进入

**Comment by dreamhunter2333** [comment]
> > > > > 2. DISABLE_ADMIN_PASSWORD_CHECK = TRUE
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 配置了这个么
> > > 
> > > 
> > > 配置了，还是要密码
> > 
> > 
> > 请尝试小写 true
> 
> 可以了，就是还会弹出密码框，需要随便输入内容才能进入

建议检查下  ` ADMIN_PASSWORDS = ["123", "456"]` 的配置是否正确

**Comment by WowYiJiu** [comment]
![登陆页面](https://im.wowyijiu.com/file/4a807859e57db73296eb6.png)
`ADMIN_PASSWORDS`设置不设置都会弹出这个框，`DISABLE_ADMIN_PASSWORD_CHECK = true`设置后应该不弹框才对

**Comment by dreamhunter2333** [comment]
> ![登陆页面](https://im.wowyijiu.com/file/4a807859e57db73296eb6.png)
> 
> `ADMIN_PASSWORDS`设置不设置都会弹出这个框，`DISABLE_ADMIN_PASSWORD_CHECK = true`设置后应该不弹框才对

输入 ADMIN_PASSWORDS 列表中的一个密码也不行么，不应该啊

**Comment by WowYiJiu** [comment]
> > ![登陆页面](https://camo.githubusercontent.com/d989e0ac4191d3efccc1bc3fae4e01526c8c0349e5c5b651898d254e4703f16b/68747470733a2f2f696d2e776f7779696a69752e636f6d2f66696c652f3461383037383539653537646237333239366562362e706e67)
> > `ADMIN_PASSWORDS`设置不设置都会弹出这个框，`DISABLE_ADMIN_PASSWORD_CHECK = true`设置后应该不弹框才对
> 
> 输入 ADMIN_PASSWORDS 列表中的一个密码也不行么，不应该啊

我以为设置`DISABLE_ADMIN_PASSWORD_CHECK = true`后就不会弹框了，目前是设置后会弹框，密码随便输就能进入，我想要的就是不弹框直接进入管理界面

**Comment by dreamhunter2333** [comment]
> DISABLE_ADMIN_PASSWORD_CHECK = true

我测试下，理论上应该不需要弹框

**Comment by dreamhunter2333** [comment]
找到问题了，我修复下

**Comment by dreamhunter2333** [comment]
main 分支已修复

> > > ![登陆页面](https://camo.githubusercontent.com/d989e0ac4191d3efccc1bc3fae4e01526c8c0349e5c5b651898d254e4703f16b/68747470733a2f2f696d2e776f7779696a69752e636f6d2f66696c652f3461383037383539653537646237333239366562362e706e67)
> > > `ADMIN_PASSWORDS`设置不设置都会弹出这个框，`DISABLE_ADMIN_PASSWORD_CHECK = true`设置后应该不弹框才对
> > 
> > 
> > 输入 ADMIN_PASSWORDS 列表中的一个密码也不行么，不应该啊
> 
> 我以为设置`DISABLE_ADMIN_PASSWORD_CHECK = true`后就不会弹框了，目前是设置后会弹框，密码随便输就能进入，我想要的就是不弹框直接进入管理界面

**Comment by dreamhunter2333** [comment]
OK 我有空再测试下，理论上 `DISABLE_ADMIN_PASSWORD_CHECK = true` 后 任何人都能进 amdin，不需要密码

**Comment by dreamhunter2333** [comment]
> > main 分支已修复
> > > > > ![登陆页面](https://camo.githubusercontent.com/d989e0ac4191d3efccc1bc3fae4e01526c8c0349e5c5b651898d254e4703f16b/68747470733a2f2f696d2e776f7779696a69752e636f6d2f66696c652f3461383037383539653537646237333239366562362e706e67)
> > > > > `ADMIN_PASSWORDS`设置不设置都会弹出这个框，`DISABLE_ADMIN_PASSWORD_CHECK = true`设置后应该不弹框才对
> > > > 
> > > > 
> > > > 输入 ADMIN_PASSWORDS 列表中的一个密码也不行么，不应该啊
> > > 
> > > 
> > > 我以为设置`DISABLE_ADMIN_PASSWORD_CHECK = true`后就不会弹框了，目前是设置后会弹框，密码随便输就能进入，我想要的就是不弹框直接进入管理界面
> 
> ![环境变量](https://camo.githubusercontent.com/0e368f543ddc5631ad135c1ec1bd1e15d125c464f6a24c4cdcc6258d38ab0c52/68747470733a2f2f696d2e776f7779696a69752e636f6d2f66696c652f3631303236653761633430303062623562313237362e706e67) 我部署了几遍，在不登录直接访问的情况下仍然会弹框，不过用admin用户没问题

main 分支已更新，可以再尝试下

**Comment by dreamhunter2333** [comment]
# v0.7.3 已发布

- feat: worker 增加 ADDRESS_CHECK_REGEX, address name 的正则表达式, 只用于检查，符合条件将通过检查
- fix: UI 修复登录页面 tab 激活图标错位
- fix: UI 修复 admin 页面刷新弹框输入密码的问题
- feat: support Oath2 登录, 可以通过 Github Authentik 等第三方登录, 详情查看 OAuth2 第三方登录

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.3
