### ISSUE TITLE
[BUG] 管理界面 webhook 白名单列表空

### ISSUE THREAD

**Issue by Ednn0nd1au** [dreamhunter2333/cloudflare_temp_email#392]
## 复现步骤
管理界面 webhook 白名单列表空，但是可以手动输入并确认生效
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/5bbcd9cc-6faf-4273-81a6-a679808903cc">

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

**Comment by dreamhunter2333** [comment]
此处是个输入框，可手动输入地址
