### ISSUE TITLE
[BUG] 邮箱前缀无法加入符号

### ISSUE THREAD

**Issue by Ednn0nd1au** [dreamhunter2333/cloudflare_temp_email#399]
## 复现步骤
邮箱前缀无法使用 `·` 符号，即在创建账号处输入 a.b@test.com，会自动生成 ab@test.com

## 预期行为
生成  a.b@test.com

## 部署方式

- [x] cli 部署
- [ ]  用户界面部署

**Comment by dreamhunter2333** [comment]
这个是设计如此，因为大多数平台会将大小写以及.符号忽略，不同邮箱去掉. 符号以及忽略大小写后会变成同一个邮箱，

所以最终只允许了纯小写字母作为邮箱，后续我可以加个配置项，做成可配置的，但是不同邮箱会冲突这个就不可避免了

**Comment by dreamhunter2333** [comment]
> feature/dev 看到了加入regex，测试完美，谢谢～

赞
