### ISSUE TITLE
环境变量中配置角色似乎没生效

### ISSUE THREAD

**Issue by cachexy123** [dreamhunter2333/cloudflare_temp_email#405]
你好，我在环境变量中配置了角色，但在admin后台更改账号的角色时，显示为空

**Comment by dreamhunter2333** [comment]
感谢反馈，配置是否正确呢，打开 f12，配置角色页面，查看下 network 中 admin/user_roles 是否了返回正确信息

**Comment by cachexy123** [comment]
![image](https://i.sfacg.uk/i/2024/08/14/zpl4zr.png)
返回空...

**Comment by cachexy123** [comment]
![image](https://i.sfacg.uk/i/2024/08/14/zpl4zr.png)

**Comment by cachexy123** [comment]
<img src="https://i.sfacg.uk/i/2024/08/14/zpl4zr.png" alt="image" />
返回空.///

**Comment by cachexy123** [comment]
<img src="https://i.sfacg.uk/i/2024/08/14/10fscys.png" alt="image" />
这是我的环境变量配置

**Comment by dreamhunter2333** [comment]
> ![image](https://camo.githubusercontent.com/77a2f87163b74fc7f0d169a6908d4e92f4aa234bf24bcb5e2e7fb0a2b86690aa/68747470733a2f2f692e73666163672e756b2f692f323032342f30382f31342f313066736379732e706e67)
> 
> 这是我的环境变量配置

你好，这里的图片无法查看

**Comment by cachexy123** [comment]
![image](https://github.com/user-attachments/assets/9f32d7b3-83ba-4d9f-9d28-4d7482253936)

**Comment by dreamhunter2333** [comment]
> ![image](https://private-user-images.githubusercontent.com/44692789/357875859-9f32d7b3-83ba-4d9f-9d28-4d7482253936.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTEzODIsIm5iZiI6MTcyMzY1MTA4MiwicGF0aCI6Ii80NDY5Mjc4OS8zNTc4NzU4NTktOWYzMmQ3YjMtODNiYS00ZDlmLTlkMjgtNGQ3NDgyMjUzOTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE1NTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOWJiNzFlYjE4M2Q2NTQ4N2VmNDliMDU1MmQ4ZjVkMGI0MDk4OWI1Njk5ZTMyOTdiM2VjNzY3OGMwM2FmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zONIubSF6lwqNYhxjjfqFwFGZ-hMcUQRwoJCwGaqBqw)

请问是通过 UI 部署的么，请配置成这种格式试试 [{"domains":["awsl.uk","dreamhunter2333.xyz"],"role":"vip","prefix":"vip"},{"domains":["awsl.uk","dreamhunter2333.xyz"],"role":"admin","prefix":""}]

**Comment by cachexy123** [comment]
> [{"domains":["awsl.uk","dreamhunter2333.xyz"],"role":"vip","prefix":"vip"},{"domains":["awsl.uk","dreamhunter2333.xyz"],"role":"admin","prefix":""}]

对的通过ui, 我试试

**Comment by cachexy123** [comment]
> > > [{"domains":["awsl.uk","dreamhunter2333.xyz"],"role":"vip","prefix":"vip"},{"domains":["awsl.uk","dreamhunter2333.xyz"],"role":"admin","prefix":""}]
> > 
> > 
> > 对的通过ui, 我试试
> 
> 我后续会更新下 UI 部署的文档

可以了, 谢谢!!

**Comment by dreamhunter2333** [comment]
感谢反馈，已增加到文档
https://temp-mail-docs.awsl.uk/zh/guide/ui/worker.html
<img width="750" alt="image" src="https://github.com/user-attachments/assets/d1200a96-0483-4a19-83d7-1a0d0701e451">
