### ISSUE TITLE
"使用 Cloudflare Workers 给已认证的邮箱发送邮件" 看不太明白

### ISSUE THREAD

**Issue by cachexy123** [dreamhunter2333/cloudflare_temp_email#412]
你好, 我根据这里提示
"使用 Cloudflare Workers 给已认证的邮箱发送邮件"
![image](https://github.com/user-attachments/assets/1034f679-b5f4-4fb4-83f4-970e082a8477)
我这里已验证了, 但是这里显示无数据
![image](https://github.com/user-attachments/assets/0c4b7b0d-8688-412f-b102-43b75b9161b5)

**Comment by dreamhunter2333** [comment]
此处为多选输入框，需要手动输入，我之后更改下提示
