### ISSUE TITLE
[BUG]配置Telegram异常

### ISSUE THREAD

**Issue by zhangya4548** [dreamhunter2333/cloudflare_temp_email#413]
## 复现步骤

根据文档通过用户界面部署完成后, 进入后台能正常收邮件, 于是又想启用 Telegram

然后在cf后台又加入了TELEGRAM_BOT_TOKEN环境变量后重新部署了

但是再次刷新进入后台想启用 Telegram还是提示报错,导致不能启用

<img width="1139" alt="Xnip2024-08-15_16-58-08" src="https://github.com/user-attachments/assets/3fdeed41-f13e-49fd-acf9-ff1d61012efe">

<img width="1091" alt="Xnip2024-08-15_16-58-30" src="https://github.com/user-attachments/assets/5ce9563d-4d4a-4a6c-9da8-4892fae8ca18">

## 预期行为

想启用 Telegram

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

**Comment by dreamhunter2333** [comment]
感谢反馈，如果要使用 telegrm bot, 需要在你图片的页面下方绑定 KV，具体配置可参考文档

**Comment by dreamhunter2333** [comment]
KV 的绑定名字需要为 KV
