### ISSUE TITLE
[BUG] ADDRESS_REGEX问题

### ISSUE THREAD

**Issue by ivangreat** [dreamhunter2333/cloudflare_temp_email#414]
## 复现步骤
配置ADDRESS_REGEX，不希望邮箱地址以admin开头，输入^(?!admin).*$后，还是可以创建以admin开头的邮箱，是不支持这种正则么？

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

**Comment by dreamhunter2333** [comment]
目前的正则为 replace 的正则（即不合法的字符会被去掉），我后续增加个校验正则

**Comment by dreamhunter2333** [comment]
# v0.7.3 已发布

- feat: worker 增加 ADDRESS_CHECK_REGEX, address name 的正则表达式, 只用于检查，符合条件将通过检查

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.3

**Comment by ivangreat** [comment]
> # v0.7.3 已发布
> * feat: worker 增加 ADDRESS_CHECK_REGEX, address name 的正则表达式, 只用于检查，符合条件将通过检查
> 
> https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.3

感谢，已测试成功。
