### ISSUE TITLE
当我登录用户时出现500错误

### ISSUE THREAD

**Issue by gedhspace** [dreamhunter2333/cloudflare_temp_email#417]
## 复现步骤

部署完ui后正常登录用户出现500 TypeError Cannot read properties of undefined (reading 'includes')错误

## 预期行为

正常登录用户

## 部署方式

- [ ] cli 部署
- [ +]  用户界面部署

**Comment by gedhspace** [comment]
邮箱地址 https://mailui.pages.dev/

**Comment by Mystic-Stars** [comment]
蹲一个解决方案，我也是这个问题

**Comment by dreamhunter2333** [comment]
可以 f12 看下具体的错误么

**Comment by dreamhunter2333** [comment]
感谢反馈，此处登录的是用户还是邮箱呢

**Comment by Mystic-Stars** [comment]
![image](https://github.com/user-attachments/assets/20a8f43d-7bd8-42e1-893c-95f50ac92075)
用户和邮箱登录都会这样，很多地方都会有这个报错

**Comment by gedhspace** [comment]
![image](https://github.com/user-attachments/assets/65c660b0-4125-410d-ae2c-094a319baff8)
邮箱会这样

**Comment by dreamhunter2333** [comment]
> ![image](https://github.com/user-attachments/assets/20a8f43d-7bd8-42e1-893c-95f50ac92075)
> 
> 用户和邮箱登录都会这样，很多地方都会有这个报错

看起来是后台报错了，能看下 worker 的日志么

**Comment by gedhspace** [comment]
![image](https://github.com/user-attachments/assets/201e258b-3fcc-4908-89f0-162f1ecf94d9)

**Comment by gedhspace** [comment]
试了两次都一样

**Comment by gedhspace** [comment]
![image](https://github.com/user-attachments/assets/d3bcfa16-626b-4bd9-8eed-36f6be23e360)

**Comment by dreamhunter2333** [comment]
JWT_SECRET 配置了么

**Comment by dreamhunter2333** [comment]
> ![image](https://private-user-images.githubusercontent.com/97295993/358835456-20a8f43d-7bd8-42e1-893c-95f50ac92075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDA0NjAsIm5iZiI6MTcyMzkwMDE2MCwicGF0aCI6Ii85NzI5NTk5My8zNTg4MzU0NTYtMjBhOGY0M2QtN2JkOC00MmUxLTg5M2MtOTVmNTBhYzkyMDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDEzMDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTcxNmI3ZmI5Nzc2ZmIzYTU3NjFjYjU0OGU0YjY4ZDczNDExYzQzZDM4NTk3NWNmYzhmOWU3NTE2Zjc0ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDQWJopjJP9jaFBJ2nYwd_8AugIQgQ8IpR4PlBQMIlE) 用户和邮箱登录都会这样，很多地方都会有这个报错

可以检查下 JWT_SECRET 是否配置了
