### ISSUE TITLE
[BUG] DEFAULT_DOMAINS 设置不生效

### ISSUE THREAD

**Issue by LiJunYi2** [dreamhunter2333/cloudflare_temp_email#430]
## 复现步骤
最新版：v0.7.4
`wrangler.toml`中设置`DEFAULT_DOMAINS = []`，`deploy`的时候，控制台显示如下，可以确定DEFAULT_DOMAINS是空的

<img width="672" alt="image" src="https://github.com/user-attachments/assets/8308d556-580d-4311-b56a-000b0c92a361">
 
但是登录`admin`控制台后，又显示是有的：

<img width="419" alt="image" src="https://github.com/user-attachments/assets/184e90a8-2ec1-4570-bf53-4153de392fd0">

## 预期行为

我想通过设置DEFAULT_DOMAINS为空，来限制未登录用户或者未注册用户无法创建临时邮箱。

## 部署方式

- [ ] cli 部署

## 浏览器环境
google

**Comment by dreamhunter2333** [comment]
目前设置为空会自动 fallback 到 domains 的值，我想下怎么限制未登录无法使用

**Comment by dreamhunter2333** [comment]
## v0.7.4

- feat: UI 列表页面增加最小宽度
- fix: 修复 name 的校验检查
- fix: 修复 DEFAULT_DOMAINS 配置为空不生效的问题

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.4

**Comment by LiJunYi2** [comment]
> ## v0.7.4
> * feat: UI 列表页面增加最小宽度
> * fix: 修复 name 的校验检查
> * fix: 修复 DEFAULT_DOMAINS 配置为空不生效的问题
> 
> https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.4

收到收到  感谢大佬

**Comment by LiJunYi2** [comment]
> ## v0.7.4
> * feat: UI 列表页面增加最小宽度
> * fix: 修复 name 的校验检查
> * fix: 修复 DEFAULT_DOMAINS 配置为空不生效的问题
> 
> https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.4

大佬，好像不行，我设置DEFAULT_DOMAINS=[]，DOMAINS设置了域名后，没注册的用户是没法创建邮箱了，但是用户注册完成后登录，去创建新邮箱发现域名下拉框是空的
<img width="913" alt="image" src="https://github.com/user-attachments/assets/196a6edc-7151-4549-88bd-6eb316a2277a">

**Comment by LiJunYi2** [comment]
大佬，这个问题下个版本可以解决吗😁😁

**Comment by dreamhunter2333** [comment]
用户注册后需要分配角色才能创建邮箱

**Comment by dreamhunter2333** [comment]
可以使用默认角色

**Comment by LiJunYi2** [comment]
> 可以使用默认角色

<img width="572" alt="image" src="https://github.com/user-attachments/assets/8e59d16d-0572-4da6-b126-6998b05c7b6d">

大佬，新用户默认角色, 仅在启用邮件验证时有效，然后启用邮件设置那里，没太明白，就比如我系统内有余额的地址如下：
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/b3df09fd-5aaf-496d-8acd-87dadeeedf97">
那我这里启用验证时，是不是可以填这个了：
<img width="680" alt="image" src="https://github.com/user-attachments/assets/b533d2c9-2e1f-411d-96cd-fe97da7c26be">

**Comment by LiJunYi2** [comment]
> 可以使用默认角色

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/7ea65d0a-18b0-47da-8ee2-75467855c754">
大佬，已验证地址列表，这样添加不对吗？
我的`wrangler.toml`已经配置了`send_email`：

```xml
send_email = [
    {name="an***79@bilivo.top"}
]
```

**Comment by dreamhunter2333** [comment]
> > 可以使用默认角色
> 
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/40384503/363822994-7ea65d0a-18b0-47da-8ee2-75467855c754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MjI5OTQtN2VhNjVkMGEtMThiMC00N2RhLThlZTItNzU0Njc4NTVjNzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDQxZDVhNGIwMjgxNmQ0MjFjYzU3Njc2OTQ0OWJlMmI4ZjRhMjIxMGVhYzJhMTM2Yzk5OWQ0YmJmOWJlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZBjfrb9-II3lLtGgStxgjVfcAwKZ43OR6WEpG1ZmaYo"> 大佬，已验证地址列表，这样添加不对吗？ 我的`wrangler.toml`已经配置了`send_email`：
> ```
> send_email = [
>     {name="an***79@bilivo.top"}
> ]
> ```

按照配置文件配置即可，不用填写具体的 name

**Comment by dreamhunter2333** [comment]
> > 可以使用默认角色
> 
> <img alt="image" width="572" src="https://private-user-images.githubusercontent.com/40384503/363811259-8e59d16d-0572-4da6-b126-6998b05c7b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTEyNTktOGU1OWQxNmQtMDU3Mi00ZGE2LWIxMjYtNjk5OGIwNWM3YjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMDg0NjE5NWJhNmViYmZlYmM4NDg4ZWVmNGVjZWNjZDFlYTMxOWZjNWZkMDdjMWFjYjgxN2RmMzVjMjZhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3BMBz-dWKDoNZGq2x7f_bHxzyPD6QtJ034k4g_anroo">
> 大佬，新用户默认角色, 仅在启用邮件验证时有效，然后启用邮件设置那里，没太明白，就比如我系统内有余额的地址如下： <img alt="image" width="1082" src="https://private-user-images.githubusercontent.com/40384503/363811561-b3df09fd-5aaf-496d-8acd-87dadeeedf97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTE1NjEtYjNkZjA5ZmQtNWFhZi00OTZkLThhY2QtODdkYWRlZWVkZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZWY5NDk3NDk1ZWI2MmNkNjFkMzgxODc5ZjhmY2FiNzRmYTExMzA1OWQxMmE3NDgwMWNkMGEwMmYzYmU0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QaYAAjY8a29i-c-vXvLanvjd-99AzEKeVuijS2i9_IA"> 那我这里启用验证时，是不是可以填这个了： <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/40384503/363811643-b533d2c9-2e1f-411d-96cd-fe97da7c26be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTE2NDMtYjUzM2QyYzktMmUxZi00MTFkLTk2Y2QtZmU5N2RhN2MyNmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTYwYjRkZmM0MDY3ZTcwNjVkZWI1MjQ3ZGQxNGNiYjliZmQ3ZWRjNGJjY2I5ZDJkMmVkMzQ1ODQ1ZjI1NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gHBQyrXDCDG3_LNmAoWksvI2FZ4rnPLM7YAQR3Zt4aI">

可以的，验证有效是为了防止攻击，可以后台创建用户并分配角色

**Comment by LiJunYi2** [comment]
> > > 可以使用默认角色
> > 
> > 
> > <img alt="image" width="572" src="https://private-user-images.githubusercontent.com/40384503/363811259-8e59d16d-0572-4da6-b126-6998b05c7b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTEyNTktOGU1OWQxNmQtMDU3Mi00ZGE2LWIxMjYtNjk5OGIwNWM3YjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMDg0NjE5NWJhNmViYmZlYmM4NDg4ZWVmNGVjZWNjZDFlYTMxOWZjNWZkMDdjMWFjYjgxN2RmMzVjMjZhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3BMBz-dWKDoNZGq2x7f_bHxzyPD6QtJ034k4g_anroo">
> > 大佬，新用户默认角色, 仅在启用邮件验证时有效，然后启用邮件设置那里，没太明白，就比如我系统内有余额的地址如下： <img alt="image" width="1082" src="https://private-user-images.githubusercontent.com/40384503/363811561-b3df09fd-5aaf-496d-8acd-87dadeeedf97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTE1NjEtYjNkZjA5ZmQtNWFhZi00OTZkLThhY2QtODdkYWRlZWVkZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZWY5NDk3NDk1ZWI2MmNkNjFkMzgxODc5ZjhmY2FiNzRmYTExMzA1OWQxMmE3NDgwMWNkMGEwMmYzYmU0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QaYAAjY8a29i-c-vXvLanvjd-99AzEKeVuijS2i9_IA"> 那我这里启用验证时，是不是可以填这个了： <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/40384503/363811643-b533d2c9-2e1f-411d-96cd-fe97da7c26be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTE2NDMtYjUzM2QyYzktMmUxZi00MTFkLTk2Y2QtZmU5N2RhN2MyNmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTYwYjRkZmM0MDY3ZTcwNjVkZWI1MjQ3ZGQxNGNiYjliZmQ3ZWRjNGJjY2I5ZDJkMmVkMzQ1ODQ1ZjI1NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gHBQyrXDCDG3_LNmAoWksvI2FZ4rnPLM7YAQR3Zt4aI">
> 
> 可以的，验证有效是为了防止攻击，可以后台创建用户并分配角色

感谢大佬，我还以为是要设置目标地址邮箱才行🤣 还有个问题就是，我成功设置之后，模拟用户注册发生邮件提示`400 Failed to send mail Please enable resend or verified address list`，然后我配置了`RESEND_TOKEN`后就没问题了，这个`RESEND_TOKEN`是必须的吗？

**Comment by dreamhunter2333** [comment]
> > > > 可以使用默认角色
> > > 
> > > 
> > > <img alt="image" width="572" src="https://private-user-images.githubusercontent.com/40384503/363811259-8e59d16d-0572-4da6-b126-6998b05c7b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTEyNTktOGU1OWQxNmQtMDU3Mi00ZGE2LWIxMjYtNjk5OGIwNWM3YjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMDg0NjE5NWJhNmViYmZlYmM4NDg4ZWVmNGVjZWNjZDFlYTMxOWZjNWZkMDdjMWFjYjgxN2RmMzVjMjZhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3BMBz-dWKDoNZGq2x7f_bHxzyPD6QtJ034k4g_anroo">
> > > 大佬，新用户默认角色, 仅在启用邮件验证时有效，然后启用邮件设置那里，没太明白，就比如我系统内有余额的地址如下： <img alt="image" width="1082" src="https://private-user-images.githubusercontent.com/40384503/363811561-b3df09fd-5aaf-496d-8acd-87dadeeedf97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTE1NjEtYjNkZjA5ZmQtNWFhZi00OTZkLThhY2QtODdkYWRlZWVkZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZWY5NDk3NDk1ZWI2MmNkNjFkMzgxODc5ZjhmY2FiNzRmYTExMzA1OWQxMmE3NDgwMWNkMGEwMmYzYmU0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QaYAAjY8a29i-c-vXvLanvjd-99AzEKeVuijS2i9_IA"> 那我这里启用验证时，是不是可以填这个了： <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/40384503/363811643-b533d2c9-2e1f-411d-96cd-fe97da7c26be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTE2NDMtYjUzM2QyYzktMmUxZi00MTFkLTk2Y2QtZmU5N2RhN2MyNmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTYwYjRkZmM0MDY3ZTcwNjVkZWI1MjQ3ZGQxNGNiYjliZmQ3ZWRjNGJjY2I5ZDJkMmVkMzQ1ODQ1ZjI1NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gHBQyrXDCDG3_LNmAoWksvI2FZ4rnPLM7YAQR3Zt4aI">
> > 
> > 
> > 可以的，验证有效是为了防止攻击，可以后台创建用户并分配角色
> 
> 感谢大佬，我还以为是要设置目标地址邮箱才行🤣 还有个问题就是，我成功设置之后，模拟用户注册发生邮件提示`400 Failed to send mail Please enable resend or verified address list`，然后我配置了`RESEND_TOKEN`后就没问题了，这个`RESEND_TOKEN`是必须的吗？

是的，给外部邮箱发邮箱需要的，目前只支持 RESEND

**Comment by LiJunYi2** [comment]
> > > > > 可以使用默认角色
> > > > 
> > > > 
> > > > <img alt="image" width="572" src="https://private-user-images.githubusercontent.com/40384503/363811259-8e59d16d-0572-4da6-b126-6998b05c7b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTEyNTktOGU1OWQxNmQtMDU3Mi00ZGE2LWIxMjYtNjk5OGIwNWM3YjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMDg0NjE5NWJhNmViYmZlYmM4NDg4ZWVmNGVjZWNjZDFlYTMxOWZjNWZkMDdjMWFjYjgxN2RmMzVjMjZhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3BMBz-dWKDoNZGq2x7f_bHxzyPD6QtJ034k4g_anroo">
> > > > 大佬，新用户默认角色, 仅在启用邮件验证时有效，然后启用邮件设置那里，没太明白，就比如我系统内有余额的地址如下： <img alt="image" width="1082" src="https://private-user-images.githubusercontent.com/40384503/363811561-b3df09fd-5aaf-496d-8acd-87dadeeedf97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTE1NjEtYjNkZjA5ZmQtNWFhZi00OTZkLThhY2QtODdkYWRlZWVkZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZWY5NDk3NDk1ZWI2MmNkNjFkMzgxODc5ZjhmY2FiNzRmYTExMzA1OWQxMmE3NDgwMWNkMGEwMmYzYmU0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QaYAAjY8a29i-c-vXvLanvjd-99AzEKeVuijS2i9_IA"> 那我这里启用验证时，是不是可以填这个了： <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/40384503/363811643-b533d2c9-2e1f-411d-96cd-fe97da7c26be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE4ODEsIm5iZiI6MTcyNTM0MTU4MSwicGF0aCI6Ii80MDM4NDUwMy8zNjM4MTE2NDMtYjUzM2QyYzktMmUxZi00MTFkLTk2Y2QtZmU5N2RhN2MyNmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTYwYjRkZmM0MDY3ZTcwNjVkZWI1MjQ3ZGQxNGNiYjliZmQ3ZWRjNGJjY2I5ZDJkMmVkMzQ1ODQ1ZjI1NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gHBQyrXDCDG3_LNmAoWksvI2FZ4rnPLM7YAQR3Zt4aI">
> > > 
> > > 
> > > 可以的，验证有效是为了防止攻击，可以后台创建用户并分配角色
> > 
> > 
> > 感谢大佬，我还以为是要设置目标地址邮箱才行🤣 还有个问题就是，我成功设置之后，模拟用户注册发生邮件提示`400 Failed to send mail Please enable resend or verified address list`，然后我配置了`RESEND_TOKEN`后就没问题了，这个`RESEND_TOKEN`是必须的吗？
> 
> 是的，给外部邮箱发邮箱需要的，目前只支持 RESEND

好滴  感谢大佬
