### ISSUE TITLE
[BUG]地址屏蔽词被绕过

### ISSUE THREAD

**Issue by Sun9220** [dreamhunter2333/cloudflare_temp_email#431]
## 复现步骤
最新版：v0.7.4

在配置以下变量时 会将其他特殊符号给予屏蔽，例如 a-d-m-i-n会被替换成admin

# address name 替换非法符号的正则表达式, 不在其中的符号将被替换，如果不设置，默认为 [^a-z0-9], 需谨慎使用, 有些符号可能导致无法收件
# ADDRESS_REGEX = "[^a-z0-9]"

在Web上配置了
邮件地址屏蔽关键词(管理员可跳过检查)：admin

经过实际测试，如果输入
a-d-m-i-n不会被block，而是会顺利的注册admin关键词的邮件地址

## 预期行为
希望作者看看怎么样修复一下这个bug，邮件地址屏蔽功能很需要

## 部署方式

- [ ]  用户界面部署

## 浏览器环境
Chrome

**Comment by dreamhunter2333** [comment]
ok 我检查下代码，应该替换完在检查是否 block

**Comment by dreamhunter2333** [comment]
# v0.7.4

- feat: UI 列表页面增加最小宽度
- fix: 修复 name 的校验检查
- fix: 修复 DEFAULT_DOMAINS 配置为空不生效的问题

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.4

**Comment by Sun9220** [comment]
我更新到了最新版v0.7.4版本，更新了一下前端和后端。
经过实际测试，屏蔽词被绕过的相关问题似乎还是存在 a-d_min 类似的形式还是会被注册成admin。

**Comment by dreamhunter2333** [comment]
## v0.7.5

- fix: 修复 `name` 的校验检查
