### ISSUE TITLE
垃圾邮件处理 SPF 状态 DMARC 状态 DKIM 状态

### ISSUE THREAD

**Issue by wqwwffsytxwp** [dreamhunter2333/cloudflare_temp_email#435]
是否可以开启一个 SPF 状态 DMARC 状态 DKIM 状态 这三个状态的判断  垃圾邮件基本上DKIM 状态 都是fail 少数 SPF 状态 也是fail

**Comment by wqwwffsytxwp** [comment]
SPF 状态 none

**Comment by zhang-wen-tao** [comment]
可以在cloudflare配置一下
配置后
既可以使用

**Comment by dreamhunter2333** [comment]
目前采用的 https://resend.com/domains 发送，需要参考 resend 的配置，在 worker 这层无法判断

**Comment by dreamhunter2333** [comment]
> f把邮件转发给workers 的时候信息里面会带有SPF 状态 DMARC 状态 DKIM 状态 这三个状态 是否可以根据这个判断邮件拒收

应该可以的，我看一下能不能从邮件 header 取到

**Comment by dreamhunter2333** [comment]
# v0.7.6 已增加

- feat: 支持提前设置 bot info, 降低 telegram 回调延迟 (#441)
- feat: 增加 telegram mini app 的 build 压缩包
- feat: 增加是否启用垃圾邮件检查 ENABLE_CHECK_JUNK_MAIL 配置

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.7.6
