### ISSUE TITLE
[BUG] 部署后端时候提示 DB is not available

### ISSUE THREAD

**Issue by dnslin** [dreamhunter2333/cloudflare_temp_email#436]
## 复现步骤

https://temp-mail.bolekmiss.workers.dev/
![1724746710585.png](https://a1.boltp.com/2024/08/27/66cd8c0f8ffa8.webp)

## 预期行为

![image](https://github.com/user-attachments/assets/9f65354e-575e-48ac-8c0f-1f66d1c0af8b)

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

## 浏览器环境
Chrome latest

**Comment by dreamhunter2333** [comment]
感谢反馈，数据名称需要为 `DB`
![image](https://github.com/user-attachments/assets/c824455e-9b66-483a-9ce5-a999b7262236)

**Comment by dnslin** [comment]
可以了 我在用户界面部署 没看到类似的提示 希望加上方便后续用户

**Comment by dreamhunter2333** [comment]
> 可以了 我在用户界面部署 没看到类似的提示 希望加上方便后续用户

OK
