### ISSUE TITLE
[Feature] 建议在 newTelegramBot 函数内初始化 botInfo，可以节约一次查询

### ISSUE THREAD

**Issue by toadfanszz** [dreamhunter2333/cloudflare_temp_email#441]
## 请描述您的 Feature

telegraf 会在 handleUpdate 内查询一次 getMe()，可以通过设置 botInfo 跳过，回调接口会稍微快一点

https://github.com/dreamhunter2333/cloudflare_temp_email/blob/main/worker/src/telegram_api/index.ts#L35

https://github.com/telegraf/telegraf/blob/v4/src/telegraf.ts#L329-L333

## 描述您想要的解决方案

https://github.com/dreamhunter2333/cloudflare_temp_email/blob/main/worker/src/telegram_api/telegram.ts#L47

这里加入 

bot.botInfo = {...BOT_INFO}

**Comment by dreamhunter2333** [comment]
感谢反馈，我之后加上测试一下

**Comment by dreamhunter2333** [comment]
main 分支已增加
