### ISSUE TITLE
Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by psen888** [dreamhunter2333/cloudflare_temp_email#445]
小白部署有点困难，最后步骤。前端报错Cannot read properties of undefined (reading 'map')麻烦大佬解答下，谢谢

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

**Comment by dreamhunter2333** [comment]
看起来是 worker 后台配置不正确，检查下worker 的配置

**Comment by dreamhunter2333** [comment]
可以 F12 看下 openapi settings api 的返回值

**Comment by hoey94** [comment]
settings 的GET请求发送的有问题，嵌套了两层
@dreamhunter2333 

请求 URL:
https://mail.77558.icu/tmail-worker.2997806434.workers.dev/open_api/settings
GET
200 OK
104.21.58.199:443
strict-origin-when-cross-origin

**Comment by dreamhunter2333** [comment]
> tmail-worker.2997806434.workers.dev/open_api/settings

你发送的这个 url 可以正常使用啊

**Comment by hoey94** [comment]
> > tmail-worker.2997806434.workers.dev/open_api/settings
> 
> 你发送的这个 url 可以正常使用啊 @hoey94

是最新版本的0.8 front有问题，无法与worker通信。 从front发送的api 
https://mail.77558.icu/tmail-worker.2997806434.workers.dev/open_api/settings
期望是：
https://tmail-worker.2997806434.workers.dev/open_api/settings

**Comment by dreamhunter2333** [comment]
> > > tmail-worker.2997806434.workers.dev/open_api/settings
> > 
> > 
> > 你发送的这个 url 可以正常使用啊 @hoey94
> 
> 是最新版本的0.8 front有问题，无法与worker通信。 从front发送的api https://mail.77558.icu/tmail-worker.2997806434.workers.dev/open_api/settings 期望是： https://tmail-worker.2997806434.workers.dev/open_api/settings
> 
> 部署front 0.7.6版本没问题

检查下 front 的url 配置，第一个看起来是配置的时候没加 `https://` 前缀导致的

**Comment by dreamhunter2333** [comment]
检查下 front 的后端 url 配置，第一个看起来是配置的时候没加 https:// 前缀导致的
