### ISSUE TITLE
[BUG]使用API key发送邮件配置Resend三方账号被封禁

### ISSUE THREAD

**Issue by hongchen-coder** [dreamhunter2333/cloudflare_temp_email#446]
## 复现步骤
使用API key发送邮件配置Resend三方账号被封禁

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

**Comment by dreamhunter2333** [comment]
感谢反馈 resend 有 给出封禁理由么

**Comment by hongchen-coder** [comment]
就是添加了一下域名，使用api key发送一次邮件就给封了

**Comment by dreamhunter2333** [comment]
发送的邮件是营销内容么，可能不符合要求

**Comment by hongchen-coder** [comment]
就一个测试邮件，可能是某些后缀的域名不允许吧

**Comment by dreamhunter2333** [comment]
> 就一个测试邮件，可能是某些后缀的域名不允许吧

可能，我这两个域名每遇到过
