### ISSUE TITLE
[BUG]邮箱地址凭据

### ISSUE THREAD

**Issue by zy111x** [dreamhunter2333/cloudflare_temp_email#451]
pages配置好进去出现了这个，邮箱地址凭据是啥？是我变量没配置吗（纯小白）
![image](https://github.com/user-attachments/assets/2a34782f-6f8e-4869-b8f9-2dba4e56d29d)

**Comment by dreamhunter2333** [comment]
需要允许邮箱注册，注册后就有登录凭据了
