### ISSUE TITLE
[BUG]怎么绑定自己生成的邮箱

### ISSUE THREAD

**Issue by zy111x** [dreamhunter2333/cloudflare_temp_email#453]
## 复现步骤

按照文档部署

## 预期行为
正常接收到邮件

## 部署方式

- [ ] cli 部署
[ ]  用户界面部署

## 浏览器环境
![image](https://github.com/user-attachments/assets/a4ca056a-ec65-497a-a86d-4f9a6a455f50)
为什么邮件都在这里，不在下面的页面，是我没绑定吗？怎么操作呀
![image](https://github.com/user-attachments/assets/7776fe85-0db2-43df-a084-aafb88fa1ee4)

**Comment by dreamhunter2333** [comment]
admin 页面是全部邮件，你的这个用户并没收到邮件
