### ISSUE TITLE
[BUG]配置完全不能发送邮件

### ISSUE THREAD

**Issue by zy111x** [dreamhunter2333/cloudflare_temp_email#455]
## 预期行为
正常发送文件

## 部署方式

- [ ] cli 部署
- [ 1]  用户界面部署

## 浏览器环境
api也申请了，变量也配置了，还是无法发送邮件
![image](https://github.com/user-attachments/assets/e6133eed-9de9-478e-ae64-4bed5f006b3a)

**Comment by zy111x** [comment]
> ## 复现步骤
> ## 预期行为
> 正常发送文件
> 
> ## 部署方式
> * [ ] CLI 部署
> * [ 1]  用户界面部署
> 
> ## 浏览器环境
> api也申请了，变量也配置了，还是无法发送邮件 ![image](https://private-user-images.githubusercontent.com/150530845/371763701-e6133eed-9de9-478e-ae64-4bed5f006b3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MzM2ODIsIm5iZiI6MTcyNzUzMzM4MiwicGF0aCI6Ii8xNTA1MzA4NDUvMzcxNzYzNzAxLWU2MTMzZWVkLTlkZTktNDc4ZS1hZTY0LTRiZWQ1ZjAwNmIzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQxNDIzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWNlMzZiNWViYjY4YzQzMDYxMDg2MmZiNGI2NjNhZWYwOGM1YWEwN2E3OTQ0MDliNTdmODExZmJmZWFiZGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YA-wroZ8__SCvwtfQRAG9hNaTVR7Ml8WTmCnCUNaT4U)

![image](https://github.com/user-attachments/assets/557d039f-eb92-43f9-84b8-280581d8c8cc)
![image](https://github.com/user-attachments/assets/21706ffb-c6e6-41f2-b5c4-60c26e349471)

**Comment by dreamhunter2333** [comment]
可以去发件权限后台查看和修改发件余额

**Comment by zy111x** [comment]
感谢已解决❤
