### ISSUE TITLE
[BUG]点击”查看邮箱凭证“时出现Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by Stfrostec** [dreamhunter2333/cloudflare_temp_email#458]
## 复现步骤
在创建邮箱账号时显示
400 Failed create address: Cannot read properties of undefined (reading 'includes')
但是创建完成
之后点击查看邮箱地址凭证出现
500 TypeError Cannot read properties of undefined (reading 'includes')
请问这是什么原因

## 预期行为
success

## 部署方式

- [ ] cli 部署
- [√]  用户界面部署

查阅文档部署，部分界面显示与实际有些出入，不清楚是否正确
打开 worker 的 url，显示 OK

**Comment by dreamhunter2333** [comment]
感谢反馈，是否配置了JWT_SECRET呢

**Comment by Stfrostec** [comment]
感谢提醒，我没创建密钥，才导致这个问题，在看文档的时候我注意到了这个是和用户登录有关，没想到也与生成邮箱地址凭证有关，所以没有配置

**Comment by dreamhunter2333** [comment]
是的，这个会用来生成很多认证相关的凭证
