### ISSUE TITLE
Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by chenb1522** [dreamhunter2333/cloudflare_temp_email#460]
## 复现步骤
跟着教程一步步搞的, 其中后端和前端都配置了自定义域, 前端的代码文件中也是配置的后端的自定义域.
worker 也绑定了变量 DOMAINS, 但还是报了下面这个错误.
![PixPin_2024-10-09_10-28-41](https://github.com/user-attachments/assets/c73a430f-2709-41fb-b77f-d86590f4f226)

https://<自定义worker域名>/open_api/settings 都正确返回了

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

## 浏览器环境
Edge 129.0.2792.79

**Comment by dreamhunter2333** [comment]
前端的 url 配置正确么，看起来没访问到 worker

**Comment by chenb1522** [comment]
> 前端的 url 配置正确么，看起来没访问到 worker

配置了,  配的是后端的自定义域地址

**Comment by dreamhunter2333** [comment]
> > 前端的 url 配置正确么，看起来没访问到 worker
> 
> 
> 
> 配置了,  配的是后端的自定义域地址

那不应该啊 F12 查看api 的返回值也正确么

**Comment by chenb1522** [comment]
> 我这里也遇到了，F12查看后，请求后端api接口的时候多了一层前端的域名： ![image](https://private-user-images.githubusercontent.com/9927734/379211983-cdac0e46-a01a-443a-be49-12fd32a14e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Nzc3NTMsIm5iZiI6MTcyOTY3NzQ1MywicGF0aCI6Ii85OTI3NzM0LzM3OTIxMTk4My1jZGFjMGU0Ni1hMDFhLTQ0M2EtYmU0OS0xMmZkMzJhMTRlNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDk1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVkNGNjZDk5MzU4ODAyYTZiYzM1M2Q4ODkwOTU2ZmIwNzA1M2I3MjFhMDRmMTI5OTdhZGNkYTQzMTczNzc2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4UjEEKH77tHSjPX2fFgquNgohavSo6vL8Lk-D3i2V04)
> 
> 使用cf的域名是正常的。

我开无痕模式或者浏览器强制刷新缓存就又可以了, 但是一旦关闭无痕或者每次不强制刷新就又会出现这个问题

**Comment by dreamhunter2333** [comment]
可以 f12 清理下缓存
