### ISSUE TITLE
[Feature] Please support Cloudflare Zero Trust - Access

### ISSUE THREAD

**Issue by catfishlty** [dreamhunter2333/cloudflare_temp_email#465]
## 请描述您的 Feature
能够更好的支持 Cloudflare Zero Trust - Access的保护功能

目前采用Pages代理Worker流量部署项目，前置增加Cloudflare Zero Trust保护。
如果初次登录网站（获取清理浏览器该网站数据）能正常先跳转到Zero Trust的登录页。
但是如果Zero Trust登录过期后访问网站，会有报错页面提示`Network Error`，抓包里面显示部分请求会403。

## 描述您想要的解决方案
个人猜测可能为浏览器缓存导致的问题，浏览器直接从缓存获取到网站页面，所以在Zero Trust过期的时候还是能访问到页面。
希望能解决Zero Trust的跳转问题。

**Comment by dreamhunter2333** [comment]
感谢反馈，应该是是缓存的问题，我考虑做个是否启用缓存的开关

**Comment by dreamhunter2333** [comment]
有空尝试下 https://github.com/dreamhunter2333/cloudflare_temp_email/pull/477 这个分支，我测试没问题

**Comment by catfishlty** [comment]
好的，这么快就搞定了，我这几天有空试试
顺便问一下如果关闭缓存，是不是对页面加载有影响？

**Comment by dreamhunter2333** [comment]
> 好的，这么快就搞定了，我这几天有空试试
> 
> 顺便问一下如果关闭缓存，是不是对页面加载有影响？

就不使用浏览器缓存了，会慢一点点，不过比起来后台 api 的速度，九牛一毛了

**Comment by catfishlty** [comment]
我测试了，没问题，感谢支持这个Feature
