### ISSUE TITLE
[BUG]Uncaught Error: No such module "node:stream". imported from "worker.js"

### ISSUE THREAD

**Issue by 666-eth** [dreamhunter2333/cloudflare_temp_email#475]
## 复现步骤

老大
最新的 worker.js 部署失败哦

## 预期行为

![image](https://github.com/user-attachments/assets/b8699ac7-decb-444a-a516-bd94bf3e3724)

**Comment by dreamhunter2333** [comment]
OK 我测试下，不应该啊

**Comment by dreamhunter2333** [comment]
CF 更新了 UI 部署需要手动在设置修改此处，我后续增加到文档

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/5e6e7c96-d11b-4efe-87a8-e1e6b1f93ff2">

**Comment by dreamhunter2333** [comment]
UI 部署需要手动在设置修改此处，已加到文档
https://temp-mail-docs.awsl.uk/zh/guide/ui/worker.html

**Comment by 666-eth** [comment]
搞定 谢谢大佬
