### ISSUE TITLE
[BUG]不能改网页图标（logo）吗

### ISSUE THREAD

**Issue by youyi0218** [dreamhunter2333/cloudflare_temp_email#478]
## 复现步骤
我把pages中的frontend.zip的logo.png换成了我自己的图片（500*500px），名字还是叫logo.png，但是上传到pages发现那个图标还是默认的图片
![image](https://github.com/user-attachments/assets/9e27d909-74a9-4fae-b0c6-f95e88b5438c)

## 预期行为
这个东西不应该替换成了我自己的了吗，为什么还是这个东西（

**Comment by youyi0218** [comment]
我试着在本地启动一个html服务，发现这个图标有更改啊，为什么上传到pages上面就变回去了？（

**Comment by dreamhunter2333** [comment]
可以在无痕模式测试下

**Comment by dreamhunter2333** [comment]
这就奇怪了，可以查看下 pages 的部署记录，确定下是生产环境不

**Comment by dreamhunter2333** [comment]
已经移除网页的所有缓存功能，可以有空再尝试
