### ISSUE TITLE
[BUG]生成随机名字会大于地址长度

### ISSUE THREAD

**Issue by longsays** [dreamhunter2333/cloudflare_temp_email#480]
## 复现步骤
设置**MAX_ADDRESS_LEN = 8**
生成随机名字会大于地址长度
![image](https://i0.du0.org/i/2024/11/13/sljxgs.webp)

**另前台页面的时区是否可以加个选项自定义现在的时区还要自己换算,有点麻烦**

**Comment by dreamhunter2333** [comment]
感谢反馈，我加一下

**Comment by dreamhunter2333** [comment]
v0.8.0

- feat: |UI| 随机生成地址时不超过最大长度
- feat: |UI| 邮件时间显示浏览器时区，可在设置中切换显示为 UTC 时间
- feat: 支持转移邮件到其他用户，参考  [转移邮件到其他用户](https://github.com/dreamhunter2333/cloudflare_temp_email/pull/484)

[更新或者部署网页不生效请如图勾选清理缓存](https://github.com/dreamhunter2333/cloudflare_temp_email/discussions/487)

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.8.0
