### ISSUE TITLE
[BUG]Network Error和Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by XokoukioX** [dreamhunter2333/cloudflare_temp_email#481]
WORKERS配置如下
![屏幕截图 2024-11-14 161906](https://github.com/user-attachments/assets/bf1cd7fb-0b39-423e-922f-258629d73ac0)
WORKERS地址：https://[mail-api.shirasuazusa.workers.dev](https://mail-api.shirasuazusa.workers.dev/)/

前端修改域名如下
![image](https://github.com/user-attachments/assets/fe00f32a-b7cc-48f0-90a7-f2f5b2047d9a)
控制台：
![image](https://github.com/user-attachments/assets/30bd4de9-d2d9-4887-b5a4-773ec19f9343)

打开绑定域名显示
![image](https://github.com/user-attachments/assets/6eddfb6a-6c4c-4f51-b310-55da53e00362)

打开自带域名显示
![image](https://github.com/user-attachments/assets/4169fed7-1086-4fc3-9c91-66d96d6b3dcc)
控制台域名：
![image](https://github.com/user-attachments/assets/79f17a4b-23eb-4023-8087-d8e5abba4ef2)

PS：除了这个域名其他的都无法使用（重新部署了一个版本域名为：https://b94731b2.mail-fronted.pages.dev/）

e.g.这是另外的PAGES域名：
![image](https://github.com/user-attachments/assets/4782188e-4f92-4927-b46f-31ca8b8fd48e)

请求大佬协助，不管怎么修改index.js它就是会默认读取不知道从哪里来的temp-email.xxx域名

- [ ] cli 部署
- [X ]  用户界面部署

## 浏览器环境
Edge 版本 130.0.2849.80 (正式版本) (64 位)

**Comment by dreamhunter2333** [comment]
清理缓存或者无痕模式打开下，我打开你发的链接是可以正常使用的

**Comment by XokoukioX** [comment]
> 清理缓存或者无痕模式打开下，我打开你发的链接是可以正常使用的

大佬，这个问题已经解决了 但是现在有一个新的问题
![image](https://github.com/user-attachments/assets/dc17755b-28c1-4f4d-9ac3-efffdef65531)
![image](https://github.com/user-attachments/assets/894215e1-918a-484c-8540-bef3e218fb4c)
![image](https://github.com/user-attachments/assets/7aee3faa-bb51-44eb-9493-e8ecb9520315)
![image](https://github.com/user-attachments/assets/d48c2d12-6566-4572-91d5-f43b0bb57288)
![image](https://github.com/user-attachments/assets/0e5275ee-3d94-4ccb-ac52-db368331bb01)

这些是我在CF中配置的路由设置 但是我尝试向*@0061226.xyz发送信件的时候收到了退件
![image](https://github.com/user-attachments/assets/d467f2e4-907b-4660-8959-b2f6ab5d01c6)
![image](https://github.com/user-attachments/assets/9b3dfb9d-9c89-4700-9434-3c7520c3a734)

请问这是在哪个地方出现了问题，如果还需要更多信息，请告诉我 我将尽快提供 谢谢

**Comment by XokoukioX** [comment]
感谢 是自己没有正确理解配置文档导致Worker变量没有配置正确，问题已经解决
