### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gdtiti** [dreamhunter2333/cloudflare_temp_email#490]
## 复现步骤

创建完临时邮箱以后或者获取邮箱地址凭证时 都会提示 jwk 错误

类似

500 DataError HMAC "jwk" key import requires a JSON Web Key with Key Type parameter ("kty") equal to "oct" (encountered "undefined").

## 部署方式

用户界面部署

**Comment by dreamhunter2333** [comment]
是否配置了 JWT_SECRET 呢

**Comment by dreamhunter2333** [comment]
需要配置了 JWT_SECRET 呢，JWT_SECRET 不要有特殊符号啥的
