### ISSUE TITLE
[Feature]有发件权限的账户增加转发邮件功能

### ISSUE THREAD

**Issue by FreeyW** [dreamhunter2333/cloudflare_temp_email#492]

**Comment by dreamhunter2333** [comment]
v0.8.1

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.8.1

- feat: |Doc| 更新 UI 安装的文档
- feat: |UI| 对用户隐藏邮箱账号的 ID
- feat: |UI| 增加邮件详情页的 转发 按钮

[更新或者部署网页不生效请如图勾选清理缓存](https://github.com/dreamhunter2333/cloudflare_temp_email/discussions/487)
