### ISSUE TITLE
[BUG] 400 KV required

### ISSUE THREAD

**Issue by Linon419** [dreamhunter2333/cloudflare_temp_email#493]
## 复现步骤
命令行绑定kv后，还提示400 KV is required

<img width="802" alt="Screenshot 2024-11-22 at 09 24 05" src="https://github.com/user-attachments/assets/ed1266f3-112d-4f38-bee9-af31a157505a">
<img width="997" alt="Screenshot 2024-11-22 at 09 24 21" src="https://github.com/user-attachments/assets/aa347bdf-47fb-459f-9999-b690745e04b1">

<img width="455" alt="Screenshot 2024-11-22 at 09 24 41" src="https://github.com/user-attachments/assets/5f3e87a8-b3e6-4c06-a20b-ad7e17f19dea">

## 预期行为
正常使用telegram bot

## 部署方式

- [x] cli 部署
- []  用户界面部署

## 浏览器环境
chrome

**Comment by dreamhunter2333** [comment]
KV 绑定名称需要为 KV

**Comment by Linon419** [comment]
> KV 绑定名称需要为 KV

文档写的是`wrangler kv:namespace create DEV`

**Comment by dreamhunter2333** [comment]
> > KV 绑定名称需要为 KV
> 
> 文档写的是`wrangler kv:namespace create DEV`

文档已更新，创建的 kv 名字不重要，关键是绑定名称需要 为 `KV`
