### ISSUE TITLE
[这个什么原因]

### ISSUE THREAD

**Issue by koi-pig** [dreamhunter2333/cloudflare_temp_email#497]
![image](https://github.com/user-attachments/assets/471f3ce0-3f3c-42cd-a0a4-114493dd6363)

**Comment by dreamhunter2333** [comment]
感谢反馈，提示是没启用发件功能 
参考 https://temp-mail-docs.awsl.uk/zh/guide/config-send-mail.html

**Comment by koi-pig** [comment]
这个描述的不是很清楚

**Comment by koi-pig** [comment]
![image](https://github.com/user-attachments/assets/d27bb43b-c32c-4a80-a40b-08baff71d561)
解析已经添加到cf了，但是不知道为啥这边老是失败，然后我继续点重试

**Comment by dreamhunter2333** [comment]
需参阅 resend 文档配置
