### ISSUE TITLE
[BUG] o.domains is undefined

### ISSUE THREAD

**Issue by seriaati** [dreamhunter2333/cloudflare_temp_email#506]
## 复现步骤
照著文檔的每個步驟操作進行後端及前端設置
前往前端網站，跳出 o.domains is undefined 錯誤
（已確認 Variables & Secrets 帶有 DOMAINS 參數）
![image](https://github.com/user-attachments/assets/00e83afb-db89-4a0d-a574-9dba84809866)

![image](https://github.com/user-attachments/assets/1ab5d257-2aca-499d-a780-32c42e165a56)
（創建郵箱時沒有域名）

## 预期行为
...

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

## 浏览器环境
Firefox 132.0.1

**Comment by dreamhunter2333** [comment]
感谢反馈，可以 F12 查看下 api 请求的是否为后端地址么

**Comment by seriaati** [comment]
@dreamhunter2333 是

**Comment by dreamhunter2333** [comment]
> @dreamhunter2333 是

open_api/settings 返回的 json 中 `defaultDomains` 或者 `domains` 正确么

**Comment by seriaati** [comment]
@dreamhunter2333 
open_api/settings 返回的是一個 HTML
![image](https://github.com/user-attachments/assets/19e7035c-45dc-43b3-b777-a1d40d205b94)

**Comment by seriaati** [comment]
@dreamhunter2333 搞錯地址了，域名確實在裡面
![image](https://github.com/user-attachments/assets/8bf50c6c-db5d-4a11-97d3-27b005ba8b7b)

**Comment by dreamhunter2333** [comment]
> @dreamhunter2333 open_api/settings 返回的是一個 HTML ![image](https://private-user-images.githubusercontent.com/61446626/392152422-19e7035c-45dc-43b3-b777-a1d40d205b94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODQzODcsIm5iZiI6MTczMzI4NDA4NywicGF0aCI6Ii82MTQ0NjYyNi8zOTIxNTI0MjItMTllNzAzNWMtNDVkYy00M2IzLWI3NzctYTFkNDBkMjA1Yjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAzNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYjY5MzA1MDA0ZTY5NWVjYzY4MjZmZTU4ZDJiOGE1YjU2NDRmNjgzMjk2ZTYwNDU5OWQzNWUxMmFkNWIwODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o8-8IEjJS-K_rjX2rWGEcROEcwci8nJS43mvf06hqQg)

看起来是后端地址配置错了，改成正确的还有错误么

**Comment by seriaati** [comment]
@dreamhunter2333 
> 看起来是后端地址配置错了，改成正确的还有错误么
  
我的前端是照著文檔配置的
![image](https://github.com/user-attachments/assets/871df9b9-63ce-4dbc-9096-5313e2298adb)
訪問 https://cloudflare-temp-mail.seria-ati.workers.dev/open_api/settings 可以獲取到 JSON 回應
但是在前端按 F12 檢查的話，會發現它請求了 https://temp-mail.seria.moe/cloudflare-temp-mail.seria-ati.workers.dev/open_api/settings
  
我的前端網址是 https://temp-mail.seria.moe
後端是 https://cloudflare-temp-mail.seria-ati.workers.dev

**Comment by dreamhunter2333** [comment]
> @dreamhunter2333
> 
> > 看起来是后端地址配置错了，改成正确的还有错误么
> 
> 我的前端是照著文檔配置的 ![image](https://private-user-images.githubusercontent.com/61446626/392266799-871df9b9-63ce-4dbc-9096-5313e2298adb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTUzOTQsIm5iZiI6MTczMzMxNTA5NCwicGF0aCI6Ii82MTQ0NjYyNi8zOTIyNjY3OTktODcxZGY5YjktNjNjZS00ZGJjLTkwOTYtNTMxM2UyMjk4YWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEyMjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NGVlOGMyOWFlZmQzNjNkZGMyZTFkM2FkMGY1NTk3ZDBhMTM5OGY3OWYyOTA3NTE2ZDdjNjNmYzIyYTY5MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MYwT3TBN1VeiNxR3aeIvynvLcPqPb8cJbQJqZV9W42M) 訪問 https://cloudflare-temp-mail.seria-ati.workers.dev/open_api/settings 可以獲取到 JSON 回應 但是在前端按 F12 檢查的話，會發現它請求了 https://temp-mail.seria.moe/cloudflare-temp-mail.seria-ati.workers.dev/open_api/settings
> 
> 我的前端網址是 https://temp-mail.seria.moe 後端是 https://cloudflare-temp-mail.seria-ati.workers.dev
> 
> 更新： 很奇怪，使用 pages 給的預設網址 https://cloudflare-temp-mail.pages.dev/ 就正常 使用我自己的域名 https://temp-mail.seria.moe 就請求到了錯誤的後端網址 ![image](https://private-user-images.githubusercontent.com/61446626/392268598-7a8ce14c-9952-49d9-8973-75d15ca7af8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTUzOTQsIm5iZiI6MTczMzMxNTA5NCwicGF0aCI6Ii82MTQ0NjYyNi8zOTIyNjg1OTgtN2E4Y2UxNGMtOTk1Mi00OWQ5LTg5NzMtNzVkMTVjYTdhZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEyMjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTlmNjczNDk0ODA5MDUxNGVkYjQxNmZmMWUyM2MwYzg5YzA1MTdlYzkzNzdmNjEzNmI0NzhlNzIwNWQ4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pDPj3HN8pahfQXlqqQuq43tJN-bc5ZU7Oe2sJEZsJ8w)

请清除浏览器缓存再尝试，我这打开的你的网页都正常

**Comment by seriaati** [comment]
我這裡也都正常了，感謝幫助
