### ISSUE TITLE
Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by PIKACHUIM** [dreamhunter2333/cloudflare_temp_email#51]
提示：Cannot read properties of undefined (reading 'map')
获取新邮箱提示的后缀是：test.com，不是自己设置的

**Comment by PIKACHUIM** [comment]
Request failed with status code 500

**Comment by PIKACHUIM** [comment]
可能是域名问题，换成cf提供的，现在报错：
timeout of 10000ms exceeded

**Comment by PIKACHUIM** [comment]
已解决，配置问题

**Comment by dreamhunter2333** [comment]
test.com 是前端写的一个默认值，
赞，最终解决了

**Comment by PIKACHUIM** [comment]
感谢解答，具体原因是cf那边的MX记录设置包含了别的邮局地址的情况下，会导致邮件路由默认关闭（虽然是启用的子域名，但是主域名关闭了子域名也不可用）
