### ISSUE TITLE
[Feature]能做个本地历史记录吗

### ISSUE THREAD

**Issue by Zding89** [dreamhunter2333/cloudflare_temp_email#511]
## 请描述您的 Feature
不注册的情况下，随机了邮箱后，凭证能保存在本地电脑
那样能重新打开后，能通过历史记录列表找回之前的邮箱

**Comment by dreamhunter2333** [comment]
目前有历史记录，主页可以切换
<img width="1127" alt="image" src="https://github.com/user-attachments/assets/87056af6-1d84-4475-88cc-663328535a57">
