### ISSUE TITLE
[BUG] No domains found, please check your worker settings

### ISSUE THREAD

**Issue by 2754026865** [dreamhunter2333/cloudflare_temp_email#512]
## 问题
![image](https://github.com/user-attachments/assets/f42d5595-1b8b-4344-9c0d-c3e1c53f1114)
页面报错，不能注册账号，不能登录
##验证
1.后端正确两个地址都返回“ok”
![image](https://github.com/user-attachments/assets/37b584a6-fcc1-4317-aa9e-6845fc323d44)

## 预期行为
能够正常显示页面，但是现在报错

## 部署方式

- [ ]  用户界面部署

## 浏览器环境
edge

**Comment by dreamhunter2333** [comment]
感谢反馈，看起来 worker 的变量未配置 domains
参考

Settings -> Variables, 如图所示添加变量，参考 [修改 wrangler.toml 配置文件](https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html#%E4%BF%AE%E6%94%B9-wrangler-toml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 中的 [vars] 部分


https://temp-mail-docs.awsl.uk/zh/guide/ui/worker.html

**Comment by dreamhunter2333** [comment]
> 1.您那个平台 ![image](https://private-user-images.githubusercontent.com/95633655/392710637-69d7c426-7cff-46b3-be2f-696cf404169b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODk3MzIsIm5iZiI6MTczMzM4OTQzMiwicGF0aCI6Ii85NTYzMzY1NS8zOTI3MTA2MzctNjlkN2M0MjYtN2NmZi00NmIzLWJlMmYtNjk2Y2Y0MDQxNjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NzdhYjdhODBiYTg5Mzc2YmEyOGY5NmVhM2Q0NzVlMGZkOTFlZGFkOGFlZDQ1N2NkYjhkNjQ0MDhkYjRjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5aAEtAduLJzU4bN3BcBMee98_BwDH3PWBQhbJWum_B0) 2.我刚刚自己按照教程搭的 ![image](https://private-user-images.githubusercontent.com/95633655/392710816-1ac28bcb-064e-4030-b143-0c9c5c96a95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODk3MzIsIm5iZiI6MTczMzM4OTQzMiwicGF0aCI6Ii85NTYzMzY1NS8zOTI3MTA4MTYtMWFjMjhiY2ItMDY0ZS00MDMwLWIxNDMtMGM5YzVjOTZhOTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNWQwNTJkMWMxYzNiZDE3ODcxMmMzZjI1Y2Q0MWJhYmYzOGRjMDRkNDE0YmYyMmM2MzBkOWVmZTYwYjZiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FUdhj1hprc9F3E3zTW_fq_lryFOSv2DXqmkMqZ2dgYE) 这多多少少不一样吧，我哪里配得不对😭

worker 变量中需要配置允许创建邮箱，创建邮箱之后就可以正常使用了，
可以到 cf 的这个页面查看

<img width="855" alt="image" src="https://github.com/user-attachments/assets/a5375ffc-bd86-4b1c-a059-5d82d521a6e6">

**Comment by dreamhunter2333** [comment]
> 我在变量中添加了呀 ![image](https://private-user-images.githubusercontent.com/95633655/392740337-5d21fb6a-d88a-4eb5-8d23-9632f735b570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTExMzUsIm5iZiI6MTczMzM5MDgzNSwicGF0aCI6Ii85NTYzMzY1NS8zOTI3NDAzMzctNWQyMWZiNmEtZDg4YS00ZWI1LThkMjMtOTYzMmY3MzViNTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNzIzYTk5MWM5Y2NhMDg4YTBlMDA0OTg3NzkzYTg2NmY0NTg1OTM4OWI4MTFiYjcyNWI5ZjJkNzdiNjI0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iViWxivQM1uhGTmIwqi7s_4lZcVtg8M39d_24sEA7vs)

拼写错误了，true.
