### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hixcao** [dreamhunter2333/cloudflare_temp_email#513]

**Comment by hixcao** [comment]
![Snipaste_2024-12-06_00-45-47](https://github.com/user-attachments/assets/13e4fcf5-6d25-47b4-a674-d33915ab1217)

**Comment by hixcao** [comment]
重置D1和kv都不行，是什么原因？大佬？还是TG机器人最多只支持绑定5个邮箱？
![Snipaste_2024-12-06_00-46-39](https://github.com/user-attachments/assets/6033f35e-04b9-44cd-baed-fd27f3334002)

**Comment by dreamhunter2333** [comment]
worker 变量中配置 TG_MAX_ADDRESS 即可

参考 https://temp-mail-docs.awsl.uk/zh/guide/ui/worker.html
