### ISSUE TITLE
[BUG]今天登录后台收不到邮件

### ISSUE THREAD

**Issue by 666-eth** [dreamhunter2333/cloudflare_temp_email#514]
## 复现步骤

![image](https://github.com/user-attachments/assets/76c022df-789c-4505-85ad-3e897b1a82b1)

这是啥错误呢

**Comment by 666-eth** [comment]
我发送邮件给 域名邮箱 
由于系统缺少电子邮件地址xxx@xxxxx.xxx ，或该地址无法接收邮件，因此无法阻止您的邮件。

**Comment by dreamhunter2333** [comment]
感谢反馈，解决了吗
