### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by didingqd** [dreamhunter2333/cloudflare_temp_email#516]
## 复现步骤
按照所有步骤进行，最后GitHub action并没有工作（使用`Deploy with workers`）
![image.png](https://img.yd6.us.kg/file/1733729030314_image.png)
![image.png](https://img.yd6.us.kg/file/1733729031149_image.png)

## 预期行为

正常部署

## 部署方式

- [x]  用户界面部署

## 浏览器环境
edge和Google

**Comment by dreamhunter2333** [comment]
部署是手动的，打开仓库的 Actions 页面，找到 Deploy Backend Production 和 Deploy Frontend，点击 Run workflow 选择分支手动部署

https://temp-mail-docs.awsl.uk/zh/guide/github-action.html

**Comment by didingqd** [comment]
哦哦，谢谢你！那这个`deploy with workers`不是能直接删掉了吗？有点误导啊

**Comment by dreamhunter2333** [comment]
> 哦哦，谢谢你！那这个`deploy with workers`不是能直接删掉了吗？有点误导啊

确实有点误导，我看看改下文档
