### ISSUE TITLE
[BUG] Telegram bot bind error: bind adress count reach the limit

### ISSUE THREAD

**Issue by catfishlty** [dreamhunter2333/cloudflare_temp_email#517]
## 复现步骤
在Telegram Bot 中输入 `/bind <Token>`，返回 `绑定失败: 绑定地址数量已达上限`
目前该账号已经绑定5个地址，再新增绑定的时候会出现该问题，对于 Telegram Bot 绑定的地址有上限吗？

## 预期行为
成功绑定

## 部署方式

- [x] cli 部署
- [ ]  用户界面部署

**Comment by dreamhunter2333** [comment]
参考文档

```
# telegram bot 最多绑定邮箱数量
# TG_MAX_ADDRESS = 5
```

https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html

**Comment by catfishlty** [comment]
我的问题。。。没看到这个配置
