### ISSUE TITLE
[BUG]500 Failed to send verify code: No balance

### ISSUE THREAD

**Issue by LFMJUN** [dreamhunter2333/cloudflare_temp_email#518]
## 复现步骤
我刚才弄了一个noreply@xxxx.xxx用于邮件验证，用户绑定邮箱，用户为admin用户组，NO_LIMIT_SEND_ROLE是admin，发件箱也显示99999，但是注册时验证还是显示No balance
![image](https://github.com/user-attachments/assets/03a514d0-0e09-46c9-ae9b-95c968dae7f8)
如果给其设置发件余额就正常
![image](https://github.com/user-attachments/assets/54997f6d-3f60-4402-85ee-b989db9514ad)

## 预期行为
不设置发件余额，也应该可以直接发送邮件

## 部署方式

- [ ] cli 部署
- [x]  用户界面部署

## 浏览器环境
EDGE

**Comment by dreamhunter2333** [comment]
系统自动发件的时候没绑定到用户，可以暂时修改余额来发件

我看下怎么实现不限制某些邮箱的发件
