### ISSUE TITLE
[BUG] 输入正确密码依然无法登录admin 

### ISSUE THREAD

**Issue by jacklilyhello** [dreamhunter2333/cloudflare_temp_email#529]
## 复现步骤
按照教程部署之后, 尝试登录管理 /admin ， 输入了正确的密码，但是依然显示 Unauthorized, your admin password is wrong ，
<img width="505" alt="截屏2024-12-25 14 54 48" src="https://github.com/user-attachments/assets/1591bce8-0791-4f9f-a960-c0a2d5d131f7" />
尝试改密码和更换浏览器, F12 控制台中未报错

## 预期行为
正常登录admin 

## 部署方式

- [ ] cli 部署
- [*]  用户界面部署

## 浏览器环境
Chrome 
版本 131.0.6778.205

先祝福作者大大圣诞快乐, 麻烦作者大大抽空回复

**Comment by dreamhunter2333** [comment]
是的 `["123456"]` 这么填写

**Comment by jacklilyhello** [comment]
> admin使用`ADMIN_PASSWORDS` 完整示例 `ADMIN_PASSWORDS = ["123456"]` 值里面的括号引号不要丢了

感谢, 成功了

**Comment by jacklilyhello** [comment]
> 是的 `["123456"]` 这么填写

谢谢作者大大提醒, 
一个小建议, 可以在文档中间写上,值里面的括号引号不要丢
再次感谢
