### ISSUE TITLE
出现错误【400 JWT_SECRET is not set】

### ISSUE THREAD

**Issue by didingqd** [dreamhunter2333/cloudflare_temp_email#530]
这个`400 JWT_SECRET is not set`是什么部署错误导致的？
我是完全按照文档根据`通过用户界面部署`进行的
是哪一步出错了吗？
![image.png](https://img.yd6.us.kg/file/1735138046909_image.png)

**Comment by dreamhunter2333** [comment]
到 worker 的设置中的变量里，增加JWT_SECRET变量，值需要自己设置

**Comment by didingqd** [comment]
好的

**Comment by didingqd** [comment]
又出现新的错误【Network Error】，这是为啥
![image.png](https://img.02261004.xyz/file/1735188273595_image.png)

**Comment by dreamhunter2333** [comment]
> 又出现新的错误【Network Error】，这是为啥 ![image.png](https://camo.githubusercontent.com/7ce9ae35dafbf19dce88bc39db89f10ffae482491b310a2f7ad6395feafa6658/68747470733a2f2f696d672e30323236313030342e78797a2f66696c652f313733353138383237333539355f696d6167652e706e67)

f12 network 页面 的 fetch 中检查后台地址是否正确，
域名正确但是，不能访问可能是需要科学上网

**Comment by didingqd** [comment]
我已经检查并将后台地址修改正确然后重新部署，仍然报错， fetch 中检查后台地址并未修改过来，是因为缓存的原因吗

**Comment by dreamhunter2333** [comment]
> 然后我更换域名重新访问，后台地址已更改过来，但出现了新的错误【No domains found, please check your worker settings】
domains 变量没设置导致的
>  fetch 中检查后台地址并未修改过来
需要清理浏览器缓存

### [更新或者部署网页不生效请如图勾选清理缓存](https://github.com/dreamhunter2333/cloudflare_temp_email/discussions/487)

![image](https://github.com/user-attachments/assets/b6ec233d-ae77-4dfb-8124-2f9f98d4a110)

**Comment by didingqd** [comment]
原来如此，我是直接看的UI部署，在那上面没提示，所以就不知道，现在知道了
