### ISSUE TITLE
[Feature]增加用户自己设置垃圾邮件拦截等级

### ISSUE THREAD

**Issue by longsays** [dreamhunter2333/cloudflare_temp_email#531]
现在默认的拦截等级根本拦不住(只拦截失败的)
`DMARC 状态
none
SPF 状态
none
DKIM 状态
none`
![Screenshot_2024-12-26-08-10-09-623_com android chrome-edit](https://github.com/user-attachments/assets/29b97843-c23c-4b35-b7a4-64847a7755ec)

希望可以增加一个验证通过，两个验证通过，全部通过的选项
如果能自己指定验证哪些就更好了，不行的话至少要有一个验证成功

**Comment by dreamhunter2333** [comment]
有道理，我之后增加成可配置的

**Comment by dishao123** [comment]
你好，请问一下图片里的页面，在哪里打开？

**Comment by dreamhunter2333** [comment]
> 你好，请问一下图片里的页面，在哪里打开？

cf 邮件转发的日志

**Comment by dishao123** [comment]
> > 你好，请问一下图片里的页面，在哪里打开？
> 
> cf 邮件转发的日志

谢谢

**Comment by dreamhunter2333** [comment]
main 分支已增加，之后会发到下个版本，目前可以通过 cli 部署

**Comment by dreamhunter2333** [comment]
- feat: 垃圾邮件检测增加存在时才检查的列表 `JUNK_MAIL_CHECK_LIST` 配置
- feat: 增加垃圾邮件检测必须通过的列表 `JUNK_MAIL_FORCE_PASS_LIST` 配置
