### ISSUE TITLE
[BUG]Telgram Bot获取邮件失败：400：Bad Request:BUTTON_URL_INVALID

### ISSUE THREAD

**Issue by sundys** [dreamhunter2333/cloudflare_temp_email#532]
后台添加了token,用户ID，及电脑报小程序的minapp的地址，初始化后，进bot机器人绑定邮箱，其它功能都正常，就是查看绑定的邮件就出现错误，凭证都绑定没有错误。求解

**Comment by dreamhunter2333** [comment]
minapp 地址正确么，需要在 telegam 里注册成 mini app

**Comment by dreamhunter2333** [comment]
> > minapp 地址正确么，需要在 telegam 里注册成 mini app
> > 注册后的地址：https://t.me/xxxbot/mailtemp
> > 这样是正确的吗?

这个地址只能在使用，只需要注册就可以。
admin 网页中填写的地址还是你部署的 mini app 的网页地址

**Comment by dreamhunter2333** [comment]
> > > > minapp 地址正确么，需要在 telegam 里注册成 mini app
> > > > 注册后的地址：https://t.me/xxxbot/mailtemp
> > > > 这样是正确的吗?
> > 
> > 
> > 这个地址只能在 telegram 使用，只需要注册就可以。 admin 网页中填写的地址还是你部署的 mini app 的网页地址
> 
> 好的，搞定了，原来是填写works的地址就行了。感谢

应该是 pages 的地址 😄
