### ISSUE TITLE
无法附加USER_ROLES

### ISSUE THREAD

**Issue by didingqd** [dreamhunter2333/cloudflare_temp_email#535]
不知道为啥，总是无法让这个`USER_ROLES`生效
![image.png](https://img.yd6.us.kg/file/1735290358121_image.png)
![image.png](https://img.yd6.us.kg/file/1735290141340_image.png)

**Comment by dreamhunter2333** [comment]
https://temp-mail-docs.awsl.uk/zh/guide/ui/worker.html

<img width="742" alt="image" src="https://github.com/user-attachments/assets/1fc0142e-c873-488c-9719-26282f6f6bd7" />

**Comment by didingqd** [comment]
哦哦，这格式是真严格。
这个`发件权限控制`为啥什么都没有啊？
![image.png](https://img.yd6.us.kg/file/1735301258439_image.png)
![image.png](https://img.yd6.us.kg/file/1735301107678_image.png)
