### ISSUE TITLE
请问能否支持显示和下载附件

### ISSUE THREAD

**Issue by lifeafter619** [dreamhunter2333/cloudflare_temp_email#56]

**Comment by lifeafter619** [comment]
还有就是对400,401错误能否加入提示
比如输入了错误的管理员密钥，加入一个提示，而不仅仅是顶上的错误码提示

**Comment by lifeafter619** [comment]
还有请问下前端部署完后，cloudflare上是部署到预览环境，那怎样把前端页面绑定到自己的域名上呢（绑在pages里只能是生产环境才可以）

**Comment by dreamhunter2333** [comment]
> 还有请问下前端部署完后，cloudflare上是部署到预览环境，那怎样把前端页面绑定到自己的域名上呢（绑在pages里只能是生产环境才可以）

预览环境，是新建的时候选择生产环境的时候没有输入 production

**Comment by dreamhunter2333** [comment]
> 还有就是对400,401错误能否加入提示 比如输入了错误的管理员密钥，加入一个提示，而不仅仅是顶上的错误码提示

好的，这个可以加一下

**Comment by dreamhunter2333** [comment]
已增加，有个问题是免费版解析不了大附件

<img width="1215" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/9780e6e0-93d7-4ee8-b5d2-a5bbfd3afbc7">
<img width="1135" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/853e7f8c-8a42-48af-8859-ede862184150">

**Comment by lifeafter619** [comment]
请问这个提交改了数据库，原来部署的怎样更新？_(:з」∠)_

**Comment by dreamhunter2333** [comment]
> 请问这个提交改了数据库，原来部署的怎样更新？_(:з」∠)_

https://github.com/dreamhunter2333/cloudflare_temp_email/blob/main/db/2024-01-13-path.sql

**Comment by dreamhunter2333** [comment]
几百KB 的大附件现在也可以了
<img width="906" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/f2a9371c-7f15-49a6-8b19-c46739f1c8f2">
