### ISSUE TITLE
接收不到邮件

### ISSUE THREAD

**Issue by 1137882300** [dreamhunter2333/cloudflare_temp_email#60]
我按照你的方式部署好了，但是接收不到邮件。请问还有什么需要处理的吗？

**Comment by dreamhunter2333** [comment]
email 路由是否配置了呢
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/0e53344b-dfa2-4407-9720-19cef582b8f4)

**Comment by dreamhunter2333** [comment]
wrangler tail cloudflare_temp_email

这个命令可以查看实时日志，可以先运行这个命令，然后发一份邮件测试

**Comment by 1137882300** [comment]
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/44225966/d08fde4d-3fdc-454d-b5ca-f07c025a9071)
email 路由配置了
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/44225966/6ff0807a-e5e2-4644-8536-cf1bd5983df0)

**Comment by 1137882300** [comment]
> wrangler tail cloudflare_temp_email
> 
> 这个命令可以查看实时日志，可以先运行这个命令，然后发一份邮件测试

执行命令之后，发送邮件，没有反应，然后过一会就会断开
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/44225966/2a97ecf7-f45a-4ba8-b074-c8bfe05a0476)

**Comment by dreamhunter2333** [comment]
> > wrangler tail cloudflare_temp_email
> > 这个命令可以查看实时日志，可以先运行这个命令，然后发一份邮件测试
> 
> 执行命令之后，发送邮件，没有反应，然后过一会就会断开 ![image](https://private-user-images.githubusercontent.com/44225966/297232580-2a97ecf7-f45a-4ba8-b074-c8bfe05a0476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDMzMzcsIm5iZiI6MTcwNTUwMzAzNywicGF0aCI6Ii80NDIyNTk2Ni8yOTcyMzI1ODAtMmE5N2VjZjctZjQ1YS00YmE4LWIwNzQtYzhiZmUwNWEwNDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE0NTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzQ3YWE0OGZkM2Y4ZmRmMzcyZGMzYTNmNWNkNzgxZDdiYWY2YmFjYzMyYTRmMWQyZGIxZWY3MTM0YTUzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GpPN5ISneEoYuUQJcMZQnmnohKLCIEkSIul1YsHaYhA)

看起来是网络问题，尝试全局vpn试试

**Comment by dreamhunter2333** [comment]
或者你可以到这个网页查看
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/360d043d-8e3f-438b-8a68-69cc4bf8b374)

**Comment by GGBondOk** [comment]
> 在将电子邮件地址绑定到您的 Worker 之前，您需要启用电子邮件路由并拥有至少一个经过验证的电子邮件地址

我也遇到了楼主一样的情况，配置也一样，不明白这句话什么意思，能否用大白话解释下呀
