### ISSUE TITLE
部署一直失败是什么原因呢

### ISSUE THREAD

**Issue by wuzheng2012** [dreamhunter2333/cloudflare_temp_email#64]
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/152124743/96dd9842-e431-42be-ab22-a97b3345fcd4)
部署一直提示这个是什么原因呢

**Comment by dreamhunter2333** [comment]
是否创建 d1 数据库了呢

**Comment by dreamhunter2333** [comment]
<img width="899" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/855d1c82-3e00-4c7f-b918-16cac09475e8">
