### ISSUE TITLE
QQ邮箱发邮件收不到

### ISSUE THREAD

**Issue by wind-hx** [dreamhunter2333/cloudflare_temp_email#70]
<img width="1098" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/17685971/50157caf-3ae2-4a9c-b19d-82b8cdc07cc1">
<img width="1260" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/17685971/7c4524e5-f11a-4148-bb9a-eb4dbf9d0fca">

**Comment by dreamhunter2333** [comment]
其他邮箱的可以收到吗，这里配置了Catch-All 了吗

<img width="1233" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/5f5ab842-ebba-4a28-ad41-8c1e7a654916">

**Comment by denvey** [comment]
状态一直是这样，请问什么原因呢
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/4018120/e78c699d-4020-40cd-8527-69a8c49e3007)

**Comment by dreamhunter2333** [comment]
看起来没启用成功，上面添加个目标地址试试

**Comment by dreamhunter2333** [comment]
在将电子邮件地址绑定到您的 Worker 之前，您需要启用电子邮件路由并拥有至少一个经过验证的电子邮件地址
