### ISSUE TITLE
Catch-all 地址 状态 一直在加载，收不到邮件

### ISSUE THREAD

**Issue by liyao1520** [dreamhunter2333/cloudflare_temp_email#72]
<img width="1326" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/76561071/0e2cfd53-0c17-43b0-8098-1f72182cd239">

**Comment by liyao1520** [comment]
已解决：添加个目标地址就行了

**Comment by caixiaomao** [comment]
> 已解决：添加个目标地址就行了

请问在哪添加？

**Comment by caixiaomao** [comment]
@liyao1520 请问在哪添加

**Comment by dreamhunter2333** [comment]
应该是认证个转发邮件的目的地吧
