### ISSUE TITLE
部署成功，但是用不了

### ISSUE THREAD

**Issue by afycn** [dreamhunter2333/cloudflare_temp_email#73]
帮忙查看一下什么问题https://2e669be1.mail-10f.pages.dev

**Comment by dreamhunter2333** [comment]
https://2e669be1.mail-10f.pages.dev/ 

这个打不开

**Comment by afycn** [comment]
> https://2e669be1.mail-10f.pages.dev/ 
> 
> 
> 
> 这个打不开

我删了，想重新部署一下看看，重新部署需要删除什么吗

**Comment by dreamhunter2333** [comment]
> > https://2e669be1.mail-10f.pages.dev/
> > 这个打不开
> 
> 我删了，想重新部署一下看看，重新部署需要删除什么吗

不需要，重新部署就行
