### ISSUE TITLE
部署成功了,但是蛮多坑的

### ISSUE THREAD

**Issue by Micah123321** [dreamhunter2333/cloudflare_temp_email#76]
教程不完善,希望优化下教程
我的成功部署地址 : https://ftmail.535888.xyz/

**Comment by dreamhunter2333** [comment]
好哥哥能说下哪些地方有问题吗

**Comment by jamosnet** [comment]
1. 不设置 ADMIN_PASSWORDS。就无法访问管理页面
2. 不能删除邮件，不能删除附件
3. 用户可以创建临时邮箱，但是没有删除临时邮箱的功能

**Comment by dreamhunter2333** [comment]
> 1. 不设置 ADMIN_PASSWORDS。就无法访问管理页面
> 2. 不能删除邮件，不能删除附件
> 3. 用户可以创建临时邮箱，但是没有删除临时邮箱的功能

第一个这个是设计成这样的，其他两项暂时还在思考解决办法

**Comment by jamosnet** [comment]
> > 1. 不设置 ADMIN_PASSWORDS。就无法访问管理页面
> > 2. 不能删除邮件，不能删除附件
> > 3. 用户可以创建临时邮箱，但是没有删除临时邮箱的功能
> 
> 第一个这个是设计成这样的，其他两项暂时还在思考解决办法

设计是合理的，赞同。觉得需要在说明里写一下，毕竟新手不读源码是无法发现这个问题的

**Comment by dreamhunter2333** [comment]
已添加删除功能

**Comment by dreamhunter2333** [comment]
删除已添加，文档已更新
