### ISSUE TITLE
cloudflare部署后更改自定义域名失效

### ISSUE THREAD

**Issue by link0518** [dreamhunter2333/cloudflare_temp_email#77]
正常解析dns但是域名不生效，不确定是cf问题还是项目的设置问题，cloudflare分配的域名是被墙的，有成功更换自定义域名的吗

**Comment by dreamhunter2333** [comment]
vpn 访问正常么

**Comment by link0518** [comment]
> vpn 访问正常么

正常的，原域名是有效的

**Comment by dreamhunter2333** [comment]
这不太清楚了，我绑定的自定义域名

**Comment by ZhouBinxin** [comment]
是部署的问题吗，开始按教程里走的话是一个预览

**Comment by dreamhunter2333** [comment]
> 是部署的问题吗，开始按教程里走的话是一个预览

<img width="632" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/6de8ce5e-dff9-4ed6-93f6-d3fccb486230">
