### ISSUE TITLE
所属域名不存在，邮件无法送达。 No Mx Record Found

### ISSUE THREAD

**Issue by liuyesblog** [dreamhunter2333/cloudflare_temp_email#8]
按教程完成了搭建，获取临时地址什么的都正常，但是用QQ邮箱发邮件秒拒，我看域名的MX记录也自动加上了，请问可能是哪里还有问题呢？感谢回复：）

**Comment by dreamhunter2333** [comment]
邮件路由是否配置了 catch all 呢
![image](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/0bf34de7-4e10-4d58-a6dd-f6ebc37bea66)

**Comment by dreamhunter2333** [comment]
如果配置没问题，此处可以查询日志
<img width="1087" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/245ee38b-4b7d-4612-bdd3-c95c0167c798">

**Comment by liuyesblog** [comment]
> 邮件路由是否配置了 catch all 呢 ![image](https://user-images.githubusercontent.com/32295532/263597856-0bf34de7-4e10-4d58-a6dd-f6ebc37bea66.png)

已经配置了，实时日志没有任何输出

方便给一下DNS的解析看看吗？

**Comment by liuyesblog** [comment]
![QQ截图20230828142344](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/130069000/2ad03a44-7cc9-47e9-9732-110011f3827d)
看退信的结果好像是MX记录不生效，但我去CF看了DNS解析，已经自动生成了三条MX记录和一条TXT记录了

**Comment by dreamhunter2333** [comment]
DNS 是电子邮件路由中一键配置的，有尝试其他邮箱吗
<img width="835" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/7f5163b0-4bc0-440d-82f3-b75e1fdcef7e">


> > 邮件路由是否配置了 catch all 呢 ![image](https://user-images.githubusercontent.com/32295532/263597856-0bf34de7-4e10-4d58-a6dd-f6ebc37bea66.png)
> 
> 已经配置了，实时日志没有任何输出
> 
> 方便给一下DNS的解析看看吗？

**Comment by liuyesblog** [comment]
> DNS 是电子邮件路由中一键配置的，有尝试其他邮箱吗 <img alt="image" width="835" src="https://user-images.githubusercontent.com/32295532/263611394-7f5163b0-4bc0-440d-82f3-b75e1fdcef7e.png">
> 
> > > 邮件路由是否配置了 catch all 呢 ![image](https://user-images.githubusercontent.com/32295532/263597856-0bf34de7-4e10-4d58-a6dd-f6ebc37bea66.png)
> > 
> > 
> > 已经配置了，实时日志没有任何输出
> > 方便给一下DNS的解析看看吗？

也尝试了outlook邮箱，一样的错误，只是提示不太一样，我试一下gmail

**Comment by dreamhunter2333** [comment]
`wrangler tail cloudflare_temp_email` 可以看详细日志，发送前先执行

**Comment by liuyesblog** [comment]
找到错误了，我部署的问题，生成的临时域名多了一位数字，感谢感谢

**Comment by wuzhongyi1105** [comment]
@liuyesblog 你好，我遇到了和您一样的问题，请问是哪里出错了呢？

**Comment by dreamhunter2333** [comment]
> @liuyesblog 你好，我遇到了和您一样的问题，请问是哪里出错了呢？

需要在对应域名的电子邮件路由中启用，并选择电子邮件 worker

**Comment by liuyesblog** [comment]
> @liuyesblog 你好，我遇到了和您一样的问题，请问是哪里出错了呢？

我好像是域名拼错啦
