### ISSUE TITLE
太久没更新（版本停留在去年），是不是无法直接更新到最新版本？

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#89]
大佬！
请问我太久没更新了～版本号都还停留在去年的版本，今天更新到最新版本一直报错，说jet错误或网络错误、Request failed with status code 500。
是不是没办法直接更新到最新版，要重建一个了呢？

**Comment by xiewei3536** [comment]
已解决，原来是数据库新版的表结构与旧版的不一致造成500 error。

**Comment by dreamhunter2333** [comment]
> 已解决，原来是数据库新版的表结构与旧版的不一致造成500 error。

我后面加一下 REAMDE
