### ISSUE TITLE
pnpm run deploy执行完毕后都是预览

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#9]
想问大佬这个怎么解决

**Comment by xiewei3536** [comment]
<img width="449" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/54cfa491-ca1a-4257-965a-7489c708d19b">

**Comment by xiewei3536** [comment]
**已解决，谢谢大佬**
另外希望能加入自定义前缀就更完美了

**Comment by dreamhunter2333** [comment]
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/29998329/264228012-54cfa491-ca1a-4257-965a-7489c708d19b.png">

应该是创建的时候选生产分支没选对

**Comment by dreamhunter2333** [comment]
> **已解决，谢谢大佬** 另外希望能加入自定义前缀就更完美了

目前可以通过 toml 自定义前缀的
