### ISSUE TITLE
能否在管理员面板，账号部份加入搜索功能，这样查找历史邮箱的登入密码方便一些

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#91]
感谢
另外请教unknown的用途是？

**Comment by dreamhunter2333** [comment]
我有空加一下搜索功能，
unknown 是查询系统未注册/已删除邮箱的邮件

**Comment by dreamhunter2333** [comment]
已添加
<img width="1243" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/486693b8-830b-42fe-88f8-0d9c79b47ceb">
