### ISSUE TITLE
注册mega.nz无法收到验证邮件

### ISSUE THREAD

**Issue by xiewei3536** [dreamhunter2333/cloudflare_temp_email#97]
大佬，发现新的问题！！
注册mega.nz无法收到验证邮件
请大佬看看是哪部份有问题，谢谢

**Comment by dreamhunter2333** [comment]
免费版解析不了大的邮件
<img width="1081" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/52c9fdc8-e811-46fd-b3f0-b7ae190bc025">

**Comment by xiewei3536** [comment]
> 免费版解析不了大的邮件，这个目前没啥解决办法，或者做成离线解析/前端解析
> 
> 如果邮件有附件的话，可以尝试去掉这部分代码
> 
> https://github.com/dreamhunter2333/cloudflare_temp_email/blob/9ce706fad1753707ba34fdae8313c1305fbf9696/worker/src/email.js#L82-L102
> 
> <img alt="image" width="1081" src="https://private-user-images.githubusercontent.com/32295532/319469181-52c9fdc8-e811-46fd-b3f0-b7ae190bc025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTQyNjksIm5iZiI6MTcxMjIxMzk2OSwicGF0aCI6Ii8zMjI5NTUzMi8zMTk0NjkxODEtNTJjOWZkYzgtZTgxMS00NmZkLWIzZjAtYjdhZTE5MGJjMDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA2NTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YzQyMjgzNWU4MDM1NDc4ODFiNGQ2YmViNmM5ZDFlNmRmMjlhOTU2ODkyZDEyMTU2Mzc1NWZjYmNmMjYzNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.as5etPSc73fGYcgGGn3eXAfgw2aMycAdyaWq9_BSRek">

了解！因为我看到这位作者也是用cloudflare，https://email-once.com/，但他的注册mega就正常（可能他是付费版），希望大佬能找到办法，感谢🙏

**Comment by dreamhunter2333** [comment]
应该是付费版了，这个邮件有 19K，比较大
<img width="264" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/32295532/e832f073-730a-4ce6-941a-d1f09ac2c08b">

**Comment by xiewei3536** [comment]
> 应该是付费版了，这个邮件有 19K，比较大 <img alt="image" width="264" src="https://private-user-images.githubusercontent.com/32295532/319498092-e832f073-730a-4ce6-941a-d1f09ac2c08b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTE5NjYsIm5iZiI6MTcxMjM5MTY2NiwicGF0aCI6Ii8zMjI5NTUzMi8zMTk0OTgwOTItZTgzMmYwNzMtNzMwYS00Y2U2LTk0MWEtZDFmMDlhYzJjMDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA4MjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNTgyN2EzMjNkNjBlNDM1ZGZkMjhlMGExZmM2NmRkZDhiNDE2ZWNmNDAxZWRlZjI4Yjc5NjgwOWY5YjdlMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.msmAhevySWFPo2x0lPuP9S_IDrS1qM9q7EwT2RM7WD4">

大佬，我升级到付费方案，依旧是这个错误Worker call resulted in an error: worker script exceeded CPU allocation
好像有其他问题存在

**Comment by xiewei3536** [comment]
@dreamhunter2333 

大佬，刚刚看了下介绍，会不会是因为用R2实现大附件的支持呢？
<img width="661" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/a25c6732-dfb3-4dda-a632-bf718efe56fc">

**Comment by dreamhunter2333** [comment]
我试一下

**Comment by dreamhunter2333** [comment]
测试了下，貌似是 mailparser 在 cf worker 运行的时候会死循环，我看看有什么办法，或者只能浏览器客户端来解析

**Comment by dreamhunter2333** [comment]
暂时特殊处理了下 mega.nz，后续再想办法处理

**Comment by dreamhunter2333** [comment]
实现了一版 rust mail parse 的代码，正在测试

**Comment by xiewei3536** [comment]
> 实现了一版 rust mail parse 的代码，正在测试 <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/32295532/320736489-7e713323-287e-42f0-97b3-d8ebc0580600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDI4MzQsIm5iZiI6MTcxMjY0MjUzNCwicGF0aCI6Ii8zMjI5NTUzMi8zMjA3MzY0ODktN2U3MTMzMjMtMjg3ZS00MmYwLTk3YjMtZDhlYmMwNTgwNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlM2JiZWU4YzY2OWMxZTA4NDcwNTFlYzkyZmU5OGQzMDIyYWNmMGI4MTQ3Y2JkMzM2NGMwNzVhMjU5OWY1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YG90iRsaxcLtqm4GWDRbRkDuErn9JpyQRg8wwirEDWs">

大佬牛逼！！
希望这次可以成功～～～

**Comment by dreamhunter2333** [comment]
> > 实现了一版 rust mail parse 的代码，正在测试 <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/32295532/320736489-7e713323-287e-42f0-97b3-d8ebc0580600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDI4MzQsIm5iZiI6MTcxMjY0MjUzNCwicGF0aCI6Ii8zMjI5NTUzMi8zMjA3MzY0ODktN2U3MTMzMjMtMjg3ZS00MmYwLTk3YjMtZDhlYmMwNTgwNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlM2JiZWU4YzY2OWMxZTA4NDcwNTFlYzkyZmU5OGQzMDIyYWNmMGI4MTQ3Y2JkMzM2NGMwNzVhMjU5OWY1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YG90iRsaxcLtqm4GWDRbRkDuErn9JpyQRg8wwirEDWs">
> 
> 大佬牛逼！！ 希望这次可以成功～～～

已经更新了，但是和旧版数据不兼容，之后会加个更新文档

**Comment by xiewei3536** [comment]
> > > 实现了一版 rust mail parse 的代码，正在测试 <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/32295532/320736489-7e713323-287e-42f0-97b3-d8ebc0580600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDI4MzQsIm5iZiI6MTcxMjY0MjUzNCwicGF0aCI6Ii8zMjI5NTUzMi8zMjA3MzY0ODktN2U3MTMzMjMtMjg3ZS00MmYwLTk3YjMtZDhlYmMwNTgwNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlM2JiZWU4YzY2OWMxZTA4NDcwNTFlYzkyZmU5OGQzMDIyYWNmMGI4MTQ3Y2JkMzM2NGMwNzVhMjU5OWY1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YG90iRsaxcLtqm4GWDRbRkDuErn9JpyQRg8wwirEDWs">
> > 
> > 
> > 大佬牛逼！！ 希望这次可以成功～～～
> 
> 已经更新了，但是和旧版数据不兼容，之后会加个更新文档

没问题！等大佬更新～
辛苦了❤️

**Comment by dreamhunter2333** [comment]
> > > > 实现了一版 rust mail parse 的代码，正在测试 <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/32295532/320736489-7e713323-287e-42f0-97b3-d8ebc0580600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDI4MzQsIm5iZiI6MTcxMjY0MjUzNCwicGF0aCI6Ii8zMjI5NTUzMi8zMjA3MzY0ODktN2U3MTMzMjMtMjg3ZS00MmYwLTk3YjMtZDhlYmMwNTgwNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlM2JiZWU4YzY2OWMxZTA4NDcwNTFlYzkyZmU5OGQzMDIyYWNmMGI4MTQ3Y2JkMzM2NGMwNzVhMjU5OWY1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YG90iRsaxcLtqm4GWDRbRkDuErn9JpyQRg8wwirEDWs">
> > > 
> > > 
> > > 大佬牛逼！！ 希望这次可以成功～～～
> > 
> > 
> > 已经更新了，但是和旧版数据不兼容，之后会加个更新文档
> 
> 没问题！等大佬更新～ 辛苦了❤️

https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.0

**Comment by xiewei3536** [comment]
> > > > > 实现了一版 rust mail parse 的代码，正在测试 <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/32295532/320736489-7e713323-287e-42f0-97b3-d8ebc0580600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDI4MzQsIm5iZiI6MTcxMjY0MjUzNCwicGF0aCI6Ii8zMjI5NTUzMi8zMjA3MzY0ODktN2U3MTMzMjMtMjg3ZS00MmYwLTk3YjMtZDhlYmMwNTgwNjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlM2JiZWU4YzY2OWMxZTA4NDcwNTFlYzkyZmU5OGQzMDIyYWNmMGI4MTQ3Y2JkMzM2NGMwNzVhMjU5OWY1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YG90iRsaxcLtqm4GWDRbRkDuErn9JpyQRg8wwirEDWs">
> > > > 
> > > > 
> > > > 大佬牛逼！！ 希望这次可以成功～～～
> > > 
> > > 
> > > 已经更新了，但是和旧版数据不兼容，之后会加个更新文档
> > 
> > 
> > 没问题！等大佬更新～ 辛苦了❤️
> 
> https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.0

感谢大佬～已经完美部署！
太棒了
