### ISSUE TITLE
能否增添自由发邮件的功能

### ISSUE THREAD

**Issue by lemongad** [dreamhunter2333/cloudflare_temp_email#98]
找到一个 worker代码，https://gist.github.com/ihsangan/6111b59b9a7b022b5897d28d8454ad8d
作者可以参考，实现功能
为作者项目点赞

**Comment by dreamhunter2333** [comment]
mailchannels 是第三方的服务，cf 的邮件功能目前只能收或者自动回复，发送邮件只能到验证的转发地址

**Comment by lemongad** [comment]
> mailchannels 是第三方的服务，cf 的邮件功能目前只能收或者自动回复，发送邮件只能到验证的转发地址

作者大大，发现一个仓库可以支持cf发邮件，但是不知道什么原理 https://github.com/oiov/vmail

**Comment by lemongad** [comment]
就是每次仓库代码改动都需要重新拉取部署吗？能否提供一个比较快捷方式，比如一键升级命令

**Comment by dreamhunter2333** [comment]
> 就是每次仓库代码改动都需要重新拉取部署吗？能否提供一个比较快捷方式，比如一键升级命令

好的我看一下怎么加个简单的方式

**Comment by dreamhunter2333** [comment]
看起来key通过这个来发送
https://github.com/giuseppelt/EmailFlare?tab=readme-ov-file#sending-emails-is-free

**Comment by lemongad** [comment]
> 找到一个 worker代码，https://gist.github.com/ihsangan/6111b59b9a7b022b5897d28d8454ad8d 作者可以参考，实现功能 为作者项目点赞

是的，上面代码也是根据MailChannels发件的，但是作者你找的这个时间好早，没想到2年前就可以利用这个发件了

**Comment by dreamhunter2333** [comment]
> > 找到一个 worker代码，https://gist.github.com/ihsangan/6111b59b9a7b022b5897d28d8454ad8d 作者可以参考，实现功能 为作者项目点赞
> 
> 
> 
> 是的，上面代码也是根据MailChannels发件的，但是作者你找的这个时间好早，没想到2年前就可以利用这个发件了

经过测试可以发送，我有空集成到现在的逻辑里

**Comment by dreamhunter2333** [comment]
https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.1 
已添加发送邮件功能

**Comment by xiewei3536** [comment]
> https://github.com/dreamhunter2333/cloudflare_temp_email/releases/tag/v0.2.1 已添加发送邮件功能

<img width="697" alt="image" src="https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/4f510a6e-7b95-4750-8e22-f0563abeb8a9">
大佬，请问这个发送请求是要由谁同意呢？

**Comment by xiewei3536** [comment]
@dreamhunter2333 
大佬，可以正常寄出。但收到邮件内容似乎有点问题，请帮忙看看是否哪里有问题，感谢！

![CleanShot 2024-04-12 at 14 19 03@2x](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/29998329/2dd0ba86-401b-466e-8431-ac5c19b14916)
